# GraphRAG Pipeline + Evaluace

Tento notebook obsahuje **dvě části**:

1. **Pipeline** (buňky 1–12) — načtení dokumentu, build grafu, indexy, retrievery, RAG chain
2. **Evaluace** (buňky 13+) — testovací sady, metrikY (BERTScore, ROUGE-L, RAGAS), `evaluate()`

**Důležité:** Evaluace volá přímo retrievery z pipeline (`full_retriever`, `standard_retriever`, `pure_graph_retriever`), takže výsledky jsou vždy identické s produkcí.

---

## Část 1 — Pipeline

In [ ]:
import hashlib
import inspect
import os
import pandas as pd
import pickle
import re
import threading
import time

from dotenv import load_dotenv
from IPython.display import display
from pydantic import BaseModel, Field
from yfiles_jupyter_graphs import GraphWidget

from neo4j import GraphDatabase
from langchain_community.graphs import Neo4jGraph
from langchain_community.vectorstores import Neo4jVector
from langchain_core.output_parsers import StrOutputParser
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.runnables import RunnablePassthrough
from langchain_experimental.graph_transformers import LLMGraphTransformer
from langchain_experimental.llms.ollama_functions import OllamaFunctions
from langchain_ollama import ChatOllama, OllamaEmbeddings
from langchain_text_splitters import MarkdownHeaderTextSplitter, RecursiveCharacterTextSplitter

load_dotenv()

True

In [ ]:
# Připojení k Neo4j 
graph = Neo4jGraph(
    url=os.environ.get('NEO4J_URI'),
    username=os.environ.get('NEO4J_USERNAME'),
    password=os.environ.get('NEO4J_PASSWORD')
)

# Inicializace modelu 
llm = OllamaFunctions(model="llama3.1:8b", temperature=0, format="json", num_predict=4096)

/var/folders/bq/dvsycyn560sgx_gql985ch9w0000gn/T/ipykernel_5993/319638709.py:2: LangChainDeprecationWarning: The class `Neo4jGraph` was deprecated in LangChain 0.3.8 and will be removed in 1.0. An updated version of the class exists in the `langchain-neo4j package and should be used instead. To use it run `pip install -U `langchain-neo4j` and import as `from `langchain_neo4j import Neo4jGraph``.
  graph = Neo4jGraph(
/var/folders/bq/dvsycyn560sgx_gql985ch9w0000gn/T/ipykernel_5993/319638709.py:9: LangChainDeprecationWarning: The class `OllamaFunctions` was deprecated in LangChain 0.0.64 and will be removed in 1.0. An updated version of the class exists in the `langchain-ollama package and should be used instead. To use it run `pip install -U `langchain-ollama` and import as `from `langchain_ollama import ChatOllama``.
  llm = OllamaFunctions(model="llama3.1:8b", temperature=0, format="json", num_predict=4096)

In [ ]:
file_path = "../documents/md/AF_III_02_01_06_Stroj_Planovani_PA.md"
cache_file = "../cache/AF_III_02_01_06_Stroj_Planovani_PA.pkl"

In [ ]:
with open(file_path, "r", encoding="utf-8") as f:
    md_content = f.read()

# 1. Rozšířené split podle nadpisů (H1 - H6)
headers_to_split_on = [
    ("#", "Header 1"), ("##", "Header 2"), ("###", "Header 3"),
    ("####", "Header 4"), ("#####", "Header 5"), ("######", "Header 6"),
]
markdown_splitter = MarkdownHeaderTextSplitter(headers_to_split_on=headers_to_split_on)
md_header_splits = markdown_splitter.split_text(md_content)

# 2. Zkrácení na logické celky
text_splitter = RecursiveCharacterTextSplitter(chunk_size=4000, chunk_overlap=400)
all_documents = text_splitter.split_documents(md_header_splits)

# Odstranění pomocných sekcí (obsah, literatura) — neobsahují znalostní obsah
documents = []
for doc in all_documents:
    h1 = doc.metadata.get("Header 1", "").strip().lower()
    
    # Pokud je hlavní nadpis "obsah" nebo "literatura", chunk zahodit
    if "obsah" in h1 or "zdroje" in h1 or "literatura" in h1:
        continue
        
    documents.append(doc)

print(f"Původně vytvořeno: {len(all_documents)} chunků.")
print(f"Po vyhození Obsahu zbylo k analýze: {len(documents)} čistých chunků.")

Původně vytvořeno: 153 chunků.
Po vyhození Obsahu zbylo k analýze: 150 čistých chunků.

In [ ]:
def get_chunk_hash(text):
    return hashlib.md5(text.encode('utf-8')).hexdigest()

# Výpočet MD5 hashů pro všechny chunky aktuálního dokumentu
for doc in documents:
    doc.metadata["hash"] = get_chunk_hash(doc.page_content)

# Načtení existujících hashů z Neo4j a oprava chybějících záznamů
driver = GraphDatabase.driver(
    os.environ.get('NEO4J_URI'),
    auth=(os.environ.get('NEO4J_USERNAME'), os.environ.get('NEO4J_PASSWORD'))
)

with driver.session() as session:
    result = session.run("MATCH (d:Document) RETURN d.text AS text, d.hash AS hash")
    records = list(result)

    neo4j_hashes = set()
    updates = []

    for record in records:
        if record["hash"]:
            neo4j_hashes.add(record["hash"])
        elif record["text"]:
            # Hash chybí — dopočítá se ze zdrojového textu a zařadí do opravné dávky
            computed_hash = get_chunk_hash(record["text"])
            neo4j_hashes.add(computed_hash)
            updates.append({"text": record["text"], "hash": computed_hash})

    if updates:
        print(f"Oprava chybějících hashů: {len(updates)} dokumentů")
        session.run("""
        UNWIND $updates AS up
        MATCH (d:Document {text: up.text})
        SET d.hash = up.hash
        """, {"updates": updates})

# Odstranění zastaralých chunků z Neo4j (smazané nebo upravené části dokumentu)
current_hashes = {doc.metadata["hash"] for doc in documents}
obsolete_hashes = neo4j_hashes - current_hashes

if obsolete_hashes:
    print(f"Odstraňuji zastaralé chunky z Neo4j: {len(obsolete_hashes)}")
    with driver.session() as session:
        for obs_hash in obsolete_hashes:
            session.run("MATCH (d:Document {hash: $hash}) DETACH DELETE d", {"hash": obs_hash})
        # Odstranění osiřelých entit bez jakékoliv vazby
        session.run("""
        MATCH (e)
        WHERE (e:Hlavni_Pojem OR e:Proces_Cinnost OR e:Nastroj_System OR
               e:Metrika_Parametr OR e:Subjekt_Role OR e:Kapitola OR e:Podkapitola)
          AND NOT (e)--()
        DELETE e
        """)
    neo4j_hashes -= obsolete_hashes
    print("Zastaralé chunky a osiřelé entity odstraněny.")

driver.close()

# Načtení lokální PKL cache
local_cache = {}
if os.path.exists(cache_file):
    with open(cache_file, "rb") as f:
        local_cache = pickle.load(f)

# Synchronizace PKL cache s aktuálním stavem dokumentu
obsolete_pkl_hashes = set(local_cache.keys()) - current_hashes

if obsolete_pkl_hashes:
    print(f"Čištění PKL cache: {len(obsolete_pkl_hashes)} zastaralých záznamů")
    for obs_hash in obsolete_pkl_hashes:
        del local_cache[obs_hash]
    with open(cache_file, "wb") as f:
        pickle.dump(local_cache, f)

# Určení chunků vyžadujících LLM extrakci
missing_in_neo4j = [doc for doc in documents if doc.metadata.get("hash") not in neo4j_hashes]
docs_for_llm = [doc for doc in missing_in_neo4j if doc.metadata.get("hash") not in local_cache]

print(f"Chunky v dokumentu:   {len(documents)}")
print(f"Chunky v Neo4j:       {len(neo4j_hashes)}")
print(f"Chunky v PKL cache:   {len(local_cache)}")
print(f"Chunky ke zpracování: {len(docs_for_llm)}")

# LLM extrakce entit a vztahů — pouze pro chunky chybějící v obou úložištích
if docs_for_llm:
    print(f"Spouštím LLM extrakci: {len(docs_for_llm)} chunků")

    universal_nodes = ["Hlavni_Pojem", "Proces_Cinnost", "Nastroj_System", "Metrika_Parametr", "Subjekt_Role"]
    universal_relationships = ["SKLADA_SE_Z", "VYUZIVA", "MA_VLASTNOST", "PROVADI", "SOUVISI_S"]

    llm_transformer = LLMGraphTransformer(
        llm=llm, allowed_nodes=universal_nodes, allowed_relationships=universal_relationships
    )

    # Iterativní zpracování s průběžným ukládáním cache po každém chunku
    for i, doc in enumerate(docs_for_llm):
        doc_hash = doc.metadata["hash"]
        print(f"  {i+1}/{len(docs_for_llm)} (hash: {doc_hash[:8]})")
        try:
            extracted_graphs = llm_transformer.convert_to_graph_documents([doc])
            if extracted_graphs:
                local_cache[doc_hash] = extracted_graphs[0]
                with open(cache_file, "wb") as f:
                    pickle.dump(local_cache, f)
        except Exception as e:
            print(f"  Chyba u chunku {i+1}, přeskočeno: {e}")
            continue

    print("Extrakce dokončena.")
else:
    if missing_in_neo4j:
        print("Všechna chybějící data načtena z PKL cache, LLM extrakce není vyžadována.")
    else:
        print("Neo4j je aktuální, žádné zpracování není vyžadováno.")

# Příprava grafových dokumentů k nahrání do Neo4j
new_graph_documents = [
    local_cache[doc.metadata["hash"]]
    for doc in missing_in_neo4j
    if doc.metadata.get("hash") in local_cache
]

📊 Celkem chunků v textu: 150
🗄️ Z toho už je v Neo4j: 150
📁 Z toho už máme předpočítáno v PKL: 150
🔥 Bude se přes LLM reálně počítat: 0 chunků
✅ LLM není potřeba, všechna data už jsou v Neo4j.

In [ ]:
# Nahrání extrahovaných grafových dokumentů do Neo4j
if new_graph_documents:
    print(f"Nahrávám {len(new_graph_documents)} dokumentů do Neo4j...")
    graph.add_graph_documents(
        new_graph_documents,
        baseEntityLabel=True,
        include_source=True  # Vytvoří uzel Document propojený s extrahovanými entitami
    )
    print("Nahrání dokončeno.")
else:
    print("Neo4j je aktuální, žádné nové dokumenty k nahrání.")

# Sestavení hierarchie kapitol z metadat chunků
print("Sestavuji stromovou strukturu kapitol...")

driver = GraphDatabase.driver(
    os.environ.get('NEO4J_URI'),
    auth=(os.environ.get('NEO4J_USERNAME'), os.environ.get('NEO4J_PASSWORD'))
)

with driver.session() as session:
    for doc in documents:
        chunk_hash = doc.metadata.get("hash")

        # Sestavení cesty nadpisů H1–H6 pro daný chunk
        # Složené path_id zajišťuje jedinečnost podkapitol se stejným názvem napříč kapitolami
        path_nodes = []
        current_path_id = ""

        for i in range(1, 7):
            h = doc.metadata.get(f"Header {i}")
            if h:
                current_path_id = f"{current_path_id} | {h}" if current_path_id else h
                path_nodes.append({"id": current_path_id, "name": h, "level": i})

        if not path_nodes:
            path_nodes = [{"id": "Obecné", "name": "Obecné", "level": 1}]

        # Vytvoření uzlů Kapitola a propojení do stromové hierarchie
        for i, item in enumerate(path_nodes):
            session.run(
                """
                MERGE (k:Kapitola {id: $id})
                SET k.nazev = $name, k.uroven = $level
                """,
                {"id": item["id"], "name": item["name"], "level": item["level"]}
            )

            # Propojení podkapitoly s nadřazenou kapitolou
            if i > 0:
                parent_item = path_nodes[i - 1]
                session.run(
                    """
                    MATCH (parent:Kapitola {id: $parent_id})
                    MATCH (child:Kapitola {id: $child_id})
                    MERGE (parent)-[:OBSAHUJE_PODKAPITOLU]->(child)
                    """,
                    {"parent_id": parent_item["id"], "child_id": item["id"]}
                )

        # Propojení nejhlubšího uzlu hierarchie s textovým chunkem
        leaf_item = path_nodes[-1]
        session.run(
            """
            MATCH (d:Document {hash: $hash})
            MATCH (k:Kapitola {id: $leaf_id})
            MERGE (k)-[:OBSAHUJE_TEXT]->(d)
            """,
            {"hash": chunk_hash, "leaf_id": leaf_item["id"]}
        )

driver.close()
print("Hierarchie kapitol sestavena.")

✅ Znalosti v Neo4j jsou stoprocentně aktuální, není co přidávat.
⏳ Buduji pevnou stromovou strukturu kapitol z metadat...
✅ Hierarchie kapitol byla úspěšně vygenerována a propojena s texty a entitami!

In [ ]:
# Inicializace embeddingového modelu
embeddings = OllamaEmbeddings(
    model="nomic-embed-text",
    num_ctx=8192  # Maximální kontextové okno modelu nomic-embed-text
)

# Vytvoření hybridního vektorového indexu nad uzly Document
try:
    vector_index = Neo4jVector.from_existing_graph(
        embeddings,
        search_type="hybrid",
        node_label="Document",
        text_node_properties=["text"],
        embedding_node_property="embedding"
    )
    vector_retriever = vector_index.as_retriever(search_kwargs={"k": 10})
    print("Vektorový index vytvořen.")
except Exception as e:
    print(f"Chyba při vytváření vektorového indexu: {e}")

# Vytvoření fulltextového indexu nad entitami a kapitolami
def create_fulltext_index():
    driver = GraphDatabase.driver(
        os.environ['NEO4J_URI'],
        auth=(os.environ['NEO4J_USERNAME'], os.environ['NEO4J_PASSWORD'])
    )
    with driver.session() as session:
        # Znovuvytvoření indexu — zajišťuje konzistenci při opakovaném spuštění
        session.run("DROP INDEX fulltext_entity_id IF EXISTS")
        session.run("""
        CREATE FULLTEXT INDEX fulltext_entity_id IF NOT EXISTS
        FOR (n:__Entity__|Kapitola|Podkapitola)
        ON EACH [n.id, n.nazev]
        """)
    driver.close()

create_fulltext_index()
print("Fulltextový index nad entitami a kapitolami vytvořen.")

✅ Vektorový index úspěšně vytvořen s max. kontextem.
✅ Fulltextový index pokrývající entity i kapitoly je připraven.

In [ ]:
# Inicializace embeddingového modelu pro manuální indexaci
embeddings_model = OllamaEmbeddings(
    model="nomic-embed-text",
    num_ctx=8192  # Maximální kontextové okno modelu nomic-embed-text
)

driver = GraphDatabase.driver(
    os.environ['NEO4J_URI'],
    auth=(os.environ['NEO4J_USERNAME'], os.environ['NEO4J_PASSWORD'])
)

def build_vector_index():
    with driver.session() as session:
        # Odstranění stávajícího indexu před znovuvytvořením
        session.run("DROP INDEX vector IF EXISTS")

        # Načtení uzlů Document bez embeddingu
        result = session.run(
            "MATCH (d:Document) WHERE d.embedding IS NULL RETURN d.id as id, d.text as text"
        )
        nodes = [{"id": r["id"], "text": r["text"]} for r in result]

        print(f"Uzly ke zpracování: {len(nodes)}")

        for i, node in enumerate(nodes):
            try:
                # Text oříznut na 8 000 znaků
                safe_text = node["text"][:8000]
                vector = embeddings_model.embed_query(safe_text)
                session.run(
                    "MATCH (d:Document {id: $id}) SET d.embedding = $vector",
                    {"id": node["id"], "vector": vector}
                )
                if (i + 1) % 10 == 0:
                    print(f"  Zpracováno {i+1}/{len(nodes)}")
            except Exception as e:
                print(f"  Chyba u uzlu {node['id']}: {e}")

        # Vytvoření vektorového indexu nad existujícími embeddingy
        session.run("""
            CREATE VECTOR INDEX vector IF NOT EXISTS
            FOR (m:Document) ON (m.embedding)
            OPTIONS {indexConfig: {
              `vector.dimensions`: 768,
              `vector.similarity_function`: 'cosine'
            }}
        """)
        print("Vektorový index vytvořen.")

build_vector_index()
driver.close()

🧹 Starý index smazán.
📦 Nalezeno 0 dokumentů v DB. Spouštím individuální embedding...
✅ Vektorový index úspěšně vytvořen manuálně.

In [ ]:
# Dense retriever — kosinová podobnost (baseline Naive RAG)
neo4j_dense_index = Neo4jVector.from_existing_index(
    embeddings,
    index_name="vector",
    search_type="vector",
    node_label="Document",
    text_node_property="text"
)
dense_retriever = neo4j_dense_index.as_retriever(search_kwargs={"k": 20})

# Hybridní retriever — kosinová podobnost + BM25 (Hybrid GraphRAG)
neo4j_hybrid_index = Neo4jVector.from_existing_index(
    embeddings,
    index_name="vector",
    search_type="hybrid",
    keyword_index_name="keyword",
    node_label="Document",
    text_node_property="text"
)
hybrid_retriever = neo4j_hybrid_index.as_retriever(search_kwargs={"k": 20})

print("dense_retriever  — search_type=vector")
print("hybrid_retriever — search_type=hybrid")

✅ dense_retriever  — search_type=vector (Naive RAG)
✅ hybrid_retriever — search_type=hybrid (Hybrid GraphRAG)

In [ ]:
# Schéma pro strukturovaný výstup extrakce entit
class Entities(BaseModel):
    """Informace o klíčových entitách a pojmech v textu."""
    names: list[str] = Field(
        ...,
        description="Všechny klíčové pojmy, technické termíny, procesy a funkce. ZÁSADNÍ: Nesekej víceslovná spojení (např. 'funkce prediktivní analytiky', 'řízení dopravy') na jednotlivá slova!",
    )

# Inicializace modelů
# llm_extraction bez num_predict — parametr je relevantní pouze pro LLMGraphTransformer
# llm_rag s rozšířeným kontextem num_ctx=32768 pro zpracování dlouhého retrieval kontextu
llm_extraction = OllamaFunctions(model="llama3.1:8b", temperature=0, format="json")
llm_rag = ChatOllama(
    model="llama3.1:8b",
    temperature=0,
    num_ctx=32768
)

# Few-shot prompt pro extrakci entit z uživatelského dotazu
extraction_prompt = ChatPromptTemplate.from_messages([
    ("system", """Jsi expert na extrakci klíčových pojmů z odborných dotazů pro vyhledávání v databázi.
Tvým úkolem je z uživatelské otázky vyextrahovat hlavní entity.

ZÁSADNÍ PRAVIDLO: Odborné pojmy, víceslovné názvy, vlastnosti, metriky nebo procesy ponechávej v celku! Nesekej ustálená spojení na jednotlivá slova.

PŘÍKLADY SPRÁVNÉHO CHOVÁNÍ:
Otázka: "Co je to sekvenční diagram?"
Entity: ["sekvenční diagram"]

Otázka: "Jaké jsou fáze buněčného dělení v biologii?"
Entity: ["fáze buněčného dělení", "biologie"]

Otázka: "Co patří pod funkce prediktivní analytiky v marketingu?"
Entity: ["funkce prediktivní analytiky v marketingu"]

Otázka: "Jaké jsou výhody agilního řízení projektů?"
Entity: ["výhody agilního řízení projektů"]
"""),
    ("human", "{question}")
])

# Extrakční pipeline s validací výstupu přes Pydantic schéma
entity_chain = extraction_prompt | llm_extraction.with_structured_output(Entities)

In [ ]:
def graph_enhanced_retriever(question: str):
    try:
        entities = entity_chain.invoke({"question": question})
        print(f"Extrahované entity: {entities.names}")

        all_documents = []
        seen_docs = set()
        search_queries = []

        relations_text = ""
        seen_relations = set()

        # Sestavení Lucene dotazů z extrahovaných entit
        for entity in entities.names:
            words = [w.lower() for w in entity.split() if len(w) >= 3]
            if words:
                lucene_query = " AND ".join([f"*{w[:5]}*" for w in words])
                search_queries.append(lucene_query)

        # Doplňkový dotaz sestavený přímo ze slov otázky
        question_words = [w.lower() for w in re.findall(r'\w+', question) if len(w) >= 3]
        if question_words:
            direct_query = " OR ".join([f"*{w[:5]}*" for w in question_words])
            search_queries.append(direct_query)

        search_queries = list(set(search_queries))

        for lucene_query in search_queries:
            printed_nodes = set()

            
            response = graph.query(
                """
                CALL db.index.fulltext.queryNodes('fulltext_entity_id', $lucene_query, {limit: 5})
                YIELD node

                // Traversal dolů pouze pro listové uzly bez přímých podkapitol
                OPTIONAL MATCH (node)-[:OBSAHUJE_PODKAPITOLU]->(direct_child)
                WITH node, count(direct_child) AS child_count

                OPTIONAL MATCH (node)-[:OBSAHUJE_PODKAPITOLU*1..5]->(sub_k)
                    WHERE child_count = 0

                // Traversal nahoru zachytí preamble chunky na úrovni H1
                OPTIONAL MATCH (parent_k:Kapitola)-[:OBSAHUJE_PODKAPITOLU*1..3]->(node)

                WITH node,
                     collect(DISTINCT sub_k) + [node] + collect(DISTINCT parent_k) AS all_nodes
                UNWIND all_nodes AS search_node

                MATCH (doc:Document)
                WHERE (doc)-[:MENTIONS]->(search_node) OR (search_node)-[:OBSAHUJE_TEXT]->(doc)

                OPTIONAL MATCH (doc)-[:MENTIONS]->(kapitola_entity:__Entity__)
                WHERE labels(node)[0] = 'Kapitola'

                OPTIONAL MATCH (node)-[r]-(neighbor)
                WHERE type(r) <> 'MENTIONS' AND type(r) <> 'OBSAHUJE_TEXT' AND type(r) <> 'OBSAHUJE_PODKAPITOLU'

                RETURN DISTINCT
                    node.id AS entity_name,
                    labels(node)[0] AS node_type,
                    type(r) AS relation,
                    neighbor.id AS related_entity,
                    kapitola_entity.id AS podrizena_entita,
                    doc.text AS source_doc
                LIMIT 50
                """,
                {"lucene_query": lucene_query}
            )

            for r in response:
                node_name = r.get('entity_name')
                node_type = r.get('node_type', 'neznámý typ')
                rel = r.get('relation')
                neighbor = r.get('related_entity')
                podrizena_entita = r.get('podrizena_entita')

                if node_name not in printed_nodes:
                    print(f"  Nalezen uzel [{node_type}]: '{node_name}'")
                    printed_nodes.add(node_name)

                if rel and neighbor:
                    rel_str = f"Položka '{neighbor}' (vztah ke '{node_name}': {rel})"
                    if rel_str not in seen_relations:
                        relations_text += f"- {rel_str}\n"
                        seen_relations.add(rel_str)

                if podrizena_entita:
                    sub_ent_str = f"Kapitola '{node_name}' obsahuje entitu: '{podrizena_entita}'"
                    if sub_ent_str not in seen_relations:
                        relations_text += f"- {sub_ent_str}\n"
                        seen_relations.add(sub_ent_str)

                doc = r.get('source_doc')
                if doc and doc not in seen_docs and len(doc) > 100:
                    all_documents.append(doc)
                    seen_docs.add(doc)

        print(f"Nalezeno dokumentů z grafu: {len(all_documents)}")
        return relations_text, all_documents

    except Exception as e:
        print(f"Chyba v grafovém retrieveru: {e}")
        return "", []

In [ ]:
# Cross-encoder reranker pro přeřazení dokumentů podle relevance k dotazu
# Použit multilingvální model trénovaný na datasetu mMARCO (včetně češtiny)
try:
    from sentence_transformers import CrossEncoder
    reranker = CrossEncoder("cross-encoder/mmarco-mMiniLMv2-L12-H384-v1")
    RERANKER_AVAILABLE = True
    print("Cross-encoder načten: mmarco-mMiniLMv2-L12-H384-v1")
except ImportError:
    RERANKER_AVAILABLE = False
    print("sentence-transformers neni dostupne, reranking preskocen")


def rerank_docs(question: str, docs, top_k: int = 10, label: str = ""):
    if not docs or not RERANKER_AVAILABLE:
        return docs[:top_k]

    # Podpora pro Document objekty i prosté řetězce
    texts = [doc.page_content if hasattr(doc, "page_content") else doc for doc in docs]
    pairs = [(question, text) for text in texts]
    scores = reranker.predict(pairs)
    ranked = sorted(zip(scores, docs), key=lambda x: x[0], reverse=True)

    print(f"  Reranking {label}({len(docs)} dokumentů → top {top_k}):")
    print(f"  {'Pořadí':<7} {'Skóre':>7}  Náhled")
    print("  " + "-" * 70)
    for rank_i, (score, doc) in enumerate(ranked, 1):
        text = doc.page_content if hasattr(doc, "page_content") else doc
        preview = text[:120].replace("\n", " ")
        marker = "+" if rank_i <= top_k else "-"
        print(f"  {marker} #{rank_i:<3} {score:>7.3f}  {preview}...")
    print()

    return [doc for _, doc in ranked[:top_k]]

✅ Multilingual cross-encoder načten: mmarco-mMiniLMv2-L12-H384-v1
   Podporuje češtinu (trénováno na mMARCO multilingválním datasetu).

In [ ]:
def full_retriever(question: str):
    # Vektorové vyhledávání — hybridní retriever (kosinová podobnost + BM25, k=20)
    vector_docs = hybrid_retriever.invoke(question)
    print(f"Vektorové vyhledávání: {len(vector_docs)} dokumentů")
    print("-" * 60)
    for i, doc in enumerate(vector_docs):
        meta = {k: v for k, v in doc.metadata.items() if k != "hash" and v}
        meta_str = " | ".join(str(v) for v in meta.values()) if meta else "(bez metadat)"
        preview = doc.page_content[:200].replace("\n", " ")
        print(f"  [{i+1}] {meta_str}")
        print(f"        {preview}...")
    print("-" * 60)

    graph_relations_text, graph_docs_list = graph_enhanced_retriever(question)
    print(f"Grafové vyhledávání: {len(graph_docs_list)} dokumentů")
    print("-" * 60)
    for i, doc_text in enumerate(graph_docs_list):
        preview = doc_text[:200].replace("\n", " ")
        print(f"  [{i+1}] {preview}...")
    print("-" * 60)

    reranked_vector = rerank_docs(question, vector_docs, top_k=10, label="[vector] ")
    reranked_graph = rerank_docs(question, graph_docs_list, top_k=10, label="[graph] ") if graph_docs_list else []

    # Výpis finálního pořadí dokumentů předaných LLM
    print("Finální pořadí — vektorové dokumenty:")
    print("  " + "-" * 70)
    for rank_i, doc in enumerate(reranked_vector, 1):
        text = doc.page_content if hasattr(doc, "page_content") else doc
        meta = {k: v for k, v in doc.metadata.items() if k != "hash" and v} if hasattr(doc, "metadata") else {}
        meta_str = " | ".join(str(v) for v in meta.values()) if meta else "(bez metadat)"
        preview = text[:150].replace("\n", " ")
        print(f"  #{rank_i:<3} {meta_str}")
        print(f"        {preview}...")
    print()

    if reranked_graph:
        print("Finální pořadí — grafové dokumenty:")
        print("  " + "-" * 70)
        for rank_i, doc in enumerate(reranked_graph, 1):
            text = doc.page_content if hasattr(doc, "page_content") else doc
            preview = text[:150].replace("\n", " ")
            print(f"  #{rank_i:<3} {preview}...")
        print()

    vector_text = "\n\n".join(
        doc.page_content if hasattr(doc, "page_content") else doc
        for doc in reranked_vector
    )
    graph_text = "\n\n".join(reranked_graph)

    # Ořez kontextu — llama3.1:8b spolehlivě zpracuje přibližně 10 000 znaků
    graph_text_trimmed  = graph_text[:8000]
    vector_text_trimmed = vector_text[:3000]
    graph_rel_trimmed   = graph_relations_text[:1500]

    # Grafové dokumenty jsou primárním zdrojem — řazeny na první pozici v kontextu
    context = (
        f"### 1. DOKUMENTY Z GRAFU (PRIMÁRNÍ ZDROJ - ČTĚTE CELÉ, ODPOVĚĎ JE ZDE):\n{graph_text_trimmed}"
        f"\n\n### 2. VEKTOROVÉ DOKUMENTY (Doplňující textový kontext):\n{vector_text_trimmed}"
        f"\n\n### 3. VZTAHY Z GRAFU (Strukturální kontext):\n{graph_rel_trimmed}"
    )

    # Náhled kontextu odeslaného do LLM
    char_count = len(context)
    sep = "=" * 70
    print(f"Kontext odeslaný do LLM ({char_count:,} znaků):")
    print(sep)
    print("[Sekce 1 — grafové dokumenty]")
    print(graph_text_trimmed[:800].replace("\n\n", "\n") + ("…" if len(graph_text_trimmed) > 800 else ""))
    print()
    print("[Sekce 2 — vektorové dokumenty]")
    print(vector_text_trimmed[:800].replace("\n\n", "\n") + ("…" if len(vector_text_trimmed) > 800 else ""))
    print()
    print("[Sekce 3 — vztahy z grafu]")
    print(graph_rel_trimmed[:800] + ("…" if len(graph_rel_trimmed) > 800 else ""))
    print(sep)

    return context

In [ ]:
template = """

Jsi expertní analytický systém pracující s technickou dokumentací.

### KRITICKÁ PRAVIDLA:
1. ODPOVÍDEJ POUZE NA ZÁKLADĚ DODANÉHO KONTEXTU.
2. Pro výčty použij odrážkový seznam, pro definice odstavce.
3. KOMPLETNÍ VÝČET BEZ ZKRACOVÁNÍ — žádné "a další", "apod.", "atd.".

### KONTEXT:
{context}

### OTÁZKA:
{question}


### ODPOVĚĎ:"""

prompt = ChatPromptTemplate.from_template(template)

# Sestavení RAG chain: retrieval → prompt → LLM → parsování výstupu
chain = (
    {"context": full_retriever, "question": RunnablePassthrough()}
    | prompt
    | llm_rag
    | StrOutputParser()
)

print("RAG chain připraven.")

✅ RAG chain s přísným promptem vytvořen!

### Rychlý test pipeline
Otázku pro ověření, že vše funguje.

In [ ]:
print(chain.invoke("Jaké jsou funkce prediktivní analytiky v plánování nákupu?"))

--- HLEDÁM ODPOVĚĎ NA: 'Jaké jsou funkce prediktivní analytiky v plánování nákupu?' ---

📚 VEKTOROVÉ VYHLEDÁVÁNÍ — nalezeno 20 dokumentů (před rerankingem):
------------------------------------------------------------
  [1] 📂 19. Operativní řízení a plánování výroby
       💬 Účelem kapitoly je vymezit funkcionalitu prediktivní analytiky v rámci operativního řízení a plánování výroby, definovat cílové proměnné a prediktory, formulovat analytické otázky pro konzultace analy...
  [2] 📂 15. Prediktivní analytika obchodu a logistiky
       💬 Účelem kapitoly je vymezit základní funkce prediktivní analytiky v rámci plánování v oblasti marketingu, řízení prodeje, nákupu a dopravy. Pro každou s oblastí jsou definovány cílové proměnné a vybran...
  [3] 📂 14. Prediktivní analytika ve finančním řízení
       💬 Účelem kapitoly  je  vymezit  funkce  prediktivní  analytiky  v rámci  finančního  plánování  a tvorby rozpočtů. Ta je základem pro definování cílových proměnných a jim odpovídajících prediktorů. V rá...
  [4] 📂 16. Prediktivní analytika v personálním řízení
       💬 Účelem kapitoly je definovat obsah a hlavní funkce prediktivní analytiky v rámci personálního plánování. Na ně navazuje definování cílových proměnných v personálním řízení a podstatné prediktory. Násl...
  [5] 📂 18. Prediktivní analytika v řízení výrobních zakázek
       💬 Účelem kapitoly je vymezit základní funkce prediktivní analytiky v rámci plánování výrobních zakázek, definování cílových proměnných a odpovídajících prediktorů. Jsou zde specifikovány  analytické  ot...
  [6] 📂 12.1 Hlavní principy prediktivní analytiky | 12. Principy a funkce uplatňované v prediktivní analytice
       💬 Obsah plánování a prediktivní analytiky je velmi variantní podle odvětví, typu a zaměření firem a jeho zvládnutí je pro analytiky hodně náročné. Z pohledu řízení firmy je ale samotným základem pro pre...
  [7] 📂 17. Prediktivní analytika v řízení investic, údržby a potřeby energií
       💬 Účelem kapitoly je vymezit hlavní funkce prediktivní analytiky v rámci plánování investic, údržby a potřeby energií strojírenské firmy. Na ty standardně navazuje definování cílových proměnných a predi...
  [8] 📂 12.3 Závěry | 12. Principy a funkce uplatňované v prediktivní analytice
       💬 Uvedené dílčí funkce, které jsou spojeny s prediktivní analytikou můžeme pracovně pokládat za jednotlivé stavební kameny jejích řešení. Váží se k nim následující poznámky:   - Základní vymezení funkcí...
  [9] 📂 18.3 Řešení prediktivní analytiky v plánování výrobních zakázek | 18. Prediktivní analytika v řízení výrobních zakázek
       💬 **Funkce prediktivní analytiky v plánování výrobních zakázek:**   - Clustering: - klastry výrobních zakázek podle zákazníků strojírenské firmy, objemu zakázek, plánovaných termínů dokončení. o   - Kla...
  [10] 📂 C. Prediktivní analytika firmy podle oblastí řízení
       💬 | [12] Principy a funkce prediktivní analytiky      | [12] Principy a funkce prediktivní analytiky           | |---------------------------------------------------|------------------------------------...
  [11] 📂 7.6 Plánování dopravy | 7. Plánování obchodu a logistiky
       💬 Plánování dopravních potřeb a jejich zajištění ve firmě představují tuto funkcionalitu:   - Plánování  jednotlivých  ukazatelů  řízení  dopravy ,  např.  nákladů  na  dopravu,  výkonu  dopravy, využit...
  [12] 📂 17.2 Prediktivní analytika v plánování potřeby energií | 17. Prediktivní analytika v řízení investic, údržby a potřeby energií | 17.2.3 Řešení prediktivní analytiky v řízení energií
       💬 **Funkce prediktivní analytiky v plánování potřeby energií:**   - Clustering: - klastry poskytovatelů energií pro strojírenskou firmu podle druhů energií, objemu dodávek. o   - Klasifikace :   - klasi...
  [13] 📂 A. Principy a podstata plánovacích úloh v řízení firmy
       💬 **[2] Podstata plánovacích úloh**   (Funkcionalita a využití plánovacích úloh se zaměřením na výrobu, resp. strojírenství.)   **[3] Principy a řešení plánovacích úloh v BI**   (Principy změn v analyti...
  [14] 📂 19.1 Obsah prediktivní analytiky v operativním plánování výroby | 19. Operativní řízení a plánování výroby
       💬 Prediktivní analytika v operativním řízení výroby zajišťuje tři druhy na sebe se vážících operací (Tomek, Vávrová, 2014):   - operativní plánování prodeje, - operativní plánování výroby, - operativní ...
  [15] 📂 21. Závěr
       💬 Text tvoří jeden z textů řady III úrovně portálu https://mbi-af.cz v tomto případě zaměřený na plánování a prediktivní analytiku strojírenských firem. Jeho cílem bylo prezentovat celkový pohled na plá...
  [16] 📂 1. Úvodní poznámky a souvislosti
       💬 Strategické Fizeni   Plánování a plánovací úlohy představují jednu ze základních a velmi významných komponent řízení firmy . Mají specifickou funkcionalitu, specifické určení i specifické technologie ...
  [17] 📂 13.3 Řešení prediktivní analytiky ve strategickém řízení | 13. Strategické řízení
       💬 **Příklady prediktivní analytiky:**   - Určování cílových hodnot, např. EBITDA (Earnings Before Interest, Taxes, Depreciation and Amortization) podle Objemu výrobních zakázek. - Klasifikace vlastních ...
  [18] 📂 18.1 Obsah prediktivní analytiky v plánování výrobních zakázek | 18. Prediktivní analytika v řízení výrobních zakázek
       💬 Prediktivní analytika v řízení výrobních zakázek má poskytovat podporu v těchto plánovacích aktivitách:   - plánování výrobních postupů a termínů výroby, - určení konkrétních strojů a zařízení pro dan...
  [19] 📂 12. Principy a funkce uplatňované v prediktivní analytice
       💬 Účelem kapitoly je uvést přehled základních principů analytických funkcí s vymezením jejich podstaty a příkladů využití. Ty budou konkretizovány podle oblastí řízení strojírenské firmy. Jde zde zejmén...
  [20] 📂 17.2 Prediktivní analytika v plánování potřeby energií | 17. Prediktivní analytika v řízení investic, údržby a potřeby energií | 17.2.1 Obsah prediktivní analytiky v plánování potřeby energií
       💬 Prediktivní analytika v řízení energií má poskytovat podporu v těchto plánovacích aktivitách:   - zpracování plánů řízení spotřeby energií - hodnocení požadavků na energie podle různých hledisek (dime...
------------------------------------------------------------
🔍 Nalezené entity pro graf: ['funkce prediktivní analytiky v plánování nákupu']
🎯 Přímý fulltext dotaz do grafu: *jaké* OR *jsou* OR *funkc* OR *predi* OR *analy* OR *pláno* OR *nákup*
  🎯 ZÁCHYT V GRAFU: Nalezen uzel [Kapitola] s názvem '15. Prediktivní analytika obchodu a logistiky | 15.3 Prediktivní analytika v plánování nákupu'
  🎯 ZÁCHYT V GRAFU: Nalezen uzel [Kapitola] s názvem '15. Prediktivní analytika obchodu a logistiky | 15.3 Prediktivní analytika v plánování nákupu | 15.3.3 Řešení prediktivní analytiky v řízení nákupu'
  🎯 ZÁCHYT V GRAFU: Nalezen uzel [Kapitola] s názvem '15. Prediktivní analytika obchodu a logistiky | 15.3 Prediktivní analytika v plánování nákupu | 15.3.1 Obsah prediktivní analytiky v řízeni nákupu'
  🎯 ZÁCHYT V GRAFU: Nalezen uzel [Kapitola] s názvem '12. Principy a funkce uplatňované v prediktivní analytice'
  🎯 ZÁCHYT V GRAFU: Nalezen uzel [Kapitola] s názvem 'Závěry k oddílu C: Plánování a prediktivní analytika'
✅ CELKEM z grafu: 5 unikátních dokumentů

🕸️  GRAFOVÉ VYHLEDÁVÁNÍ — nalezeno 5 dokumentů (před rerankingem):
------------------------------------------------------------
  [1] 💬 Účelem kapitoly je vymezit základní funkce prediktivní analytiky v rámci plánování v oblasti marketingu, řízení prodeje, nákupu a dopravy. Pro každou s oblastí jsou definovány cílové proměnné a vybran...
  [2] 💬 **Analytické otázky :**   - Jak zvýšit úspěšnost a výkonnost byznysu díky vysoké kvalitě plánovacích úloh při řízení nákupů? - Jak co nejpřesněji a včas zjišťovat budoucí předpokládané potřeby zboží a...
  [3] 💬 Prediktivní analytika v řízení nákupů podporuje prognózování a plánování nákupů materiálů, zboží a služeb pro potřeby firmy. V oblasti plánování nákupů má zejména připravovat podklady pro tyto operace...
  [4] 💬 Účelem kapitoly je uvést přehled základních principů analytických funkcí s vymezením jejich podstaty a příkladů využití. Ty budou konkretizovány podle oblastí řízení strojírenské firmy. Jde zde zejmén...
  [5] 💬 Oddíl se zaměřil na základní obsah prediktivní analytiky strojírenské firmy ve vazbě na potřeby jejího prognózování a plánování. Předmětem řešení nebyly ani v tomto případě jednotlivé nástroje a jejic...
------------------------------------------------------------

🔀 Reranking vektorových dokumentů...
  📊 Reranking [vector] (20 docs → top 10):
  Rank    Score  Preview
  ----------------------------------------------------------------------
  ✅ #1     8.972  Účelem kapitoly je vymezit základní funkce prediktivní analytiky v rámci plánování v oblasti marketingu, řízení prodeje,...
  ✅ #2     8.471  Prediktivní analytika v operativním řízení výroby zajišťuje tři druhy na sebe se vážících operací (Tomek, Vávrová, 2014)...
  ✅ #3     7.278  Prediktivní analytika v řízení výrobních zakázek má poskytovat podporu v těchto plánovacích aktivitách:   - plánování vý...
  ✅ #4     5.865  Účelem kapitoly je vymezit základní funkce prediktivní analytiky v rámci plánování výrobních zakázek, definování cílovýc...
  ✅ #5     4.956  **Funkce prediktivní analytiky v plánování výrobních zakázek:**   - Clustering: - klastry výrobních zakázek podle zákazn...
  ✅ #6     4.868  Účelem kapitoly je vymezit funkcionalitu prediktivní analytiky v rámci operativního řízení a plánování výroby, definovat...
  ✅ #7     4.864  Účelem kapitoly je vymezit hlavní funkce prediktivní analytiky v rámci plánování investic, údržby a potřeby energií stro...
  ✅ #8     4.551  **Funkce prediktivní analytiky v plánování potřeby energií:**   - Clustering: - klastry poskytovatelů energií pro strojí...
  ✅ #9     4.404  Účelem kapitoly je definovat obsah a hlavní funkce prediktivní analytiky v rámci personálního plánování. Na ně navazuje ...
  ✅ #10    4.379  Účelem kapitoly  je  vymezit  funkce  prediktivní  analytiky  v rámci  finančního  plánování  a tvorby rozpočtů. Ta je z...
  ❌ #11    3.757  | [12] Principy a funkce prediktivní analytiky      | [12] Principy a funkce prediktivní analytiky           | |--------...
  ❌ #12    3.707  Obsah plánování a prediktivní analytiky je velmi variantní podle odvětví, typu a zaměření firem a jeho zvládnutí je pro ...
  ❌ #13    3.601  Prediktivní analytika v řízení energií má poskytovat podporu v těchto plánovacích aktivitách:   - zpracování plánů řízen...
  ❌ #14    2.182  **Příklady prediktivní analytiky:**   - Určování cílových hodnot, např. EBITDA (Earnings Before Interest, Taxes, Depreci...
  ❌ #15    1.994  Strategické Fizeni   Plánování a plánovací úlohy představují jednu ze základních a velmi významných komponent řízení fir...
  ❌ #16    1.775  Text tvoří jeden z textů řady III úrovně portálu https://mbi-af.cz v tomto případě zaměřený na plánování a prediktivní a...
  ❌ #17   -0.270  Uvedené dílčí funkce, které jsou spojeny s prediktivní analytikou můžeme pracovně pokládat za jednotlivé stavební kameny...
  ❌ #18   -2.395  Účelem kapitoly je uvést přehled základních principů analytických funkcí s vymezením jejich podstaty a příkladů využití....
  ❌ #19   -5.574  Plánování dopravních potřeb a jejich zajištění ve firmě představují tuto funkcionalitu:   - Plánování  jednotlivých  uka...
  ❌ #20   -8.150  **[2] Podstata plánovacích úloh**   (Funkcionalita a využití plánovacích úloh se zaměřením na výrobu, resp. strojírenstv...

🔀 Reranking grafových dokumentů...
  📊 Reranking [graph] (5 docs → top 10):
  Rank    Score  Preview
  ----------------------------------------------------------------------
  ✅ #1    10.819  Prediktivní analytika v řízení nákupů podporuje prognózování a plánování nákupů materiálů, zboží a služeb pro potřeby fi...
  ✅ #2     8.972  Účelem kapitoly je vymezit základní funkce prediktivní analytiky v rámci plánování v oblasti marketingu, řízení prodeje,...
  ✅ #3     6.857  **Analytické otázky :**   - Jak zvýšit úspěšnost a výkonnost byznysu díky vysoké kvalitě plánovacích úloh při řízení nák...
  ✅ #4     1.989  Oddíl se zaměřil na základní obsah prediktivní analytiky strojírenské firmy ve vazbě na potřeby jejího prognózování a pl...
  ✅ #5    -2.395  Účelem kapitoly je uvést přehled základních principů analytických funkcí s vymezením jejich podstaty a příkladů využití....


🏆 FINÁLNÍ POŘADÍ — VEKTOROVÉ dokumenty předané LLM:
  ----------------------------------------------------------------------
  #1   📂 15. Prediktivní analytika obchodu a logistiky
       💬 Účelem kapitoly je vymezit základní funkce prediktivní analytiky v rámci plánování v oblasti marketingu, řízení prodeje, nákupu a dopravy. Pro každou ...
  #2   📂 19.1 Obsah prediktivní analytiky v operativním plánování výroby | 19. Operativní řízení a plánování výroby
       💬 Prediktivní analytika v operativním řízení výroby zajišťuje tři druhy na sebe se vážících operací (Tomek, Vávrová, 2014):   - operativní plánování pro...
  #3   📂 18.1 Obsah prediktivní analytiky v plánování výrobních zakázek | 18. Prediktivní analytika v řízení výrobních zakázek
       💬 Prediktivní analytika v řízení výrobních zakázek má poskytovat podporu v těchto plánovacích aktivitách:   - plánování výrobních postupů a termínů výro...
  #4   📂 18. Prediktivní analytika v řízení výrobních zakázek
       💬 Účelem kapitoly je vymezit základní funkce prediktivní analytiky v rámci plánování výrobních zakázek, definování cílových proměnných a odpovídajících ...
  #5   📂 18.3 Řešení prediktivní analytiky v plánování výrobních zakázek | 18. Prediktivní analytika v řízení výrobních zakázek
       💬 **Funkce prediktivní analytiky v plánování výrobních zakázek:**   - Clustering: - klastry výrobních zakázek podle zákazníků strojírenské firmy, objemu...
  #6   📂 19. Operativní řízení a plánování výroby
       💬 Účelem kapitoly je vymezit funkcionalitu prediktivní analytiky v rámci operativního řízení a plánování výroby, definovat cílové proměnné a prediktory,...
  #7   📂 17. Prediktivní analytika v řízení investic, údržby a potřeby energií
       💬 Účelem kapitoly je vymezit hlavní funkce prediktivní analytiky v rámci plánování investic, údržby a potřeby energií strojírenské firmy. Na ty standard...
  #8   📂 17.2 Prediktivní analytika v plánování potřeby energií | 17. Prediktivní analytika v řízení investic, údržby a potřeby energií | 17.2.3 Řešení prediktivní analytiky v řízení energií
       💬 **Funkce prediktivní analytiky v plánování potřeby energií:**   - Clustering: - klastry poskytovatelů energií pro strojírenskou firmu podle druhů ener...
  #9   📂 16. Prediktivní analytika v personálním řízení
       💬 Účelem kapitoly je definovat obsah a hlavní funkce prediktivní analytiky v rámci personálního plánování. Na ně navazuje definování cílových proměnných...
  #10  📂 14. Prediktivní analytika ve finančním řízení
       💬 Účelem kapitoly  je  vymezit  funkce  prediktivní  analytiky  v rámci  finančního  plánování  a tvorby rozpočtů. Ta je základem pro definování cílovýc...

🏆 FINÁLNÍ POŘADÍ — GRAFOVÉ dokumenty předané LLM:
  ----------------------------------------------------------------------
  #1   💬 Prediktivní analytika v řízení nákupů podporuje prognózování a plánování nákupů materiálů, zboží a služeb pro potřeby firmy. V oblasti plánování nákup...
  #2   💬 Účelem kapitoly je vymezit základní funkce prediktivní analytiky v rámci plánování v oblasti marketingu, řízení prodeje, nákupu a dopravy. Pro každou ...
  #3   💬 **Analytické otázky :**   - Jak zvýšit úspěšnost a výkonnost byznysu díky vysoké kvalitě plánovacích úloh při řízení nákupů? - Jak co nejpřesněji a vč...
  #4   💬 Oddíl se zaměřil na základní obsah prediktivní analytiky strojírenské firmy ve vazbě na potřeby jejího prognózování a plánování. Předmětem řešení neby...
  #5   💬 Účelem kapitoly je uvést přehled základních principů analytických funkcí s vymezením jejich podstaty a příkladů využití. Ty budou konkretizovány podle...


📤 KONTEXT ODESLANÝ DO LLM (10,478 znaků):
======================================================================
[SEKCE 1 — Grafové dokumenty (preview prvních 800 znaků)]
Prediktivní analytika v řízení nákupů podporuje prognózování a plánování nákupů materiálů, zboží a služeb pro potřeby firmy. V oblasti plánování nákupů má zejména připravovat podklady pro tyto operace:
- sestavení výhledu a plánu nákupu,
- propočet spotřeby materiálu, resp. zboží na dané období,
- bilancování  potřeby  dodávek  materiálu  s  následnými  úpravami  podle  možností  dodavatele, představuje pak vstup do poptávek nebo objednávek,
- sestavení nákupního rozpočtu,
- podklady pro operativní plánování nákupu, které se realizuje ve vazbě na plánování prodeje a plán výroby, resp. plánování výrobních zakázek.
Účelem kapitoly je vymezit základní funkce prediktivní analytiky v rámci plánování v oblasti marketingu, řízení prodeje, nákupu a dopravy. Pro každou s oblastí jsou definován…

[SEKCE 2 — Vektorový text (preview prvních 800 znaků)]
Účelem kapitoly je vymezit základní funkce prediktivní analytiky v rámci plánování v oblasti marketingu, řízení prodeje, nákupu a dopravy. Pro každou s oblastí jsou definovány cílové proměnné a vybrané prediktory. Následně jsou formulovány analytické otázky pro konzultace  analytiků  s obchodními  manažery,  výrobním  manažerem  a  specialisty  firmy  a  následně i funkce a příklady prediktivní analytiky v řízení uvedených oblastí.
Prediktivní analytika v operativním řízení výroby zajišťuje tři druhy na sebe se vážících operací (Tomek, Vávrová, 2014):
- operativní plánování prodeje,
- operativní plánování výroby,
- operativní plánování nákupu.
Prediktivní analytika má poskytovat podporu v těchto plánovacích aktivitách:
- zpracování plánu zadávané výroby,
- výběr a určování přednostníc…

[SEKCE 3 — Vztahy z grafu (preview prvních 800 znaků)]
- Kapitola '15. Prediktivní analytika obchodu a logistiky | 15.3 Prediktivní analytika v plánování nákupu' obsahuje detailní pojem/entitu: 'Doprava'
- Kapitola '15. Prediktivní analytika obchodu a logistiky | 15.3 Prediktivní analytika v plánování nákupu' obsahuje detailní pojem/entitu: 'Řízení Prodeje'
- Kapitola '15. Prediktivní analytika obchodu a logistiky | 15.3 Prediktivní analytika v plánování nákupu' obsahuje detailní pojem/entitu: 'Plánování'
- Kapitola '15. Prediktivní analytika obchodu a logistiky | 15.3 Prediktivní analytika v plánování nákupu' obsahuje detailní pojem/entitu: 'Prediktivní Analytika'
- Kapitola '15. Prediktivní analytika obchodu a logistiky | 15.3 Prediktivní analytika v plánování nákupu' obsahuje detailní pojem/entitu: 'Marketing'
- Kapitola '15. Prediktivní an…
======================================================================
Funkce prediktivní analytiky v plánování nákupu zahrnují:

1.  **Clustering**:
    *   klastry dodavatelů strojírenské firmy podle dodávaných materiálů, nástrojů, přípravků, příslušnosti k dodavatelskému řetězci, podle typů kooperací a poskytovaných služeb,
    *   segmentace dodavatelů podle technickoekonomických charakteristik, spolehlivosti, objemu dodávek v čase,
    *   segmentace obchodních případů Nákup. podle finančního objemu, dodacích podmínek, platebních podmínek.
2.  **Klasifikace**:
    *   klasifikace dodavatelů - jejich rozřazení do stejnorodých tříd a odhad pravděpodobnosti správnosti takového zařazení pro každého dodavatele,
    *   klasifikace dodávaných materiálů - obvykle vychází z oficiální nomenklatury materiálů,
    *   klasifikace poskytovaných a nakupovaných služeb - posouzení správnosti klasifikace uvedením pravděpodobnosti správného členění.
3.  **Přiřazování podobností**:
    *   určování podstatných charakteristik dodavatelů a jejich podobností v rámci definovaných skupin.
4.  **Profilování, ' Popis chování '**:
    *   specifikace klíčových charakteristik dodavatelů z pohledu přístupů k zajištění a řízení obchodních případů 'Nákup'.
5.  **Predikce vazeb**:

In [ ]:
def showGraph():
    driver = GraphDatabase.driver(
        uri=os.environ.get('NEO4J_URI'),
        auth=(os.environ.get('NEO4J_USERNAME'), os.environ.get('NEO4J_PASSWORD'))
    )

    with driver.session() as session:
        query = """
        MATCH (s)-[r]->(t)
        RETURN s, r, t
        """
        graph_data = session.run(query).graph()

    driver.close()

    widget = GraphWidget(graph=graph_data)

    def custom_node_label(node):
        props = node.get("properties", {})
        labels = node.get("labels", [])

        # Uzly Document zobrazí začátek textu místo hash identifikátoru
        if "Document" in labels:
            text = props.get("text", "")
            return text[:40] + "..." if text else "Textový blok"

        # Kapitoly a entity zobrazí své id
        return props.get("id", "Neznámý uzel")

    widget.node_label_mapping = custom_node_label
    return widget

showGraph()

---

##  Část 2 — Evaluace

Evaluace **přímo volá retrievery z pipeline** výše — žádná duplicita kódu, žádný rozdíl v odpovědích.

**Retrievery:**
- `Standard RAG` — pouze vektorové vyhledávání (`vector_retriever`, k=20)
- `Pure Graph RAG` — pouze grafové vyhledávání + reranking
- `Hybrid GraphRAG` — kombinace grafu + vektoru + reranking (= `full_retriever`)

**Metriky:**
- `BERTScore` P/R/F1 — sémantická podobnost s ground truth
- `ROUGE-L` P/R/F1 — lexikální překryv s ground truth
- `RAGAS` Faithfulness, AnswerRelevancy, ContextRecall, AnswerCorrectness (LLM judge: Qwen)

In [ ]:
try:
    from bert_score import score as bert_score
    BERTSCORE_AVAILABLE = True
    print("BERTScore načten.")
except ImportError:
    BERTSCORE_AVAILABLE = False
    print("bert-score není dostupný: pip install bert-score")

try:
    from rouge_score import rouge_scorer
    ROUGE_AVAILABLE = True
    print("ROUGE-L načten.")
except ImportError:
    ROUGE_AVAILABLE = False
    print("rouge-score není dostupný: pip install rouge-score")

try:
    from ragas.metrics import Faithfulness, AnswerRelevancy, AnswerCorrectness, ContextRecall
    from ragas import evaluate as evaluate_ragas
    from ragas.llms import LangchainLLMWrapper
    from ragas.embeddings import LangchainEmbeddingsWrapper
    from ragas.run_config import RunConfig
    from datasets import Dataset
    RAGAS_AVAILABLE = True
    print("RAGAS načten.")
except ImportError:
    RAGAS_AVAILABLE = False
    print("ragas není dostupný: pip install ragas datasets")

# LLM judge pro RAGAS — nezávislý model oddělený od modelu generujícího odpovědi
llm_judge = ChatOllama(model="qwen2.5:7b", temperature=0, num_ctx=16384)

print("Evaluační závislosti načteny.")
print("LLM judge: qwen2.5:7b")

✅ BERTScore loaded
✅ ROUGE-L loaded
✅ RAGAS loaded
✅ Eval imports hotové
   LLM judge (RAGAS): qwen2.5:7b

/var/folders/bq/dvsycyn560sgx_gql985ch9w0000gn/T/ipykernel_5993/1775939859.py:22: DeprecationWarning: Importing Faithfulness from 'ragas.metrics' is deprecated and will be removed in v1.0. Please use 'ragas.metrics.collections' instead. Example: from ragas.metrics.collections import Faithfulness
  from ragas.metrics import Faithfulness, AnswerRelevancy, AnswerCorrectness, ContextRecall
/var/folders/bq/dvsycyn560sgx_gql985ch9w0000gn/T/ipykernel_5993/1775939859.py:22: DeprecationWarning: Importing AnswerRelevancy from 'ragas.metrics' is deprecated and will be removed in v1.0. Please use 'ragas.metrics.collections' instead. Example: from ragas.metrics.collections import AnswerRelevancy
  from ragas.metrics import Faithfulness, AnswerRelevancy, AnswerCorrectness, ContextRecall
/var/folders/bq/dvsycyn560sgx_gql985ch9w0000gn/T/ipykernel_5993/1775939859.py:22: DeprecationWarning: Importing AnswerCorrectness from 'ragas.metrics' is deprecated and will be removed in v1.0. Please use 'ragas.metrics.collections' instead. Example: from ragas.metrics.collections import AnswerCorrectness
  from ragas.metrics import Faithfulness, AnswerRelevancy, AnswerCorrectness, ContextRecall
/var/folders/bq/dvsycyn560sgx_gql985ch9w0000gn/T/ipykernel_5993/1775939859.py:22: DeprecationWarning: Importing ContextRecall from 'ragas.metrics' is deprecated and will be removed in v1.0. Please use 'ragas.metrics.collections' instead. Example: from ragas.metrics.collections import ContextRecall
  from ragas.metrics import Faithfulness, AnswerRelevancy, AnswerCorrectness, ContextRecall

In [ ]:
def naive_rag(question: str) -> str:
    """Baseline — dense retriever s kosinovou podobností, bez rerankingu."""
    docs = dense_retriever.invoke(question)
    return '\n\n'.join(d.page_content for d in docs)


def graph_rag(question: str) -> str:
    """Graph RAG — traversal znalostního grafu s rerankingem."""
    rel, docs = graph_enhanced_retriever(question)
    ranked = rerank_docs(question, docs, top_k=10) if docs else []
    graph_text = '\n\n'.join(ranked)
    return (
        f'### DOKUMENTY Z GRAFU:\n{graph_text[:8000]}'
        f'\n\n### VZTAHY Z GRAFU:\n{rel[:3000]}'
    )


def hybrid_graphrag(question: str) -> str:
    """Hybrid GraphRAG — kombinace traversalu znalostního grafu a hybridního retrieveru."""
    return full_retriever(question)


SCENARE = {
    'Naive RAG':       naive_rag,
    'Graph RAG':       graph_rag,
    'Hybrid GraphRAG': hybrid_graphrag,
}

print("Evaluační scénáře připraveny:")
print("  Naive RAG       — dense retriever, bez rerankingu (baseline)")
print("  Graph RAG       — KG traversal s rerankingem")
print("  Hybrid GraphRAG — KG traversal + hybridní retriever s rerankingem")

✅ Evaluační retrievery připraveny
   Scénáře: ['Naive RAG', 'Graph RAG', 'Hybrid GraphRAG']

Naive RAG       — Dense only, BEZ rerankingu  → baseline (Lewis 2020)
Graph RAG       — KG Retriever + reranking    → přínos grafu
Hybrid GraphRAG — KG + Hybrid + reranking     → hlavní systém

### 📋 Testovací sady

Každá sada je seznam dvojic `(otázka, ground_truth)`.
Pro nový dokument přidej `sada_nazev = [...]`.

In [ ]:
sada_planovani_pa = [
 
    # ── VÝČTOVÉ (3) ────────────────────────────────────────────────────────────
 
    (
        'Jaké jsou funkce prediktivní analytiky v plánování nákupu?',
        '- Clustering: klastry dodavatelů podle dodávaných materiálů, nástrojů, přípravků, '
        'příslušnosti k dodavatelskému řetězci; segmentace dodavatelů podle technickoekonomických '
        'charakteristik a spolehlivosti\n'
        '- Klasifikace: klasifikace dodavatelů do stejnorodých tříd; klasifikace dodávaných '
        'materiálů; klasifikace nakupovaných služeb\n'
        '- Přiřazování podobností: určování podstatných charakteristik dodavatelů a jejich '
        'podobností v rámci definovaných skupin\n'
        '- Profilování: specifikace klíčových charakteristik dodavatelů z pohledu přístupů '
        'k řízení obchodních případů Nákup\n'
        '- Predikce vazeb: vyhodnocování vazeb kvality a včasnosti dodávek materiálů vzhledem '
        'k velikosti a ekonomické síle dodavatelské firmy\n'
        '- Náhodné modelování: hodnocení kvality dodávek jednotlivých dodavatelů vzhledem '
        'k jejich podstatným charakteristikám'
    ),
 
    (
        'Jake jsou dimenze v řešení úloh analytiky přípravy a plánování výrobních zakázek?',
        'Čas - časová dimenze určující dobu poptávky, zahájení, dílčích etap, ukončení výrobní zakázky\n'
        'Regiony - struktura regionů pro specifikaci a realizaci výrobních zakázek\n'
        'Podnikové útvary - sledování a plánování nároků na zdroje podle útvarů firmy\n'
        'Měny - struktura využívaných měn včetně kurzů\n'
        'Nákladové druhy - standardní struktura nákladů v souvislosti s přípravou výrobních zakázek\n'
        'Účetní osnova - struktura účtů pro analýzy nákladů na výrobní zakázky\n'
        'Dodavatelé - dodavatelé materiálů, sestav, přípravků a kooperací\n'
        'Lidské zdroje a mzdy - zaměstnanci, kvalifikační struktura, mzdové složky\n'
        'Sklady - struktura vlastních a pronajatých skladů včetně mezioperačních\n'
        'Materiály - vstupní materiály předmětem normování\n'
        'Materiálové normy, Technologické postupy, Výkonové normy\n'
        'Výrobky - výrobky, polotovary, sestavy předmětem technické přípravy výroby\n'
        'Výrobní střediska - struktura středisek a jejich kapacity\n'
        'Výrobní zakázky - struktura druhů výrobních zakázek'
    ),
 
    (
        'Jake jsou hlavní plánovací dimenze podle jednotlivých skupin?',
        'Základní dimenze: Časová dimenze, Regiony, Odvětví ekonomiky, Měrné jednotky\n'
        'Podniková organizace: Cíle firmy, Podnikové procesy, Činnosti, Podnikové útvary, '
        'Podniková aktiva, Vnitropodnikové zakázky\n'
        'Ekonomické dimenze: Účtová osnova, Účetní období, Kapitálová struktura, Měny, '
        'Nákladové druhy, Druhy cen\n'
        'Externí partneři: Zákazníci, Dodavatelé, Veřejná správa, Finanční ústavy\n'
        'Lidské zdroje a mzdy: Zaměstnanci, Kvalifikační struktura, Věková struktura, '
        'Vzdělávání, Typy školení, Mzdové složky\n'
        'Obchodní dimenze: Zboží, Materiály, Služby, Segmenty trhu, Obchodní kanály\n'
        'Dimenze skladového hospodářství: Sklady, Skladová místa\n'
        'Dimenze majetku: Druhy majetku, Investice, Opravy / údržba\n'
        'Dimenze interní dopravy: Poskytovatelé dopravy, Dopravní prostředky, PHM\n'
        'Dimenze hospodaření s energiemi: Druhy energií, Dodavatelé energií\n'
        'IT služby a zdroje: IT služby, Dodavatelé IT, Aplikace, IT projekty\n'
        'Dimenze řízení výroby: Výrobní zakázky, Výrobky, Výrobní střediska, Výrobní dávky'
    ),
 
    # ── DEFINICE / ÚČEL (3) ────────────────────────────────────────────────────
 
    (
        'Jaké jsou základní cíle plánovacích úloh?',
        '- Vytvořit a využít plánovací systém respektující plánovací metody\n'
        '- Zajistit konsolidaci plánů z různých organizačních jednotek\n'
        '- Zajistit konsolidaci hodnot z různých druhů plánů do výsledného finančního plánu\n'
        '- Zajistit konsolidaci plánů z pohledu různých měn\n'
        '- Automatizovat řízení pracovního toku při přípravě plánu\n'
        '- Efektivně zpřístupňovat sestavené plány zainteresovaným pracovníkům'
    ),
    
    (
        'Jaké plánovací nástroje jsou popsány v dokumentu?',
        'Oracle Enterprise Performance Management, '
        'IBM Planning Analytics, '
        'Anaplan, '
        'Workday, '
        'SAP Analytics Cloud'
    ),
 
    (
        'Jaké jsou cílové proměnné strategického řízení?',
        'Hospodářský výsledek, '
        'Počet plánovaných inovací výroby výrobků a služeb, '
        'Objem nákladů firmy, '
        'MVA (Market Value Added), '
        'EVA (Economic Value Added), '
        'EBITDA, '
        'Počet zákazníků firmy, '
        'Průběžná doba výroby, '
        'Produktivita práce, '
        'Tržní podíl'
    ),
 
    # ── VZTAHOVÉ — vstupy/výstupy a vazby mezi oblastmi (3) ───────────────────
 
    (
        'Jaké analytické otázky řeší plánování prodeje?',
        '- Jak zvýšit úspěšnost a výkonnost byznysu díky vysoké kvalitě plánovacích úloh?\n'
        '- Jak co nejpřesněji a včas zjišťovat budoucí předpokládané obchodní příležitosti?\n'
        '- Jak systematicky sledovat a regulovat stav zásob pro prodejní zakázky?\n'
        '- Jak zajistit dostupnost informací o stavu a předpokládaném vývoji trhu?\n'
        '- Jak správně a racionálně aplikovat plánovací metodiky firmy?\n'
        '- Jak průběžně analyzovat odchylky od vytvořeného plánu prodeje?\n'
        '- Jak nastavit různé možnosti alokace plánovaných hodnot prodejů na útvary?'
    ),
 
    (
        'Jaké jsou dimenze v řešení úloh finančního plánování?',
        'Čas - časová dimenze plánovací horizonty finančních ukazatelů\n'
        'Podnikové procesy - plánování finančních objemů pro zajištění procesů firmy\n'
        'Podnikové útvary - plánování ekonomických charakteristik podle útvarů\n'
        'Střediska - hospodářská, nákladová a zisková střediska\n'
        'Finanční ústavy - řízení pohybů na účtech\n'
        'Měny - struktura využívaných měn a kurzy\n'
        'Nákladové druhy - standardní struktura pro plánování nákladů\n'
        'Účetní období - nepřetržitě po sobě jdoucích dvanáct měsíců\n'
        'Účetní osnova - struktura účtů hlavní knihy a analytického účetnictví\n'
        'Dodavatelé - plánování dodávek podle dodavatelů\n'
        'Zákazníci firmy - plánovaný finanční objem zakázek\n'
        'Zaměstnanci - plánování časových kapacit a utilizace\n'
        'Platební podmínky - způsoby a termíny plateb\n'
        'Obchodní kanály - různé způsoby prodeje'
    ),
 
    (
        'Vyjmenuj analytické otázky ve strategickém plánování.',
        'Navazují roční plány na dlouhodobou strategii a záměry firmy?\n'
        'Jsou všechny vstupy a výstupy jednoznačně oceněny a jsou stanoveny možné výkyvy '
        'v průběhu roku?\n'
        'Jsou stanoveny principy a postupy pro tvorbu strategických plánů?\n'
        'Jsou stanoveny seznamy aktuálně sledovaných klíčových metrik z jednotlivých procesů?\n'
        'Obsahuje plán rezervu na možná rizika?\n'
        'Využívá firma v oblasti strategického řízení metody a nástroje prediktivní analytiky?'
    ),
 
    # ── FAKTICKÉ — jednoduché definice (3) ────────────────────────────────────
 
    (
        'Co jsou osy P-F křivky?',
        'Osa X znázorňuje čas. '
        'Osa Y (svislá) představuje stav zařízení.'
    ),
 
    (
        'Jaké skupiny metrik zahrnuje strategické plánování strojírenské firmy?',
        '- Finanční strategie\n'
        '- Obchodní strategie, strategie cenotvorby, strategie distribuce produktů\n'
        '- Personální strategie a strategie interní i externí komunikace\n'
        '- Marketing a marketingový výzkum\n'
        '- Majetkové a investiční strategie\n'
        '- Informační strategie'
    ),
 
    (
        'Jaké jsou funkce prediktivní analytiky v marketingu?',
        '- Clustering: klastry zákazníků strojírenské firmy podle typu výroby, příslušnosti '
        'k dodavatelskému řetězci, dislokace závodů\n'
        '- Klasifikace: klasifikace zákazníků — rozřazení do stejnorodých tříd\n'
        '- Přiřazování podobností: určování podstatných charakteristik zákazníků a výběr '
        'firem podobných nejlepším zákazníkům\n'
        '- Profilování: specifikace klíčových charakteristik zákazníků z pohledu přístupů '
        'k řízení obchodních případů Prodej\n'
        '- Predikce vazeb: vyhodnocování vazeb marketingových aktivit k dosahovaným '
        'obchodním výsledkům\n'
        '- Náhodné modelování: vyhodnocení kvality promo akcí a vývoj tržeb u vybraných '
        'výrobků a služeb'
    ),
 
]
 
print(f'Celkem otázek: {len(sada_planovani_pa)}')

Celkem otázek: 12

In [ ]:
import threading
import inspect

LLM_TIMEOUT = 180


def compute_bertscore(predictions, references):
    """Vrátí (Precision, Recall, F1) listy pro BERTScore."""
    if not BERTSCORE_AVAILABLE:
        none = [None] * len(predictions)
        return none, none, none
    P, R, F1 = bert_score(
        predictions, references,
        model_type='bert-base-multilingual-cased', lang='cs',
        verbose=False
    )
    return P.tolist(), R.tolist(), F1.tolist()


def compute_rouge(predictions, references):
    """Vrátí (Precision, Recall, F1) listy pro ROUGE-L."""
    if not ROUGE_AVAILABLE:
        none = [None] * len(predictions)
        return none, none, none
    scorer = rouge_scorer.RougeScorer(['rougeL'], use_stemmer=False)
    P, R, F1 = [], [], []
    for pred, ref in zip(predictions, references):
        s = scorer.score(ref, pred)['rougeL']
        P.append(s.precision); R.append(s.recall); F1.append(s.fmeasure)
    return P, R, F1


def call_with_timeout(retriever, llm, question, timeout=LLM_TIMEOUT):
    """Zavolá retriever a LLM s timeoutem. Vrátí (answer, context, elapsed_s)."""
    result = {}

    # Prompt identický s pipeline — zajišťuje konzistenci mezi evaluací a produkcí
    EVAL_PROMPT = """
Jsi expertní analytický systém pracující s technickou dokumentací.

### KRITICKÁ PRAVIDLA:
1. ODPOVÍDEJ POUZE NA ZÁKLADĚ DODANÉHO KONTEXTU.
2. Pro výčty použij odrážkový seznam, pro definice odstavce.
3. KOMPLETNÍ VÝČET BEZ ZKRACOVÁNÍ — žádné "a další", "apod.", "atd.".

### KONTEXT:
{context}

### OTÁZKA:
{question}

### ODPOVĚĎ:"""

    def worker():
        try:
            context = retriever(question)
            prompt  = EVAL_PROMPT.format(context=context, question=question)
            answer  = llm_rag.invoke(prompt).content
            result['ok'] = (answer, context)
        except Exception as e:
            result['error'] = str(e)

    t  = threading.Thread(target=worker)
    t0 = time.time()
    t.start()
    t.join(timeout=timeout)
    elapsed = round(time.time() - t0, 1)

    if t.is_alive():
        return None, None, elapsed
    if 'error' in result:
        return f"ERROR: {result['error']}", '', elapsed
    answer, context = result['ok']
    return answer, context, elapsed


def evaluate(sada, document_name=None, timeout=LLM_TIMEOUT, mode='combined'):
    """
    Spustí evaluaci pro danou testovací sadu.

    Retrievery jsou volány přímo z pipeline — bez duplicity kódu,
    chování je identické se Streamlit aplikací.

    Parametry
    ----------
    sada          : list of (question, ground_truth)
    document_name : str, volitelný — název pro výstupní CSV
    timeout       : int, sekundy na jedno LLM volání (výchozí 180)
    mode          : 'combined' | 'reference' | 'ragas'
        'combined'   — BERTScore + ROUGE-L + RAGAS (výchozí)
        'reference'  — pouze BERTScore + ROUGE-L, bez LLM judge
        'ragas'      — pouze RAGAS
    """
    if not sada:
        print('Testovací sada je prázdná.')
        return None

    if document_name is None:
        frame = inspect.currentframe().f_back
        document_name = next(
            (k for k, v in frame.f_locals.items() if v is sada), 'document'
        ).replace('sada_', '')

    print(f'Evaluace: {document_name}')
    print(f'Otázky: {len(sada)} | Metody: {len(SCENARE)} | '
          f'LLM volání celkem: {len(sada) * len(SCENARE)}')
    print(f'Timeout: {timeout}s | Mode: {mode}\n')

    rows     = []
    out_file = f'../evaluation/evaluation_{document_name}.csv'

    for i, (question, ground_truth) in enumerate(sada, 1):
        print(f'[{i}/{len(sada)}] {question}')
        for method_name, retriever in SCENARE.items():
            print(f'  {method_name}...', end=' ', flush=True)

            answer, context, elapsed = call_with_timeout(retriever, llm_rag, question, timeout)

            if answer is None:
                print(f'Timeout ({elapsed}s), přeskočeno.')
                answer = 'TIMEOUT'; context = ''
            else:
                print(f'{elapsed}s')
                print(f'    {answer[:120].replace(chr(10), " ")}...')

            if answer != 'TIMEOUT' and mode in ('combined', 'reference'):
                bp, br, bf1 = compute_bertscore([answer], [ground_truth])
                rp, rr, rf1 = compute_rouge([answer], [ground_truth])
                bert_p, bert_r, bert_f1 = bp[0], br[0], bf1[0]
                rouge_p, rouge_r, rouge_f1 = rp[0], rr[0], rf1[0]
                print(f'    BERT F1: {round(bert_f1, 3)} | '
                      f'ROUGE-L R: {round(rouge_r, 3)} | '
                      f'ROUGE-L F1: {round(rouge_f1, 3)}')
            else:
                bert_p = bert_r = bert_f1 = None
                rouge_p = rouge_r = rouge_f1 = None

            rows.append({
                'document':     document_name,
                'method':       method_name,
                'question':     question,
                'answer':       answer,
                'context':      context,
                'time_s':       elapsed,
                'ground_truth': ground_truth,
                'BERTScore_P':  bert_p,
                'BERTScore_R':  bert_r,
                'BERTScore_F1': bert_f1,
                'ROUGE_L_P':    rouge_p,
                'ROUGE_L_R':    rouge_r,
                'ROUGE_L_F1':   rouge_f1,
            })

        # Průběžné ukládání po každé otázce
        existing = pd.read_csv(out_file) if os.path.exists(out_file) else pd.DataFrame()
        pd.concat([existing, pd.DataFrame(rows)]).drop_duplicates(
            subset=['method', 'question'], keep='last'
        ).to_csv(out_file, index=False, encoding='utf-8-sig')
        print(f'  Uloženo: {out_file}\n')

    df = pd.DataFrame(rows)

    print('\n' + '=' * 60)
    print('Vygenerované odpovědi')
    print('=' * 60)
    for _, r in df.iterrows():
        print(f'\n[{r["method"]}] {r["question"]}')
        print('-' * 40)
        print(r['answer'])

    df_valid = df[df['answer'] != 'TIMEOUT'].copy()
    if df_valid.empty:
        print('Žádné platné výsledky — všechna volání překročila timeout.')
        return df

    if mode in ('combined', 'ragas') and RAGAS_AVAILABLE:
        print('\nRAGAS evaluace...')
        ragas_llm = LangchainLLMWrapper(llm_judge)
        ragas_emb = LangchainEmbeddingsWrapper(embeddings)

        dataset = Dataset.from_dict({
            'user_input':         df_valid['question'].tolist(),
            'response':           df_valid['answer'].tolist(),
            'retrieved_contexts': [[k] for k in df_valid['context'].tolist()],
            'reference':          df_valid['ground_truth'].tolist(),
        })
        ragas_result = evaluate_ragas(
            dataset=dataset,
            metrics=[Faithfulness(), AnswerRelevancy(), ContextRecall(), AnswerCorrectness()],
            llm=ragas_llm, embeddings=ragas_emb,
            run_config=RunConfig(timeout=300, max_workers=1)
        )
        df_ragas   = ragas_result.to_pandas()
        wanted     = ['faithfulness', 'answer_relevancy', 'context_recall', 'answer_correctness']
        available  = [c for c in wanted if c in df_ragas.columns]
        ragas_cols = df_ragas[available].reset_index(drop=True)
    else:
        ragas_cols = pd.DataFrame({
            'faithfulness':       [None] * len(df_valid),
            'answer_relevancy':   [None] * len(df_valid),
            'context_recall':     [None] * len(df_valid),
            'answer_correctness': [None] * len(df_valid),
        })

    ref_cols = ['BERTScore_P', 'BERTScore_R', 'BERTScore_F1',
                'ROUGE_L_P', 'ROUGE_L_R', 'ROUGE_L_F1']
    df_out = pd.concat([
        df_valid[['document', 'method', 'question', 'answer', 'context',
                  'time_s', 'ground_truth'] + ref_cols].reset_index(drop=True),
        ragas_cols
    ], axis=1)

    metrics_cols = [c for c in ref_cols + ['faithfulness', 'answer_relevancy',
                    'context_recall', 'answer_correctness'] if c in df_out.columns]

    print(f'\nVýsledky per otázka — {document_name}')
    display(df_out[['method', 'question'] + metrics_cols].round(3))

    print(f'\nPrůměrné skóre — {document_name}')
    display(df_out.groupby('method')[metrics_cols].mean().round(3))

    if 'ROUGE_L_R' in df_out.columns and df_out['ROUGE_L_R'].notna().any():
        best_rouge = df_out.groupby('method')['ROUGE_L_R'].mean().idxmax()
        print(f'\nNejlepší ROUGE-L Recall (úplnost):    {best_rouge}')
    if 'BERTScore_F1' in df_out.columns and df_out['BERTScore_F1'].notna().any():
        best_bert = df_out.groupby('method')['BERTScore_F1'].mean().idxmax()
        print(f'Nejlepší BERTScore F1 (sémantika):     {best_bert}')
    if 'answer_correctness' in df_out.columns and df_out['answer_correctness'].notna().any():
        best_ac = df_out.groupby('method')['answer_correctness'].mean().idxmax()
        print(f'Nejlepší Answer Correctness (RAGAS):   {best_ac}')

    existing = pd.read_csv(out_file) if os.path.exists(out_file) else pd.DataFrame()
    pd.concat([existing, df_out]).drop_duplicates(
        subset=['method', 'question'], keep='last'
    ).to_csv(out_file, index=False, encoding='utf-8-sig')
    print(f'\nVýsledky uloženy: {out_file}')
    return df_out


print('evaluate() připravena.')
print('  evaluate(sada_planovani_pa)                     # combined')
print('  evaluate(sada_planovani_pa, mode="reference")   # bez RAGAS')
print('  evaluate(sada_planovani_pa, mode="ragas")       # pouze RAGAS')
print('  evaluate(sada_planovani_pa[:1])                 # jedna otázka')

✅ evaluate() připravena

Použití:
  evaluate(sada_strojirenska_firma)                            # combined
  evaluate(sada_strojirenska_firma, mode="reference")          # bez RAGAS
  evaluate(sada_strojirenska_firma, mode="ragas")              # pouze RAGAS
  evaluate(sada_strojirenska_firma[:1], document_name="q1")    # 1 otázka

###  Spuštění evaluace

In [ ]:
evaluate(
    sada_planovani_pa, 
    document_name='planovani_pa',
    mode='combined',
    timeout=60
)

🚀 Evaluating: planovani_pa
   Otázky: 12 | Metody: 3 | Celkem LLM volání: 36
   Timeout: 60s | Mode: combined

[1/12] Jaké jsou funkce prediktivní analytiky v plánování nákupu?
  ⏳ Naive RAG... ✅ 18.6s
    → Funkce prediktivní analytiky v plánování nákupu zahrnují:  - Clustering: skupina dodavatelů podle kritérií jako je cena,...
    BERT F1: 0.735 | ROUGE-L R: 0.217 | ROUGE-L F1: 0.189
  ⏳ Graph RAG... 🔍 Nalezené entity pro graf: ['funkce prediktivní analytiky v plánování nákupu']
🎯 Přímý fulltext dotaz do grafu: *jaké* OR *jsou* OR *funkc* OR *predi* OR *analy* OR *pláno* OR *nákup*
  🎯 ZÁCHYT V GRAFU: Nalezen uzel [Kapitola] s názvem '15. Prediktivní analytika obchodu a logistiky | 15.3 Prediktivní analytika v plánování nákupu'
  🎯 ZÁCHYT V GRAFU: Nalezen uzel [Kapitola] s názvem '15. Prediktivní analytika obchodu a logistiky | 15.3 Prediktivní analytika v plánování nákupu | 15.3.3 Řešení prediktivní analytiky v řízení nákupu'
  🎯 ZÁCHYT V GRAFU: Nalezen uzel [Kapitola] s názvem '15. Prediktivní analytika obchodu a logistiky | 15.3 Prediktivní analytika v plánování nákupu | 15.3.1 Obsah prediktivní analytiky v řízeni nákupu'
  🎯 ZÁCHYT V GRAFU: Nalezen uzel [Kapitola] s názvem '12. Principy a funkce uplatňované v prediktivní analytice'
  🎯 ZÁCHYT V GRAFU: Nalezen uzel [Kapitola] s názvem 'Závěry k oddílu C: Plánování a prediktivní analytika'
✅ CELKEM z grafu: 5 unikátních dokumentů
  📊 Reranking (5 docs → top 10):
  Rank    Score  Preview
  ----------------------------------------------------------------------
  ✅ #1    10.819  Prediktivní analytika v řízení nákupů podporuje prognózování a plánování nákupů materiálů, zboží a služeb pro potřeby fi...
  ✅ #2     8.972  Účelem kapitoly je vymezit základní funkce prediktivní analytiky v rámci plánování v oblasti marketingu, řízení prodeje,...
  ✅ #3     6.857  **Analytické otázky :**   - Jak zvýšit úspěšnost a výkonnost byznysu díky vysoké kvalitě plánovacích úloh při řízení nák...
  ✅ #4     1.989  Oddíl se zaměřil na základní obsah prediktivní analytiky strojírenské firmy ve vazbě na potřeby jejího prognózování a pl...
  ✅ #5    -2.395  Účelem kapitoly je uvést přehled základních principů analytických funkcí s vymezením jejich podstaty a příkladů využití....

✅ 20.3s
    → Funkce prediktivní analytiky v plánování nákupu zahrnují:  1.  **Clustering**:      *   klastry dodavatelů strojírenské ...
    BERT F1: 0.795 | ROUGE-L R: 0.984 | ROUGE-L F1: 0.692
  ⏳ Hybrid GraphRAG...
--- HLEDÁM ODPOVĚĎ NA: 'Jaké jsou funkce prediktivní analytiky v plánování nákupu?' ---

📚 VEKTOROVÉ VYHLEDÁVÁNÍ — nalezeno 20 dokumentů (před rerankingem):
------------------------------------------------------------
  [1] 📂 19. Operativní řízení a plánování výroby
       💬 Účelem kapitoly je vymezit funkcionalitu prediktivní analytiky v rámci operativního řízení a plánování výroby, definovat cílové proměnné a prediktory, formulovat analytické otázky pro konzultace analy...
  [2] 📂 15. Prediktivní analytika obchodu a logistiky
       💬 Účelem kapitoly je vymezit základní funkce prediktivní analytiky v rámci plánování v oblasti marketingu, řízení prodeje, nákupu a dopravy. Pro každou s oblastí jsou definovány cílové proměnné a vybran...
  [3] 📂 14. Prediktivní analytika ve finančním řízení
       💬 Účelem kapitoly  je  vymezit  funkce  prediktivní  analytiky  v rámci  finančního  plánování  a tvorby rozpočtů. Ta je základem pro definování cílových proměnných a jim odpovídajících prediktorů. V rá...
  [4] 📂 16. Prediktivní analytika v personálním řízení
       💬 Účelem kapitoly je definovat obsah a hlavní funkce prediktivní analytiky v rámci personálního plánování. Na ně navazuje definování cílových proměnných v personálním řízení a podstatné prediktory. Násl...
  [5] 📂 18. Prediktivní analytika v řízení výrobních zakázek
       💬 Účelem kapitoly je vymezit základní funkce prediktivní analytiky v rámci plánování výrobních zakázek, definování cílových proměnných a odpovídajících prediktorů. Jsou zde specifikovány  analytické  ot...
  [6] 📂 12.1 Hlavní principy prediktivní analytiky | 12. Principy a funkce uplatňované v prediktivní analytice
       💬 Obsah plánování a prediktivní analytiky je velmi variantní podle odvětví, typu a zaměření firem a jeho zvládnutí je pro analytiky hodně náročné. Z pohledu řízení firmy je ale samotným základem pro pre...
  [7] 📂 17. Prediktivní analytika v řízení investic, údržby a potřeby energií
       💬 Účelem kapitoly je vymezit hlavní funkce prediktivní analytiky v rámci plánování investic, údržby a potřeby energií strojírenské firmy. Na ty standardně navazuje definování cílových proměnných a predi...
  [8] 📂 12.3 Závěry | 12. Principy a funkce uplatňované v prediktivní analytice
       💬 Uvedené dílčí funkce, které jsou spojeny s prediktivní analytikou můžeme pracovně pokládat za jednotlivé stavební kameny jejích řešení. Váží se k nim následující poznámky:   - Základní vymezení funkcí...
  [9] 📂 18.3 Řešení prediktivní analytiky v plánování výrobních zakázek | 18. Prediktivní analytika v řízení výrobních zakázek
       💬 **Funkce prediktivní analytiky v plánování výrobních zakázek:**   - Clustering: - klastry výrobních zakázek podle zákazníků strojírenské firmy, objemu zakázek, plánovaných termínů dokončení. o   - Kla...
  [10] 📂 C. Prediktivní analytika firmy podle oblastí řízení
       💬 | [12] Principy a funkce prediktivní analytiky      | [12] Principy a funkce prediktivní analytiky           | |---------------------------------------------------|------------------------------------...
  [11] 📂 7.6 Plánování dopravy | 7. Plánování obchodu a logistiky
       💬 Plánování dopravních potřeb a jejich zajištění ve firmě představují tuto funkcionalitu:   - Plánování  jednotlivých  ukazatelů  řízení  dopravy ,  např.  nákladů  na  dopravu,  výkonu  dopravy, využit...
  [12] 📂 17.2 Prediktivní analytika v plánování potřeby energií | 17. Prediktivní analytika v řízení investic, údržby a potřeby energií | 17.2.3 Řešení prediktivní analytiky v řízení energií
       💬 **Funkce prediktivní analytiky v plánování potřeby energií:**   - Clustering: - klastry poskytovatelů energií pro strojírenskou firmu podle druhů energií, objemu dodávek. o   - Klasifikace :   - klasi...
  [13] 📂 A. Principy a podstata plánovacích úloh v řízení firmy
       💬 **[2] Podstata plánovacích úloh**   (Funkcionalita a využití plánovacích úloh se zaměřením na výrobu, resp. strojírenství.)   **[3] Principy a řešení plánovacích úloh v BI**   (Principy změn v analyti...
  [14] 📂 19.1 Obsah prediktivní analytiky v operativním plánování výroby | 19. Operativní řízení a plánování výroby
       💬 Prediktivní analytika v operativním řízení výroby zajišťuje tři druhy na sebe se vážících operací (Tomek, Vávrová, 2014):   - operativní plánování prodeje, - operativní plánování výroby, - operativní ...
  [15] 📂 21. Závěr
       💬 Text tvoří jeden z textů řady III úrovně portálu https://mbi-af.cz v tomto případě zaměřený na plánování a prediktivní analytiku strojírenských firem. Jeho cílem bylo prezentovat celkový pohled na plá...
  [16] 📂 1. Úvodní poznámky a souvislosti
       💬 Strategické Fizeni   Plánování a plánovací úlohy představují jednu ze základních a velmi významných komponent řízení firmy . Mají specifickou funkcionalitu, specifické určení i specifické technologie ...
  [17] 📂 13.3 Řešení prediktivní analytiky ve strategickém řízení | 13. Strategické řízení
       💬 **Příklady prediktivní analytiky:**   - Určování cílových hodnot, např. EBITDA (Earnings Before Interest, Taxes, Depreciation and Amortization) podle Objemu výrobních zakázek. - Klasifikace vlastních ...
  [18] 📂 18.1 Obsah prediktivní analytiky v plánování výrobních zakázek | 18. Prediktivní analytika v řízení výrobních zakázek
       💬 Prediktivní analytika v řízení výrobních zakázek má poskytovat podporu v těchto plánovacích aktivitách:   - plánování výrobních postupů a termínů výroby, - určení konkrétních strojů a zařízení pro dan...
  [19] 📂 12. Principy a funkce uplatňované v prediktivní analytice
       💬 Účelem kapitoly je uvést přehled základních principů analytických funkcí s vymezením jejich podstaty a příkladů využití. Ty budou konkretizovány podle oblastí řízení strojírenské firmy. Jde zde zejmén...
  [20] 📂 17.2 Prediktivní analytika v plánování potřeby energií | 17. Prediktivní analytika v řízení investic, údržby a potřeby energií | 17.2.1 Obsah prediktivní analytiky v plánování potřeby energií
       💬 Prediktivní analytika v řízení energií má poskytovat podporu v těchto plánovacích aktivitách:   - zpracování plánů řízení spotřeby energií - hodnocení požadavků na energie podle různých hledisek (dime...
------------------------------------------------------------
🔍 Nalezené entity pro graf: ['funkce prediktivní analytiky v plánování nákupu']
🎯 Přímý fulltext dotaz do grafu: *jaké* OR *jsou* OR *funkc* OR *predi* OR *analy* OR *pláno* OR *nákup*
  🎯 ZÁCHYT V GRAFU: Nalezen uzel [Kapitola] s názvem '15. Prediktivní analytika obchodu a logistiky | 15.3 Prediktivní analytika v plánování nákupu'
  🎯 ZÁCHYT V GRAFU: Nalezen uzel [Kapitola] s názvem '15. Prediktivní analytika obchodu a logistiky | 15.3 Prediktivní analytika v plánování nákupu | 15.3.3 Řešení prediktivní analytiky v řízení nákupu'
  🎯 ZÁCHYT V GRAFU: Nalezen uzel [Kapitola] s názvem '15. Prediktivní analytika obchodu a logistiky | 15.3 Prediktivní analytika v plánování nákupu | 15.3.1 Obsah prediktivní analytiky v řízeni nákupu'
  🎯 ZÁCHYT V GRAFU: Nalezen uzel [Kapitola] s názvem '12. Principy a funkce uplatňované v prediktivní analytice'
  🎯 ZÁCHYT V GRAFU: Nalezen uzel [Kapitola] s názvem 'Závěry k oddílu C: Plánování a prediktivní analytika'
✅ CELKEM z grafu: 5 unikátních dokumentů

🕸️  GRAFOVÉ VYHLEDÁVÁNÍ — nalezeno 5 dokumentů (před rerankingem):
------------------------------------------------------------
  [1] 💬 Účelem kapitoly je vymezit základní funkce prediktivní analytiky v rámci plánování v oblasti marketingu, řízení prodeje, nákupu a dopravy. Pro každou s oblastí jsou definovány cílové proměnné a vybran...
  [2] 💬 **Analytické otázky :**   - Jak zvýšit úspěšnost a výkonnost byznysu díky vysoké kvalitě plánovacích úloh při řízení nákupů? - Jak co nejpřesněji a včas zjišťovat budoucí předpokládané potřeby zboží a...
  [3] 💬 Prediktivní analytika v řízení nákupů podporuje prognózování a plánování nákupů materiálů, zboží a služeb pro potřeby firmy. V oblasti plánování nákupů má zejména připravovat podklady pro tyto operace...
  [4] 💬 Účelem kapitoly je uvést přehled základních principů analytických funkcí s vymezením jejich podstaty a příkladů využití. Ty budou konkretizovány podle oblastí řízení strojírenské firmy. Jde zde zejmén...
  [5] 💬 Oddíl se zaměřil na základní obsah prediktivní analytiky strojírenské firmy ve vazbě na potřeby jejího prognózování a plánování. Předmětem řešení nebyly ani v tomto případě jednotlivé nástroje a jejic...
------------------------------------------------------------

🔀 Reranking vektorových dokumentů...
  📊 Reranking [vector] (20 docs → top 10):
  Rank    Score  Preview
  ----------------------------------------------------------------------
  ✅ #1     8.972  Účelem kapitoly je vymezit základní funkce prediktivní analytiky v rámci plánování v oblasti marketingu, řízení prodeje,...
  ✅ #2     8.471  Prediktivní analytika v operativním řízení výroby zajišťuje tři druhy na sebe se vážících operací (Tomek, Vávrová, 2014)...
  ✅ #3     7.278  Prediktivní analytika v řízení výrobních zakázek má poskytovat podporu v těchto plánovacích aktivitách:   - plánování vý...
  ✅ #4     5.865  Účelem kapitoly je vymezit základní funkce prediktivní analytiky v rámci plánování výrobních zakázek, definování cílovýc...
  ✅ #5     4.956  **Funkce prediktivní analytiky v plánování výrobních zakázek:**   - Clustering: - klastry výrobních zakázek podle zákazn...
  ✅ #6     4.868  Účelem kapitoly je vymezit funkcionalitu prediktivní analytiky v rámci operativního řízení a plánování výroby, definovat...
  ✅ #7     4.864  Účelem kapitoly je vymezit hlavní funkce prediktivní analytiky v rámci plánování investic, údržby a potřeby energií stro...
  ✅ #8     4.551  **Funkce prediktivní analytiky v plánování potřeby energií:**   - Clustering: - klastry poskytovatelů energií pro strojí...
  ✅ #9     4.404  Účelem kapitoly je definovat obsah a hlavní funkce prediktivní analytiky v rámci personálního plánování. Na ně navazuje ...
  ✅ #10    4.379  Účelem kapitoly  je  vymezit  funkce  prediktivní  analytiky  v rámci  finančního  plánování  a tvorby rozpočtů. Ta je z...
  ❌ #11    3.757  | [12] Principy a funkce prediktivní analytiky      | [12] Principy a funkce prediktivní analytiky           | |--------...
  ❌ #12    3.707  Obsah plánování a prediktivní analytiky je velmi variantní podle odvětví, typu a zaměření firem a jeho zvládnutí je pro ...
  ❌ #13    3.601  Prediktivní analytika v řízení energií má poskytovat podporu v těchto plánovacích aktivitách:   - zpracování plánů řízen...
  ❌ #14    2.182  **Příklady prediktivní analytiky:**   - Určování cílových hodnot, např. EBITDA (Earnings Before Interest, Taxes, Depreci...
  ❌ #15    1.994  Strategické Fizeni   Plánování a plánovací úlohy představují jednu ze základních a velmi významných komponent řízení fir...
  ❌ #16    1.775  Text tvoří jeden z textů řady III úrovně portálu https://mbi-af.cz v tomto případě zaměřený na plánování a prediktivní a...
  ❌ #17   -0.270  Uvedené dílčí funkce, které jsou spojeny s prediktivní analytikou můžeme pracovně pokládat za jednotlivé stavební kameny...
  ❌ #18   -2.395  Účelem kapitoly je uvést přehled základních principů analytických funkcí s vymezením jejich podstaty a příkladů využití....
  ❌ #19   -5.574  Plánování dopravních potřeb a jejich zajištění ve firmě představují tuto funkcionalitu:   - Plánování  jednotlivých  uka...
  ❌ #20   -8.150  **[2] Podstata plánovacích úloh**   (Funkcionalita a využití plánovacích úloh se zaměřením na výrobu, resp. strojírenstv...

🔀 Reranking grafových dokumentů...
  📊 Reranking [graph] (5 docs → top 10):
  Rank    Score  Preview
  ----------------------------------------------------------------------
  ✅ #1    10.819  Prediktivní analytika v řízení nákupů podporuje prognózování a plánování nákupů materiálů, zboží a služeb pro potřeby fi...
  ✅ #2     8.972  Účelem kapitoly je vymezit základní funkce prediktivní analytiky v rámci plánování v oblasti marketingu, řízení prodeje,...
  ✅ #3     6.857  **Analytické otázky :**   - Jak zvýšit úspěšnost a výkonnost byznysu díky vysoké kvalitě plánovacích úloh při řízení nák...
  ✅ #4     1.989  Oddíl se zaměřil na základní obsah prediktivní analytiky strojírenské firmy ve vazbě na potřeby jejího prognózování a pl...
  ✅ #5    -2.395  Účelem kapitoly je uvést přehled základních principů analytických funkcí s vymezením jejich podstaty a příkladů využití....


🏆 FINÁLNÍ POŘADÍ — VEKTOROVÉ dokumenty předané LLM:
  ----------------------------------------------------------------------
  #1   📂 15. Prediktivní analytika obchodu a logistiky
       💬 Účelem kapitoly je vymezit základní funkce prediktivní analytiky v rámci plánování v oblasti marketingu, řízení prodeje, nákupu a dopravy. Pro každou ...
  #2   📂 19.1 Obsah prediktivní analytiky v operativním plánování výroby | 19. Operativní řízení a plánování výroby
       💬 Prediktivní analytika v operativním řízení výroby zajišťuje tři druhy na sebe se vážících operací (Tomek, Vávrová, 2014):   - operativní plánování pro...
  #3   📂 18.1 Obsah prediktivní analytiky v plánování výrobních zakázek | 18. Prediktivní analytika v řízení výrobních zakázek
       💬 Prediktivní analytika v řízení výrobních zakázek má poskytovat podporu v těchto plánovacích aktivitách:   - plánování výrobních postupů a termínů výro...
  #4   📂 18. Prediktivní analytika v řízení výrobních zakázek
       💬 Účelem kapitoly je vymezit základní funkce prediktivní analytiky v rámci plánování výrobních zakázek, definování cílových proměnných a odpovídajících ...
  #5   📂 18.3 Řešení prediktivní analytiky v plánování výrobních zakázek | 18. Prediktivní analytika v řízení výrobních zakázek
       💬 **Funkce prediktivní analytiky v plánování výrobních zakázek:**   - Clustering: - klastry výrobních zakázek podle zákazníků strojírenské firmy, objemu...
  #6   📂 19. Operativní řízení a plánování výroby
       💬 Účelem kapitoly je vymezit funkcionalitu prediktivní analytiky v rámci operativního řízení a plánování výroby, definovat cílové proměnné a prediktory,...
  #7   📂 17. Prediktivní analytika v řízení investic, údržby a potřeby energií
       💬 Účelem kapitoly je vymezit hlavní funkce prediktivní analytiky v rámci plánování investic, údržby a potřeby energií strojírenské firmy. Na ty standard...
  #8   📂 17.2 Prediktivní analytika v plánování potřeby energií | 17. Prediktivní analytika v řízení investic, údržby a potřeby energií | 17.2.3 Řešení prediktivní analytiky v řízení energií
       💬 **Funkce prediktivní analytiky v plánování potřeby energií:**   - Clustering: - klastry poskytovatelů energií pro strojírenskou firmu podle druhů ener...
  #9   📂 16. Prediktivní analytika v personálním řízení
       💬 Účelem kapitoly je definovat obsah a hlavní funkce prediktivní analytiky v rámci personálního plánování. Na ně navazuje definování cílových proměnných...
  #10  📂 14. Prediktivní analytika ve finančním řízení
       💬 Účelem kapitoly  je  vymezit  funkce  prediktivní  analytiky  v rámci  finančního  plánování  a tvorby rozpočtů. Ta je základem pro definování cílovýc...

🏆 FINÁLNÍ POŘADÍ — GRAFOVÉ dokumenty předané LLM:
  ----------------------------------------------------------------------
  #1   💬 Prediktivní analytika v řízení nákupů podporuje prognózování a plánování nákupů materiálů, zboží a služeb pro potřeby firmy. V oblasti plánování nákup...
  #2   💬 Účelem kapitoly je vymezit základní funkce prediktivní analytiky v rámci plánování v oblasti marketingu, řízení prodeje, nákupu a dopravy. Pro každou ...
  #3   💬 **Analytické otázky :**   - Jak zvýšit úspěšnost a výkonnost byznysu díky vysoké kvalitě plánovacích úloh při řízení nákupů? - Jak co nejpřesněji a vč...
  #4   💬 Oddíl se zaměřil na základní obsah prediktivní analytiky strojírenské firmy ve vazbě na potřeby jejího prognózování a plánování. Předmětem řešení neby...
  #5   💬 Účelem kapitoly je uvést přehled základních principů analytických funkcí s vymezením jejich podstaty a příkladů využití. Ty budou konkretizovány podle...


📤 KONTEXT ODESLANÝ DO LLM (10,478 znaků):
======================================================================
[SEKCE 1 — Grafové dokumenty (preview prvních 800 znaků)]
Prediktivní analytika v řízení nákupů podporuje prognózování a plánování nákupů materiálů, zboží a služeb pro potřeby firmy. V oblasti plánování nákupů má zejména připravovat podklady pro tyto operace:
- sestavení výhledu a plánu nákupu,
- propočet spotřeby materiálu, resp. zboží na dané období,
- bilancování  potřeby  dodávek  materiálu  s  následnými  úpravami  podle  možností  dodavatele, představuje pak vstup do poptávek nebo objednávek,
- sestavení nákupního rozpočtu,
- podklady pro operativní plánování nákupu, které se realizuje ve vazbě na plánování prodeje a plán výroby, resp. plánování výrobních zakázek.
Účelem kapitoly je vymezit základní funkce prediktivní analytiky v rámci plánování v oblasti marketingu, řízení prodeje, nákupu a dopravy. Pro každou s oblastí jsou definován…

[SEKCE 2 — Vektorový text (preview prvních 800 znaků)]
Účelem kapitoly je vymezit základní funkce prediktivní analytiky v rámci plánování v oblasti marketingu, řízení prodeje, nákupu a dopravy. Pro každou s oblastí jsou definovány cílové proměnné a vybrané prediktory. Následně jsou formulovány analytické otázky pro konzultace  analytiků  s obchodními  manažery,  výrobním  manažerem  a  specialisty  firmy  a  následně i funkce a příklady prediktivní analytiky v řízení uvedených oblastí.

/var/folders/bq/dvsycyn560sgx_gql985ch9w0000gn/T/ipykernel_5993/1325014252.py:192: DeprecationWarning: LangchainLLMWrapper is deprecated and will be removed in a future version. Use llm_factory instead: from openai import OpenAI; from ragas.llms import llm_factory; llm = llm_factory('gpt-4o-mini', client=OpenAI(api_key='...'))
  ragas_llm = LangchainLLMWrapper(llm_judge)
/var/folders/bq/dvsycyn560sgx_gql985ch9w0000gn/T/ipykernel_5993/1325014252.py:193: DeprecationWarning: LangchainEmbeddingsWrapper is deprecated and will be removed in a future version. Use the modern embedding providers instead: embedding_factory('openai', model='text-embedding-3-small', client=openai_client) or from ragas.embeddings import OpenAIEmbeddings, GoogleEmbeddings, HuggingFaceEmbeddings
  ragas_emb = LangchainEmbeddingsWrapper(embeddings)

Evaluating:   0%|          | 0/144 [00:00<?, ?it/s]

📊 VÝSLEDKY PER OTÁZKA — planovani_pa

,method,question,BERTScore_P,BERTScore_R,BERTScore_F1,ROUGE_L_P,ROUGE_L_R,ROUGE_L_F1,faithfulness,answer_relevancy,context_recall,answer_correctness
0,Naive RAG,Jaké jsou funkce prediktivní analytiky v pláno...,0.714,0.757,0.735,0.168,0.217,0.189,1.000,0.471,0.167,0.775
1,Graph RAG,Jaké jsou funkce prediktivní analytiky v pláno...,0.746,0.851,0.795,0.534,0.984,0.692,1.000,0.492,1.000,0.974
2,Hybrid GraphRAG,Jaké jsou funkce prediktivní analytiky v pláno...,0.750,0.854,0.799,0.534,0.984,0.692,1.000,0.494,1.000,0.972
3,Naive RAG,Jake jsou dimenze v řešení úloh analytiky příp...,0.694,0.694,0.694,0.236,0.232,0.234,1.000,0.518,0.929,0.439
4,Graph RAG,Jake jsou dimenze v řešení úloh analytiky příp...,0.730,0.796,0.762,0.402,0.949,0.565,1.000,0.473,1.000,0.961
5,Hybrid GraphRAG,Jake jsou dimenze v řešení úloh analytiky příp...,0.725,0.792,0.757,0.379,0.932,0.539,1.000,0.505,1.000,0.961
6,Naive RAG,Jake jsou hlavní plánovací dimenze podle jedno...,0.842,0.875,0.858,0.828,0.987,0.901,1.000,0.438,1.000,0.978
7,Graph RAG,Jake jsou hlavní plánovací dimenze podle jedno...,0.835,0.867,0.851,0.819,0.987,0.895,1.000,0.438,1.000,0.978
8,Hybrid GraphRAG,Jake jsou hlavní plánovací dimenze podle jedno...,0.746,0.807,0.775,0.808,1.000,0.894,1.000,0.431,1.000,0.953
9,Naive RAG,Jaké jsou základní cíle plánovacích úloh?,0.621,0.706,0.661,0.093,0.266,0.137,1.000,0.387,0.667,0.258
10,Graph RAG,Jaké jsou základní cíle plánovacích úloh?,0.741,0.838,0.786,0.517,0.975,0.675,1.000,0.448,1.000,0.742
11,Hybrid GraphRAG,Jaké jsou základní cíle plánovacích úloh?,0.753,0.844,0.796,0.542,0.975,0.697,1.000,0.431,1.000,0.704
12,Naive RAG,Jaké plánovací nástroje jsou popsány v dokumentu?,0.697,0.755,0.725,0.308,0.333,0.320,0.200,0.461,0.800,0.715
13,Graph RAG,Jaké plánovací nástroje jsou popsány v dokumentu?,0.590,0.727,0.651,0.070,0.500,0.122,1.000,0.464,0.600,0.658
14,Hybrid GraphRAG,Jaké plánovací nástroje jsou popsány v dokumentu?,0.515,0.716,0.599,0.041,0.583,0.077,0.750,0.437,0.400,0.644
15,Naive RAG,Jaké jsou cílové proměnné strategického řízení?,0.620,0.628,0.624,0.085,0.102,0.093,0.333,0.353,0.100,0.145
16,Graph RAG,Jaké jsou cílové proměnné strategického řízení?,0.630,0.816,0.711,0.179,1.000,0.304,0.478,0.391,1.000,0.938
17,Hybrid GraphRAG,Jaké jsou cílové proměnné strategického řízení?,0.631,0.816,0.711,0.154,1.000,0.266,1.000,0.395,1.000,0.935
18,Naive RAG,Jaké analytické otázky řeší plánování prodeje?,0.694,0.735,0.714,0.110,0.182,0.137,1.000,0.411,0.000,0.598
19,Graph RAG,Jaké analytické otázky řeší plánování prodeje?,0.797,0.904,0.847,0.412,1.000,0.584,1.000,0.739,0.857,0.971
20,Hybrid GraphRAG,Jaké analytické otázky řeší plánování prodeje?,0.797,0.904,0.847,0.412,1.000,0.584,1.000,0.739,0.857,0.971
21,Naive RAG,Jaké jsou dimenze v řešení úloh finančního plá...,0.637,0.598,0.617,0.154,0.084,0.109,1.000,0.435,0.786,0.180
22,Graph RAG,Jaké jsou dimenze v řešení úloh finančního plá...,0.680,0.654,0.667,0.344,0.147,0.206,1.000,0.455,1.000,0.434
23,Hybrid GraphRAG,Jaké jsou dimenze v řešení úloh finančního plá...,0.690,0.779,0.732,0.288,0.923,0.439,1.000,0.462,1.000,0.939
24,Naive RAG,Vyjmenuj analytické otázky ve strategickém plá...,0.639,0.665,0.652,0.124,0.143,0.133,1.000,0.370,0.000,0.177
25,Graph RAG,Vyjmenuj analytické otázky ve strategickém plá...,0.897,0.954,0.925,0.840,1.000,0.913,0.500,0.607,1.000,0.980
26,Hybrid GraphRAG,Vyjmenuj analytické otázky ve strategickém plá...,0.897,0.954,0.925,0.840,1.000,0.913,0.833,0.458,1.000,0.980
27,Naive RAG,Co jsou osy P-F křivky?,0.608,0.675,0.640,0.037,0.071,0.049,0.000,0.522,0.000,0.161
28,Graph RAG,Co jsou osy P-F křivky?,0.804,0.879,0.840,0.619,0.929,0.743,1.000,0.546,1.000,0.556
29,Hybrid GraphRAG,Co jsou osy P-F křivky?,0.806,0.881,0.842,0.650,0.929,0.765,1.000,0.588,1.000,0.560
30,Naive RAG,Jaké skupiny metrik zahrnuje strategické pláno...,0.611,0.650,0.630,0.062,0.219,0.097,1.000,0.487,0.833,0.284
31,Graph RAG,Jaké skupiny metrik zahrnuje strategické pláno...,0.745,0.858,0.797,0.429,0.844,0.568,1.000,0.479,1.000,0.688
32,Hybrid GraphRAG,Jaké skupiny metrik zahrnuje strategické pláno...,0.793,0.902,0.844,0.561,1.000,0.719,0.667,0.478,1.000,0.967
33,Naive RAG,Jaké jsou funkce prediktivní analytiky v marke...,0.797,0.888,0.840,0.546,0.983,0.702,0.938,0.591,1.000,0.976
34,Graph RAG,Jaké jsou funkce prediktivní analytiky v marke...,0.641,0.705,0.672,0.131,0.283,0.179,1.000,0.589,1.000,0.511
35,Hybrid GraphRAG,Jaké jsou funkce prediktivní analytiky v marke...,0.692,0.727,0.709,0.173,0.233,0.199,1.000,0.814,1.000,0.718

📊 PRŮMĚRNÉ SKÓRE — planovani_pa

,BERTScore_P,BERTScore_R,BERTScore_F1,ROUGE_L_P,ROUGE_L_R,ROUGE_L_F1,faithfulness,answer_relevancy,context_recall,answer_correctness
method,,,,,,,,,,
Graph RAG,0.736,0.821,0.775,0.441,0.800,0.537,0.915,0.510,0.955,0.783
Hybrid GraphRAG,0.733,0.831,0.778,0.449,0.880,0.565,0.938,0.519,0.938,0.859
Naive RAG,0.681,0.719,0.699,0.229,0.318,0.258,0.789,0.454,0.523,0.474

🏆 Nejlepší ROUGE-L Recall (úplnost):       Hybrid GraphRAG
🏆 Nejlepší BERTScore F1 (sémantika):        Hybrid GraphRAG
🏆 Nejlepší Answer Correctness (RAGAS):      Hybrid GraphRAG

✅ Výsledky uloženy → evaluation_planovani_pa.csv

,document,method,question,answer,context,time_s,ground_truth,BERTScore_P,BERTScore_R,BERTScore_F1,ROUGE_L_P,ROUGE_L_R,ROUGE_L_F1,faithfulness,answer_relevancy,context_recall,answer_correctness
0,planovani_pa,Naive RAG,Jaké jsou funkce prediktivní analytiky v pláno...,Funkce prediktivní analytiky v plánování nákup...,Účelem kapitoly je vymezit funkcionalitu predi...,18.6,- Clustering: klastry dodavatelů podle dodávan...,0.714192,0.756678,0.734821,0.167665,0.217054,0.189189,1.000000,0.470824,0.166667,0.775423
1,planovani_pa,Graph RAG,Jaké jsou funkce prediktivní analytiky v pláno...,Funkce prediktivní analytiky v plánování nákup...,### DOKUMENTY Z GRAFU:\nPrediktivní analytika ...,20.3,- Clustering: klastry dodavatelů podle dodávan...,0.745744,0.851247,0.795011,0.533613,0.984496,0.692098,1.000000,0.491682,1.000000,0.973967
2,planovani_pa,Hybrid GraphRAG,Jaké jsou funkce prediktivní analytiky v pláno...,Funkce prediktivní analytiky v plánování nákup...,### 1. DOKUMENTY Z GRAFU (PRIMÁRNÍ ZDROJ - ČTĚ...,21.5,- Clustering: klastry dodavatelů podle dodávan...,0.749811,0.854337,0.798669,0.533613,0.984496,0.692098,1.000000,0.493506,1.000000,0.971577
3,planovani_pa,Naive RAG,Jake jsou dimenze v řešení úloh analytiky příp...,Dimenze v řešení úloh analytiky přípravy a plá...,Účelem kapitoly je vymezit funkcionalitu predi...,20.7,"Čas - časová dimenze určující dobu poptávky, z...",0.693650,0.694047,0.693849,0.235632,0.231638,0.233618,1.000000,0.518056,0.928571,0.438870
4,planovani_pa,Graph RAG,Jake jsou dimenze v řešení úloh analytiky příp...,Dimenze v řešení úloh analytiky přípravy a plá...,### DOKUMENTY Z GRAFU:\n**[10.1] Dimenze v řeš...,28.0,"Čas - časová dimenze určující dobu poptávky, z...",0.729696,0.796431,0.761604,0.401914,0.949153,0.564706,1.000000,0.473013,1.000000,0.960950
5,planovani_pa,Hybrid GraphRAG,Jake jsou dimenze v řešení úloh analytiky příp...,Dimenze v řešení úloh analytiky přípravy a plá...,### 1. DOKUMENTY Z GRAFU (PRIMÁRNÍ ZDROJ - ČTĚ...,29.9,"Čas - časová dimenze určující dobu poptávky, z...",0.725155,0.791677,0.756957,0.379310,0.932203,0.539216,1.000000,0.505013,1.000000,0.961398
6,planovani_pa,Naive RAG,Jake jsou hlavní plánovací dimenze podle jedno...,Podle tabulky B-1 jsou hlavní plánovací dimenz...,Tabulka B-1: Přehled hlavních plánovacích dime...,28.1,"Základní dimenze: Časová dimenze, Regiony, Odv...",0.841777,0.874762,0.857952,0.827957,0.987179,0.900585,1.000000,0.438132,1.000000,0.978155
7,planovani_pa,Graph RAG,Jake jsou hlavní plánovací dimenze podle jedno...,Podle tabulky B-1 jsou hlavní plánovací dimenz...,### DOKUMENTY Z GRAFU:\nTabulka B-1: Přehled h...,20.9,"Základní dimenze: Časová dimenze, Regiony, Odv...",0.835250,0.867390,0.851017,0.819149,0.987179,0.895349,1.000000,0.438132,1.000000,0.978487
8,planovani_pa,Hybrid GraphRAG,Jake jsou hlavní plánovací dimenze podle jedno...,Hlavní plánovací dimenze podle jednotlivých sk...,### 1. DOKUMENTY Z GRAFU (PRIMÁRNÍ ZDROJ - ČTĚ...,27.2,"Základní dimenze: Časová dimenze, Regiony, Odv...",0.745838,0.807065,0.775245,0.808290,1.000000,0.893983,1.000000,0.431391,1.000000,0.952885
9,planovani_pa,Naive RAG,Jaké jsou základní cíle plánovacích úloh?,Plánovací úlohy mají několik základních cílů:\...,Plánování skladů a skladových zásob firmy jsou...,21.8,- Vytvořit a využít plánovací systém respektuj...,0.621298,0.706267,0.661063,0.092511,0.265823,0.137255,1.000000,0.386567,0.666667,0.257767
10,planovani_pa,Graph RAG,Jaké jsou základní cíle plánovacích úloh?,Plánovací úlohy sledují několik základních cíl...,### DOKUMENTY Z GRAFU:\nFunkce: \nPlánovací ú...,15.3,- Vytvořit a využít plánovací systém respektuj...,0.740621,0.837730,0.786188,0.516779,0.974684,0.675439,1.000000,0.448135,1.000000,0.742424
11,planovani_pa,Hybrid GraphRAG,Jaké jsou základní cíle plánovacích úloh?,Plánovací úlohy sledují několik základních cíl...,### 1. DOKUMENTY Z GRAFU (PRIMÁRNÍ ZDROJ - ČTĚ...,16.2,- Vytvořit a využít plánovací systém respektuj...,0.753439,0.844272,0.796274,0.542254,0.974684,0.696833,1.000000,0.430556,1.000000,0.704033
12,planovani_pa,Naive RAG,Jaké plánovací nástroje jsou popsány v dokumentu?,Plánovací nástroje popsané v dokumentu jsou:\n...,- V uvedeném schématu jsou v hranatých závorká...,15.4,"Oracle Enterprise Performance Management, IBM ...",0.697454,0.755241,0.725198,0.307692,0.333333,0.320000,0.200000,0.460997,0.800000,0.714855
13,planovani_pa,Graph RAG,Jaké plánovací nástroje jsou popsány v dokumentu?,Plánovací nástroje popsané v dokumentu jsou:\n...,### DOKUMENTY Z GRAFU:\nFunkce: \nPlánovací ú...,13.2,"Oracle Enterprise Performance Management, IBM ...",0.590099,0.726675,0.651304,0.069767,0.500000,0.122449,1.000000,0.463841,0.600000,0.657750
14,planovani_pa,Hybrid GraphRAG,Jaké plánovací nástroje jsou popsány v dokumentu?,"Plánovací nástroje, které jsou popsány v dokum...",### 1. DOKUMENTY Z GRAFU (PRIMÁRNÍ ZDROJ - ČTĚ...,17.5,"Oracle Enterprise Performance Management, IBM ...",0.515194,0.716305,0.599328,0.040936,0.583333,0.076503,0.750000,0.437482,0.400000,0.643933
15,planovani_pa,Naive RAG,Jaké jsou cílové proměnné strategického řízení?,Cílové proměnné strategického řízení jsou:\n\n...,Plánování skladů a skladových zásob firmy jsou...,15.9,"Hospodářský výsledek, Počet plánovaných inovac...",0.619587,0.628271,0.623899,0.084746,0.102041,0.092593,0.333333,0.353238,0.100000,0.144959
16,planovani_pa,Graph RAG,Jaké jsou cílové proměnné strategického řízení?,Cílové proměnné strategického řízení zahrnují:...,### DOKUMENTY Z GRAFU:\nNáměty na specifikaci ...,20.3,"Hospodářský výsledek, Počet plánovaných inovac...",0.630194,0.816307,0.711278,0.179487,1.000000,0.304348,0.478261,0.390798,1.000000,0.938108
17,planovani_pa,Hybrid GraphRAG,Jaké jsou cílové proměnné strategického řízení?,Cílové proměnné strategického řízení zahrnují:...,### 1. DOKUMENTY Z GRAFU (PRIMÁRNÍ ZDROJ - ČTĚ...,22.3,"Hospodářský výsledek, Počet plánovaných inovac...",0.630892,0.815610,0.711457,0.153605,1.000000,0.266304,1.000000,0.394837,1.000000,0.935423
18,planovani_pa,Naive RAG,Jaké analytické otázky řeší plánování prodeje?,Plánování prodeje řeší následující analytické ...,- Analýzy ukazatelů pro operativní plánování p...,26.0,- Jak zvýšit úspěšnost a výkonnost byznysu dík...,0.693996,0.734524,0.713685,0.110429,0.181818,0.137405,1.000000,0.411192,0.000000,0.598269
19,planovani_pa,Graph RAG,Jaké analytické otázky řeší plánování prodeje?,"Analytické otázky, které řeší plánování prodej...",### DOKUMENTY Z GRAFU:\n**Analytické otázky :*...,19.7,- Jak zvýšit úspěšnost a výkonnost byznysu dík...,0.796778,0.904304,0.847142,0.412500,1.000000,0.584071,1.000000,0.739343,0.857143,0.970553
20,planovani_pa,Hybrid GraphRAG,Jaké analytické otázky řeší plánování prodeje?,"Analytické otázky, které řeší plánování prodej...",### 1. DOKUMENTY Z GRAFU (PRIMÁRNÍ ZDROJ - ČTĚ...,20.4,- Jak zvýšit úspěšnost a výkonnost byznysu dík...,0.796778,0.904304,0.847142,0.412500,1.000000,0.584071,1.000000,0.739343,0.857143,0.970553
21,planovani_pa,Naive RAG,Jaké jsou dimenze v řešení úloh finančního plá...,"- Hospodářský výsledek, resp. Výsledek hospoda...",Plánování skladů a skladových zásob firmy jsou...,20.8,Čas - časová dimenze plánovací horizonty finan...,0.636848,0.597567,0.616583,0.153846,0.083916,0.108597,1.000000,0.435335,0.785714,0.179890
22,planovani_pa,Graph RAG,Jaké jsou dimenze v řešení úloh finančního plá...,Dimenze v řešení úloh finančního plánování jso...,### DOKUMENTY Z GRAFU:\n**[6.1] Dimenze pro ře...,14.3,Čas - časová dimenze plánovací horizonty finan...,0.680248,0.654107,0.666921,0.344262,0.146853,0.205882,1.000000,0.455180,1.000000,0.434499
23,planovani_pa,Hybrid GraphRAG,Jaké jsou dimenze v řešení úloh finančního plá...,Dimenze v řešení úloh finančního plánování jso...,### 1. DOKUMENTY Z GRAFU (PRIMÁRNÍ ZDROJ - ČTĚ...,30.0,Čas - časová dimenze plánovací horizonty finan...,0.690105,0.778620,0.731696,0.288210,0.923077,0.439268,1.000000,0.461736,1.000000,0.938929
24,planovani_pa,Naive RAG,Vyjmenuj analytické otázky ve strategickém plá...,Analytické otázky ve strategickém plánování:\n...,**[10.1] Dimenze v řešení úloh operativního pl...,14.4,Navazují roční plány na dlouhodobou strategii ...,0.638611,0.665444,0.651751,0.123711,0.142857,0.132597,1.000000,0.369833,0.000000,0.176575
25,planovani_pa,Graph RAG,Vyjmenuj analytické otázky ve strategickém plá...,Analytické otázky ve strategickém plánování js...,### DOKUMENTY Z GRAFU:\nOddíl se zaměřil na zá...,12.5,Navazují roční plány na dlouhodobou strategii ...,0.897292,0.953666,0.924621,0.840000,1.000000,0.913043,0.500000,0.606519,1.000000,0.980138
26,planovani_pa,Hybrid GraphRAG,Vyjmenuj analytické otázky ve strategickém plá...,Analytické otázky ve strategickém plánování js...,### 1. DOKUMENTY Z GRAFU (PRIMÁRNÍ ZDROJ - ČTĚ...,13.7,Navazují roční plány na dlouhodobou strategii ...,0.897292,0.953666,0.924621,0.840000,1.000000,0.913043,0.833333,0.457897,1.000000,0.980138
27,planovani_pa,Naive RAG,Co jsou osy P-F křivky?,Osy P-F křivky jsou:\n\n* **P** - Problém (Pro...,Plánování skladů a skladových zásob firmy jsou...,16.4,Osa X znázorňuje čas. Osa Y (svislá) představu...,0.607917,0.674682,0.639562,0.037037,0.071429,0.048780,0.000000,0.522357,0.000000,0.160846
28,planovani_pa,Graph RAG,Co jsou osy P-F křivky?,Osa X na grafu P-F křivky znázorňuje čas a svi...,### DOKUMENTY Z GRAFU:\nV souvislosti s lepší...,8.5,Osa X znázorňuje čas. Osa Y (svislá) představu...,0.804229,0.879460,0.840164,0.619048,0.928571,0.742857,1.000000,0.546040,1.000000,0.555817
29,planovani_pa,Hybrid GraphRAG,Co jsou osy P-F křivky?,"Osa X na grafu P-F křivky znázorňuje čas, svis...",### 1. DOKUMENTY Z GRAFU (PRIMÁRNÍ ZDROJ - ČTĚ...,10.8,Osa X znázorňuje čas. Osa Y (svislá) představu...,0.806046,0.881077,0.841893,0.650000,0.928571,0.764706,1.000000,0.587951,1.000000,0.559526
30,planovani_pa,Naive RAG,Jaké skupiny metrik zahrnuje strategické pláno...,Strategické plánování strojírenské firmy zahrn...,**Plánování nákupních aktivit firmy představuj...,23.9,"- Finanční strategie\n- Obchodní strategie, st...",0.611294,0.650407,0.630244,0.062500,0.218750,0.097222,1.000000,0.487438,0.833333,0.283945
31,planovani_pa,Graph RAG,Jaké skupiny metrik zahrnuje strategické pláno...,Strategické plánování strojírenské firmy zahrn...,### DOKUMENTY Z GRAFU:\nStrategie strojírenské...,9.9,"- Finanční strategie\n- Obchodní strategie, st...",0.744985,0.857615,0.797342,0.428571,0.843750,0.568421,1.000000,0.478540,1.000000,0.687997
32,planovani_pa,Hybrid GraphRAG,Jaké skupiny metrik zahrnuje strategické pláno...,Strategické plánování strojírenské firmy zahrn...,### 1. DOKUMENTY Z GRAFU (PRIMÁRNÍ ZDROJ - ČTĚ...,10.7,"- Finanční strategie\n- Obchodní strategie, st...",0.793315,0.902182,0.844253,0.561404,1.000000,0.719101,0.666667,0.478320,1.000000,0.966876
33,planovani_pa,Naive RAG,Jaké jsou funkce prediktivní analytiky v marke...,Funkce prediktivní analytiky v marketingu zahr...,Účelem kapitoly je vymezit základní funkce pre...,24.6,- Clustering: klastry zákazníků strojírenské f...,0.796598,0.888152,0.839887,0.546296,0.983333,0.702381,0.937500,0.591107,1.000000,0.975894
34,planovani_pa,Graph RAG,Jaké jsou funkce prediktivní analytiky v marke...,Funkce prediktivní analytiky v marketingu zahr...,### DOKUMENTY Z GRAFU:\nPrediktivní analytika ...,21.5,- Clustering: klastry zákazníků strojírenské f...,0.641444,0.704543,0.671514,0.130769,0.283333,0.178947,1.000000,0.589419,1.000000,0.511303
35,planovani_pa,Hybrid GraphRAG,Jaké jsou funkce prediktivní analytiky v marke...,Funkce prediktivní analytiky v marketingu zahr...,### 1. DOKUMENTY Z GRAFU (PRIMÁRNÍ ZDROJ - ČTĚ...,19.6,- Clustering: klastry zákazníků strojírenské f...,0.691574,0.726580,0.708645,0.172840,0.233333,0.198582,1.000000,0.813973,1.000000,0.718054

In [ ]:
df1 = pd.read_csv('../evaluation/evaluation_strojirenska_firma.csv')
df2 = pd.read_csv('../evaluation/evaluation_planovani_pa.csv')

metrics = ['BERTScore_F1', 'ROUGE_L_R', 'ROUGE_L_F1',
           'faithfulness', 'answer_relevancy', 'context_recall', 'answer_correctness']
metrics = [m for m in metrics if df1[m].notna().any()]

# Průměrné skóre per dokument
for label, df in [('Strojírenská firma', df1), ('Plánování PA', df2)]:
    dv = df[df['answer'] != 'TIMEOUT']
    print(f'\n=== {label} — průměry ===')
    display(dv.groupby('method')[metrics].mean().round(3))

# Souhrnné průměry přes oba dokumenty
dv_all = pd.concat([df1, df2])
dv_all = dv_all[dv_all['answer'] != 'TIMEOUT']
print('\n=== Souhrn — oba dokumenty ===')
display(dv_all.groupby('method')[metrics].mean().round(3))

# Výsledky per typ otázky — Strojírenská firma
typy_firma = {
    'Výčtové':       df1['question'].unique()[0:3],
    'Definice/účel': df1['question'].unique()[3:6],
    'Vztahové':      df1['question'].unique()[6:9],
    'Faktické':      df1['question'].unique()[9:12],
}
print('\n=== Strojírenská firma — per typ otázky ===')
for typ, qs in typy_firma.items():
    sub = df1[df1['question'].isin(qs) & (df1['answer'] != 'TIMEOUT')]
    print(f'\n{typ}:')
    display(sub.groupby('method')[['ROUGE_L_R', 'BERTScore_F1', 'answer_correctness']].mean().round(3))

# Výsledky per typ otázky — Plánování PA
typy_pa = {
    'Výčtové':       df2['question'].unique()[0:3],
    'Definice/účel': df2['question'].unique()[3:6],
    'Vztahové':      df2['question'].unique()[6:9],
    'Faktické':      df2['question'].unique()[9:12],
}
print('\n=== Plánování PA — per typ otázky ===')
for typ, qs in typy_pa.items():
    sub = df2[df2['question'].isin(qs) & (df2['answer'] != 'TIMEOUT')]
    print(f'\n{typ}:')
    display(sub.groupby('method')[['ROUGE_L_R', 'BERTScore_F1', 'answer_correctness']].mean().round(3))

=== Strojírenská firma — průměry ===

,BERTScore_F1,ROUGE_L_R,ROUGE_L_F1,faithfulness,answer_relevancy,context_recall,answer_correctness
method,,,,,,,
Graph RAG,0.748,0.792,0.372,0.861,0.629,0.833,0.689
Hybrid GraphRAG,0.798,0.862,0.527,0.917,0.596,1.000,0.756
Naive RAG,0.701,0.342,0.243,0.892,0.558,0.785,0.594

=== Plánování PA — průměry ===

,BERTScore_F1,ROUGE_L_R,ROUGE_L_F1,faithfulness,answer_relevancy,context_recall,answer_correctness
method,,,,,,,
Graph RAG,0.775,0.800,0.537,0.915,0.510,0.955,0.783
Hybrid GraphRAG,0.778,0.880,0.565,0.938,0.519,0.938,0.859
Naive RAG,0.699,0.318,0.258,0.789,0.454,0.523,0.474

=== SOUHRN — oba dokumenty ===

,BERTScore_F1,ROUGE_L_R,ROUGE_L_F1,faithfulness,answer_relevancy,context_recall,answer_correctness
method,,,,,,,
Graph RAG,0.761,0.796,0.455,0.889,0.569,0.894,0.736
Hybrid GraphRAG,0.788,0.871,0.546,0.927,0.558,0.969,0.807
Naive RAG,0.700,0.330,0.250,0.841,0.506,0.654,0.534

=== Strojírenská firma — per typ otázky ===

Výčtové:

                 ROUGE_L_R  BERTScore_F1  answer_correctness
method
Graph RAG            0.689         0.719               0.476
Hybrid GraphRAG      0.771         0.726               0.677
Naive RAG            0.315         0.678               0.685

Definice/účel:

                 ROUGE_L_R  BERTScore_F1  answer_correctness
method
Graph RAG            0.822         0.784               0.845
Hybrid GraphRAG      0.859         0.817               0.764
Naive RAG            0.286         0.686               0.723

Vztahové:

                 ROUGE_L_R  BERTScore_F1  answer_correctness
method
Graph RAG            0.912         0.745               0.620
Hybrid GraphRAG      0.968         0.881               0.798
Naive RAG            0.269         0.747               0.441

Faktické:

                 ROUGE_L_R  BERTScore_F1  answer_correctness
method
Graph RAG            0.743         0.742               0.816
Hybrid GraphRAG      0.849         0.768               0.785
Naive RAG            0.497         0.694               0.528

=== Plánování PA — per typ otázky ===

Výčtové:

                 ROUGE_L_R  BERTScore_F1  answer_correctness
method
Graph RAG            0.974         0.803               0.971
Hybrid GraphRAG      0.972         0.777               0.962
Naive RAG            0.479         0.762               0.731

Definice/účel:

                 ROUGE_L_R  BERTScore_F1  answer_correctness
method
Graph RAG            0.825         0.716               0.779
Hybrid GraphRAG      0.853         0.702               0.761
Naive RAG            0.234         0.670               0.373

Vztahové:

                 ROUGE_L_R  BERTScore_F1  answer_correctness
method
Graph RAG            0.716         0.813               0.795
Hybrid GraphRAG      0.974         0.834               0.963
Naive RAG            0.136         0.661               0.318

Faktické:

                 ROUGE_L_R  BERTScore_F1  answer_correctness
method
Graph RAG            0.685         0.770               0.585
Hybrid GraphRAG      0.721         0.798               0.748
Naive RAG            0.425         0.703               0.474

In [ ]:
df1 = pd.read_csv('../evaluation/evaluation_strojirenska_firma.csv')
df2 = pd.read_csv('../evaluation/evaluation_planovani_pa.csv')
df_all = pd.concat([df1, df2])
df_all = df_all[df_all['answer'] != 'TIMEOUT']

metrics_show = ['ROUGE_L_R', 'BERTScore_F1', 'context_recall', 'answer_correctness']

# Pivot tabulka pro porovnání Answer Correctness per metoda
pivot = df_all.pivot_table(
    index=['document', 'question'],
    columns='method',
    values='answer_correctness',
    aggfunc='first'
).reset_index()
pivot.columns.name = None

# Otázky kde Naive RAG překonal Graph RAG o více než 0.4 bodů
naive_wins = pivot[
    (pivot['Naive RAG'] > pivot['Graph RAG']) &
    (pivot['Naive RAG'] - pivot['Graph RAG'] >= 0.4)
].copy()
naive_wins['diff (Naive-Graph)'] = (naive_wins['Naive RAG'] - naive_wins['Graph RAG']).round(3)
naive_wins = naive_wins.sort_values('diff (Naive-Graph)', ascending=False)

print(f"Otázky kde Naive RAG > Graph RAG (rozdíl >= 0.4, metrika: Answer Correctness): {len(naive_wins)}")
display(naive_wins[['document', 'question', 'Naive RAG', 'Graph RAG', 'Hybrid GraphRAG', 'diff (Naive-Graph)']].round(3).reset_index(drop=True))

# Detail per otázka — metriky a vygenerované odpovědi
print("\nDetail per otázka")
for _, row in naive_wins.iterrows():
    q   = row['question']
    doc = row['document']
    print(f"\n{'=' * 70}")
    print(f"Dokument: {doc} | Otázka: {q}")

    sub = df_all[df_all['question'] == q][['method'] + metrics_show].copy()
    sub = sub.rename(columns={
        'ROUGE_L_R':          'ROUGE-L Recall',
        'BERTScore_F1':       'BERTScore F1',
        'context_recall':     'Context Recall',
        'answer_correctness': 'Answer Correctness'
    }).set_index('method')
    display(sub.round(3))

    print("\nOdpovědi:")
    for method in ['Naive RAG', 'Graph RAG', 'Hybrid GraphRAG']:
        ans_row = df_all[(df_all['question'] == q) & (df_all['method'] == method)]
        if not ans_row.empty:
            answer = ans_row['answer'].values[0]
            ac     = ans_row['answer_correctness'].values[0]
            print(f"\n{method} (AC={float(ac or 0):.3f})")
            print(answer[:1000] + ('...' if len(str(answer)) > 1000 else ''))

📊 Otázky kde Naive RAG > Graph RAG (rozdíl ≥ 0.4) — metrika: Answer Correctness (celkem: 2)

,document,question,Naive RAG,Graph RAG,Hybrid GraphRAG,diff (Naive−Graph)
0,strojirenska_firma,Jaké funkce zahrnuje pokročilá analytika v mar...,0.957,0.173,0.746,0.784
1,planovani_pa,Jaké jsou funkce prediktivní analytiky v marke...,0.976,0.511,0.718,0.465

📊 Detail per otázka — metriky + odpovědi

══════════════════════════════════════════════════════════════════════
Dokument: strojirenska_firma | Otázka: Jaké funkce zahrnuje pokročilá analytika v marketingu?

,ROUGE-L Recall,BERTScore F1,Context Recall,Answer Correctness
method,,,,
Naive RAG,0.569,0.727,1.0,0.957
Graph RAG,0.176,0.640,0.0,0.173
Hybrid GraphRAG,0.451,0.711,1.0,0.746

📝 Odpovědi:

── Naive RAG (AC=0.957) ──
Pokročilá analytika v marketingu zahrnuje následující funkce:

1.  **Segmentace**: rozdělení objektů do skupin, které mají podobné charakteristiky, např. segmentace demografická, behaviorální (podle chování), geografická apod.
2.  **Analýza nákupního košíku**: zjišťuje souvislosti mezi produkty, které kupují zákazníci společně, a nabízí kombinace produktů (cross selling) apod.
3.  **Predikce odchodu zákazníků** - 'churn management': předpovídá zákazníky, kteří hodlají odejít ke konkurenci nebo přestat využívat určité produkty nebo služby.
4.  **Credit scoring**: ohodnocení zákazníka podle úvěrového rizika, zda bude splácet např. svůj úvěr.

Pokročilá analytika v marketingu se zaměřuje na prediktivní analýzu a předpovídání chování zákazníků, aby bylo možné efektivněji cílit na jejich potřeby a nabízet jim relevantní produkty nebo služby....

── Graph RAG (AC=0.173) ──
Není možné odpovědět na otázku, protože se týká marketingu, nikoli finančního řízení. Pokročilá analytika v kontextu dokumentů z grafu řeší finanční vývoj a problémy, zejména predikce v oblasti finančního řízení.

Pokud byste chtěli vědět, jaké funkce zahrnuje pokročilá analytika v kontextu finančního řízení, mohu vám říci:

- hodnocení očekávaného zisku a výnosů v závislosti na stavu trhu, maržích a vlastní produkci,
- analýzy vývoje nákladů podle vývoje vlastní nabídky a produkce,
- predikce úvěrového zatížení firmy,
- hodnocení pohledávek a závazků podle významu partnerů.

Tyto funkce jsou popsány v dokumentech z grafu jako součást finančního řízení....

── Hybrid GraphRAG (AC=0.746) ──
Pokročilá analytika v marketingu zahrnuje následující funkce:

* Segmentace, tj. rozdělení objektů do skupin, které mají podobné charakteristiky
* Analýza nákupního košíku zjišťuje souvislosti mezi produkty, které kupují zákazníci společně
* Predikce odchodu zákazníků - 'churn management' -předpovídá zákazníky, kteří hodlají odejít ke konkurenci, nebo přestat využívat určité produkty nebo služby
* Credit scoring je ohodnocení zákazníka podle úvěrového rizika, zda bude splácet např. svůj úvěr

Tyto funkce jsou popsány v kapitole '2. Finanční řízení firmy | 2.1 Přehled a obsah úloh finančního řízení | 2.1.9 Finance - pokročilá analytika' a také v kapitole '7-12: Prodej - pokročilá analytika'....

══════════════════════════════════════════════════════════════════════
Dokument: planovani_pa | Otázka: Jaké jsou funkce prediktivní analytiky v marketingu?

,ROUGE-L Recall,BERTScore F1,Context Recall,Answer Correctness
method,,,,
Naive RAG,0.983,0.840,1.0,0.976
Graph RAG,0.283,0.672,1.0,0.511
Hybrid GraphRAG,0.233,0.709,1.0,0.718

📝 Odpovědi:

── Naive RAG (AC=0.976) ──
Funkce prediktivní analytiky v marketingu zahrnují:

- Clustering:
  - klastry zákazníků strojírenské firmy podle typu výroby, příslušnosti k dodavatelskému řetězci, dislokace závodů apod.,
  - segmentace zákazníků podle technickoekonomických charakteristik,
  - segmentace marketingových akcí, podle zaměření na skupiny zákazníků, způsobu realizace, teritoriálního zaměření.

- Klasifikace :
  - klasifikace zákazníků - jejich rozřazení do stejnorodých tříd a odhad pravděpodobnosti správnosti takového zařazení pro každého zákazníka,
  - klasifikace prodávaného zboží - obvykle podle katalogu zboží,
  - klasifikace marketingových akcí - posouzení správnosti klasifikace uvedením pravděpodobnosti správného členění.

- Přiřazování podobností:
  - určování podstatných charakteristik zákazníků a na tomto základě výběr firem, které jsou obdobné našim nejlepším zákazníkům.

- Profilování, ' Popis chování ' :
  - specifikace klíčových charakteristik zákazníků z pohledu přístupů k zajištění a řízení...

── Graph RAG (AC=0.511) ──
Funkce prediktivní analytiky v marketingu zahrnují:

1.  **Clustering**: seskupování dat podle jejich podobnosti, vytváření klastrů zákazníků nebo dodavatelů.
2.  **Klasifikace a hodnocení pravděpodobnosti tříd (Classification and class probability estimation)**: určování cílové třídy s využitím sledovaných hodnot a odhad pravděpodobnosti správnosti zařazení objektu do této třídy.
3.  **Rozhodovací pravidla**: použití rozhodovacích pravidel podobně jako u rozhodovacích stromů, které umožňují klasifikovat kategorii cílového atributu z kombinace kategorií vstupních atributů.
4.  **Asociační pravidla**: vyhledávání vazeb mezi různými atributy v předpokladu a závěru, které jsou důležité pro predikci chování zákazníků nebo produktů.
5.  **Přiřazování podobností (Similarity matching)**: identifikace podobných objektů na základě jejich známých dat, využívání firmografických charakteristik firem a od nich odvozených objektů.
6.  **Seskupování podle výskytů (Co-occurence grouping)**: vyhledáván...

── Hybrid GraphRAG (AC=0.718) ──
Funkce prediktivní analytiky v marketingu zahrnují:

1.  **Clustering**: seskupování dat podle jejich podobnosti, vytváření klastrů zákazníků nebo produktů.
2.  **Klasifikace**: rozřazení objektů do tříd na základě jejich charakteristik a odhad pravděpodobnosti správnosti takového zařazení.
3.  **Přiřazování podobností (Similarity matching)**: identifikace podobných objektů podle jejich známých dat.
4.  **Profilování**: popis typického chování jednotlivce nebo skupiny, označuje se také jako 'Popis chování'.
5.  **Predikce vazeb (Link prediction)**: predikce vazeb mezi datovými položkami a navržení, že taková vazba by měla existovat.
6.  **Redukce dat (Data reduction)**: redukce velkých objemů dat na ty nejpodstatnější informace pro analýzy.

Tyto funkce jsou využívány v různých oblastech marketingu, jako je plánování cílů a zaměření marketingových akcí, segmentace zákazníků nebo produktů, klasifikace prodávaného zboží nebo marketingových akcí....