# GraphRAG Pipeline + Evaluace

Tento notebook obsahuje **dvě části**:

1. **Pipeline** (buňky 1–12) — načtení dokumentu, build grafu, indexy, retrievery, RAG chain
2. **Evaluace** (buňky 13+) — testovací sady, metrikY (BERTScore, ROUGE-L, RAGAS), `evaluate()`

**Důležité:** Evaluace volá přímo retrievery z pipeline (`full_retriever`, `standard_retriever`, `pure_graph_retriever`), takže výsledky jsou vždy identické s produkcí.

---

##  Část 1 — Pipeline

In [ ]:
import hashlib
import inspect
import os
import pickle
import re
import threading
import time

from dotenv import load_dotenv
from IPython.display import display
from neo4j import GraphDatabase
from pydantic import BaseModel, Field

from langchain_community.graphs import Neo4jGraph
from langchain_community.vectorstores import Neo4jVector
from langchain_core.output_parsers import StrOutputParser
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.runnables import RunnablePassthrough
from langchain_experimental.graph_transformers import LLMGraphTransformer
from langchain_experimental.llms.ollama_functions import OllamaFunctions
from langchain_ollama import ChatOllama, OllamaEmbeddings
from langchain_text_splitters import MarkdownHeaderTextSplitter, RecursiveCharacterTextSplitter


load_dotenv()

True

In [ ]:
# Připojení k Neo4j 
graph = Neo4jGraph(
    url=os.environ.get('NEO4J_URI'),
    username=os.environ.get('NEO4J_USERNAME'),
    password=os.environ.get('NEO4J_PASSWORD')
)

# Inicializace modelu 
llm = OllamaFunctions(model="llama3.1:8b", temperature=0, format="json", num_predict=4096)

In [ ]:
file_path = "../documents/md/AF_III_02_01__Strojirenska_Firma.md"
cache_file = "../cache/AF_III_02_01__Strojirenska_Firma.pkl"

In [ ]:
with open(file_path, "r", encoding="utf-8") as f:
    md_content = f.read()

# 1. Rozšířené split podle nadpisů (H1 - H6)
headers_to_split_on = [
    ("#", "Header 1"), ("##", "Header 2"), ("###", "Header 3"),
    ("####", "Header 4"), ("#####", "Header 5"), ("######", "Header 6"),
]
markdown_splitter = MarkdownHeaderTextSplitter(headers_to_split_on=headers_to_split_on)
md_header_splits = markdown_splitter.split_text(md_content)

# 2. Zkrácení na logické celky
text_splitter = RecursiveCharacterTextSplitter(chunk_size=4000, chunk_overlap=400)
all_documents = text_splitter.split_documents(md_header_splits)

# Odstranění pomocných sekcí (obsah, literatura) — neobsahují znalostní obsah
documents = []
for doc in all_documents:
    h1 = doc.metadata.get("Header 1", "").strip().lower()
    
    # Pokud je hlavní nadpis "obsah" nebo "literatura", chunk zahodit
    if "obsah" in h1 or "zdroje" in h1 or "literatura" in h1:
        continue
        
    documents.append(doc)

print(f"Původně vytvořeno: {len(all_documents)} chunků.")
print(f"Po vyhození Obsahu zbylo k analýze: {len(documents)} čistých chunků.")

Původně vytvořeno: 794 chunků.
Po vyhození Obsahu zbylo k analýze: 662 čistých chunků.

In [ ]:
def get_chunk_hash(text):
    return hashlib.md5(text.encode('utf-8')).hexdigest()

# Výpočet MD5 hashů pro všechny chunky aktuálního dokumentu
for doc in documents:
    doc.metadata["hash"] = get_chunk_hash(doc.page_content)

# Načtení existujících hashů z Neo4j a oprava chybějících záznamů
driver = GraphDatabase.driver(
    os.environ.get('NEO4J_URI'),
    auth=(os.environ.get('NEO4J_USERNAME'), os.environ.get('NEO4J_PASSWORD'))
)

with driver.session() as session:
    result = session.run("MATCH (d:Document) RETURN d.text AS text, d.hash AS hash")
    records = list(result)

    neo4j_hashes = set()
    updates = []

    for record in records:
        if record["hash"]:
            neo4j_hashes.add(record["hash"])
        elif record["text"]:
            # Hash chybí — dopočítá se ze zdrojového textu a zařadí do opravné dávky
            computed_hash = get_chunk_hash(record["text"])
            neo4j_hashes.add(computed_hash)
            updates.append({"text": record["text"], "hash": computed_hash})

    if updates:
        print(f"Oprava chybějících hashů: {len(updates)} dokumentů")
        session.run("""
        UNWIND $updates AS up
        MATCH (d:Document {text: up.text})
        SET d.hash = up.hash
        """, {"updates": updates})

# Odstranění zastaralých chunků z Neo4j (smazané nebo upravené části dokumentu)
current_hashes = {doc.metadata["hash"] for doc in documents}
obsolete_hashes = neo4j_hashes - current_hashes

if obsolete_hashes:
    print(f"Odstraňuji zastaralé chunky z Neo4j: {len(obsolete_hashes)}")
    with driver.session() as session:
        for obs_hash in obsolete_hashes:
            session.run("MATCH (d:Document {hash: $hash}) DETACH DELETE d", {"hash": obs_hash})
        # Odstranění osiřelých entit bez jakékoliv vazby
        session.run("""
        MATCH (e)
        WHERE (e:Hlavni_Pojem OR e:Proces_Cinnost OR e:Nastroj_System OR
               e:Metrika_Parametr OR e:Subjekt_Role OR e:Kapitola OR e:Podkapitola)
          AND NOT (e)--()
        DELETE e
        """)
    neo4j_hashes -= obsolete_hashes
    print("Zastaralé chunky a osiřelé entity odstraněny.")

driver.close()

# Načtení lokální PKL cache
local_cache = {}
if os.path.exists(cache_file):
    with open(cache_file, "rb") as f:
        local_cache = pickle.load(f)

# Synchronizace PKL cache s aktuálním stavem dokumentu
obsolete_pkl_hashes = set(local_cache.keys()) - current_hashes

if obsolete_pkl_hashes:
    print(f"Čištění PKL cache: {len(obsolete_pkl_hashes)} zastaralých záznamů")
    for obs_hash in obsolete_pkl_hashes:
        del local_cache[obs_hash]
    with open(cache_file, "wb") as f:
        pickle.dump(local_cache, f)

# Určení chunků vyžadujících LLM extrakci
missing_in_neo4j = [doc for doc in documents if doc.metadata.get("hash") not in neo4j_hashes]
docs_for_llm = [doc for doc in missing_in_neo4j if doc.metadata.get("hash") not in local_cache]

print(f"Chunky v dokumentu:   {len(documents)}")
print(f"Chunky v Neo4j:       {len(neo4j_hashes)}")
print(f"Chunky v PKL cache:   {len(local_cache)}")
print(f"Chunky ke zpracování: {len(docs_for_llm)}")

# LLM extrakce entit a vztahů — pouze pro chunky chybějící v obou úložištích
if docs_for_llm:
    print(f"Spouštím LLM extrakci: {len(docs_for_llm)} chunků")

    universal_nodes = ["Hlavni_Pojem", "Proces_Cinnost", "Nastroj_System", "Metrika_Parametr", "Subjekt_Role"]
    universal_relationships = ["SKLADA_SE_Z", "VYUZIVA", "MA_VLASTNOST", "PROVADI", "SOUVISI_S"]

    llm_transformer = LLMGraphTransformer(
        llm=llm, allowed_nodes=universal_nodes, allowed_relationships=universal_relationships
    )

    # Iterativní zpracování s průběžným ukládáním cache po každém chunku
    for i, doc in enumerate(docs_for_llm):
        doc_hash = doc.metadata["hash"]
        print(f"  {i+1}/{len(docs_for_llm)} (hash: {doc_hash[:8]})")
        try:
            extracted_graphs = llm_transformer.convert_to_graph_documents([doc])
            if extracted_graphs:
                local_cache[doc_hash] = extracted_graphs[0]
                with open(cache_file, "wb") as f:
                    pickle.dump(local_cache, f)
        except Exception as e:
            print(f"  Chyba u chunku {i+1}, přeskočeno: {e}")
            continue

    print("Extrakce dokončena.")
else:
    if missing_in_neo4j:
        print("Všechna chybějící data načtena z PKL cache, LLM extrakce není vyžadována.")
    else:
        print("Neo4j je aktuální, žádné zpracování není vyžadováno.")

# Příprava grafových dokumentů k nahrání do Neo4j
new_graph_documents = [
    local_cache[doc.metadata["hash"]]
    for doc in missing_in_neo4j
    if doc.metadata.get("hash") in local_cache
]

📊 Celkem chunků v textu: 662
🗄️ Z toho už je v Neo4j: 643
📁 Z toho už máme předpočítáno v PKL: 643
🔥 Bude se přes LLM reálně počítat: 1 chunků
⏳ Spouštím LLM extrakci pro 1 chunků...
  Zpracovávám 1/1 (Hash: 58233aa0)...
    ❌ Chyba při zpracování chunku 1 (přeskakuji): 'llama3.1:8b' did not respond with valid JSON.
                Please try again.
                Response: {
  "tool": "DynamicGraph",
  "tool_input": {
    "$defs": {
      "SimpleNode": [
        {
          "id": "Firemní kultura",
          "type": "Hlavni_Pojem"
        },
        {
          "id": "Metody řízení firmy",
          "type": "Proces_Cinnost"
        },
        {
          "id": "Podniková architektura",
          "type": "Nastroj_System"
        },
        {
          "id": "Podniková organizace",
          "type": "Subjekt_Role"
        },
        {
          "id": "Dislokace podniku",
          "type": "Metrika_Parametr"
        },
        {
          "id": "Úroveň podnikových procesů",
          "type": "Proces_Cinnost"
        },
        {
          "id": "Reengineering procesů",
          "type": "Nastroj_System"
        },
        {
          "id": "Kvalita personálních zdrojů",
          "type": "Metrika_Parametr"
        }
      ],
      "SimpleRelationship": [
        {
          "source_node_id": "Firemní kultura",
          "source_node_type": "Hlavni_Pojem",
          "target_node_id": "Metody řízení firmy",
          "target_node_type": "Proces_Cinnost",
          "type": "SKLADA_SE_Z"
        },
        {
          "source_node_id": "Firemní kultura",
          "source_node_type": "Hlavni_Pojem",
          "target_node_id": "Podniková architektura",
          "target_node_type": "Nastroj_System",
          "type": "SKLADA_SE_Z"
        },
        {
          "source_node_id": "Firemní kultura",
          "source_node_type": "Hlavni_Pojem",
          "target_node_id": "Podniková organizace",
          "target_node_type": "Subjekt_Role",
          "type": "SKLADA_SE_Z"
        },
        {
          "source_node_id": "Firemní kultura",
          "source_node_type": "Hlavni_Pojem",
          "target_node_id": "Dislokace podniku",
          "target_node_type": "Metrika_Parametr",
          "type": "SKLADA_SE_Z"
        },
        {
          "source_node_id": "Firemní kultura",
          "source_node_type": "Hlavni_Pojem",
          "target_node_id": "Úroveň podnikových procesů",
          "target_node_type": "Proces_Cinnost",
          "type": "SKLADA_SE_Z"
        },
        {
          "source_node_id": "Firemní kultura",
          "source_node_type": "Hlavni_Pojem",
          "target_node_id": "Reengineering procesů",
          "target_node_type": "Nastroj_System",
          "type": "SKLADA_SE_Z"
        },
        {
          "source_node_id": "Firemní kultura",
          "source_node_type": "Hlavni_Pojem",
          "target_node_id": "Kvalita personálních zdrojů",
          "target_node_type": "Metrika_Parametr",
          "type": "SKLADA_SE_Z"
        },
        {
          "source_node_id": "Metody řízení firmy",
          "source_node_type": "Proces_Cinnost",
          "target_node_id": "Podniková architektura",
          "target_node_type": "Nastroj_System",
          "type": "VYUZIVA"
        },
        {
          "source_node_id": "Metody řízení firmy",
          "source_node_type": "Proces_Cinnost",
          "target_node_id": "Podniková organizace",
          "target_node_type": "Subjekt_Role",
          "type": "VYUZIVA"
        },
        {
          "source_node_id": "Metody řízení firmy",
          "source_node_type": "Proces_Cinnost",
          "target_node_id": "Dislokace podniku",
          "target_node_type": "Metrika_Parametr",
          "type": "VYUZIVA"
        },
        {
          "source_node_id": "Metody řízení firmy",
          "source_node_type": "Proces_Cinnost",
          "target_node_id": "Úroveň podnikových procesů",
          "target_node_type": "Proces_Cinnost",
          "type": "VYUZIVA"
        },
        {
          "source_node_id": "Metody řízení firmy",
          "source_node_type": "Proces_Cinnost",
          "target_node_id": "Reengineering procesů",
          "target_node_type": "Nastroj_System",
          "type": "VYUZIVA"
        },
        {
          "source_node_id": "Metody řízení firmy",
          "source_node_type": "Proces_Cinnost",
          "target_node_id": "Kvalita personálních zdrojů",
          "target_node_type": "Metrika_Parametr",
          "type": "VYUZIVA"
        },
        {
          "source_node_id": "Podniková architektura",
          "source_node_type": "Nastroj_System",
          "target_node_id": "Podniková organizace",
          "target_node_type": "Subjekt_Role",
          "type": "VYUZIVA"
        },
        {
          "source_node_id": "Podniková architektura",
          "source_node_type": "Nastroj_System",
          "target_node_id": "Dislokace podniku",
          "target_node_type": "Metrika_Parametr",
          "type": "VYUZIVA"
        },
        {
          "source_node_id": "Podniková architektura",
          "source_node_type": "Nastroj_System",
          "target_node_id": "Úroveň podnikových procesů",
          "target_node_type": "Proces_Cinnost",
          "type": "VYUZIVA"
        },
        {
          "source_node_id": "Podniková architektura",
          "source_node_type": "Nastroj_System",
          "target_node_id": "Reengineering procesů",
          "target_node_type": "Nastroj_System",
          "type": "VYUZIVA"
        },
        {
          "source_node_id": "Podniková architektura",
          "source_node_type": "Nastroj_System",
          "target_node_id": "Kvalita personálních zdrojů",
          "target_node_type": "Metrika_Parametr",
          "type": "VYUZIVA"
        },
        {
          "source_node_id": "Podniková organizace",
          "source_node_type": "Subjekt_Role",
          "target_node_id": "Dislokace podniku",
          "target_node_type": "Metrika_Parametr",
          "type": "VYUZIVA"
        },
        {
          "source_node_id": "Podniková organizace",
          "source_node_type": "Subjekt_Role",
          "target_node_id": "Úroveň podnikových procesů",
          "target_node_type": "Proces_Cinnost",
          "type": "VYUZIVA"
        },
        {
          "source_node_id": "Podniková organizace",
          "source_node_type": "Subjekt_Role",
          "target_node_id": "Reengineering procesů",
          "target_node_type": "Nastroj_System",
          "type": "VYUZIVA"
        },
        {
          "source_node_id": "Podniková organizace",
          "source_node_type": "Subjekt_Role",
          "target_node_id": "Kvalita personálních zdrojů",
          "target_node_type": "Metrika_Parametr",
          "type": "VYUZIVA"
        },
        {
          "source_node_id": "Dislokace podniku",
          "source_node_type": "Metrika_Parametr",
          "target_node_id": "Úroveň podnikových procesů",
          "target_node_type": "Proces_Cinnost",
          "type": "VYUZIVA"
        },
        {
          "source_node_id": "Dislokace podniku",
          "source_node_type": "Metrika_Parametr",
          "target_node_id": "Reengineering procesů",
          "target_node_type": "Nastroj_System",
          "type": "VYUZIVA"
        },
        {
          "source_node_id": "Dislokace podniku",
          "source_node_type": "Metrika_Parametr",
          "target_node_id": "Kvalita personálních zdrojů",
          "target_node_type": "Metrika_Parametr",
          "type": "VYUZIVA"
        },
        {
          "source_node_id": "Úroveň podnikových procesů",
          "source_node_type": "Proces_Cinnost",
          "target_node_id": "Reengineering procesů",
          "target_node_type": "Nastroj_System",
          "type": "VYUZIVA"
        },
        {
          "source_node_id": "Úroveň podnikových procesů",
          "source_node_type": "Proces_Cinnost",
          "target_node_id": "Kvalita personálních zdrojů",
          "target_node_type": "Metrika_Parametr",
          "type": "VYUZIVA"
        },
        {
          "source_node_id": "Reengineering procesů",
          "source_node_type": "Nastroj_System",
          "target_node_id": "Kvalita personálních zdrojů",
          "target_node_type": "Metrika_Parametr",
          "type": "VYUZIVA"
        }
      ]
    },
    "nodes": [
      {
        "id": "Firemní kultura",
        "type": "Hlavni_Pojem"
      },
      {
        "id": "Metody řízení firmy",
        "type": "Proces_Cinnost"
      },
      {
        "id": "Podniková architektura",
        "type": "Nastroj_System"
      },
      {
        "id": "Podniková organizace",
        "type": "Subjekt_Role"
      },
      {
        "id": "Dislokace podniku",
        "type": "Metrika_Parametr"
      },
      {
        "id": "Úroveň podnikových procesů",
        "type": "Proces_Cinnost"
      },
      {
        "id": "Reengineering procesů",
        "type": "Nastroj_System"
      },
      {
        "id": "Kvalita personálních zdrojů",
        "type": "Metrika_Parametr"
      }
    ],
    "relationships": [
      {
        "source_node_id": "Firemní kultura",
        "source_node_type": "Hlavni_Pojem",
        "target_node_id": "Metody řízení firmy",
        "target_node_type": "Proces_Cinnost",
        "type": "SKLADA_SE_Z"
      },
      {
        "source_node_id": "Firemní kultura",
        "source_node_type": "Hlavni_Pojem",
        "target_node_id": "Podniková architektura",
        "target_node_type": "Nastroj_System",
        "type": "SKLADA_SE_Z"
      },
      {
        "source_node_id": "Firemní kultura",
        "source_node_type": "Hlavni_Pojem",
        "target_node_id": "Podniková organizace",
        "target_node_type": "Subjekt_Role",
        "type": "SKLADA_SE_Z"
      },
      {
        "source_node_id": "Firemní kultura",
        "source_node_type": "Hlavni_Pojem",
        "target_node_id": "Dislokace podniku",
        "target_node_type": "Metrika_Parametr",
        "type": "SKLADA_SE_Z"
      },
      {
        "source_node_id": "Firemní kultura",
        "source_node_type": "Hlavni_Pojem",
        "target_node_id": "Úroveň podnikových procesů",
        "target_node_type": "Proces_Cinnost",
        "type": "SKLADA_SE_Z"
      },
      {
        "source_node_id": "Firemní kultura",
        "source_node_type": "Hlavni_Pojem",
        "target_node_id": "Reengineering procesů",
        "target_node_type": "Nastroj_System",
        "type": "SKLADA_SE_Z"
      },
      {
        "source_node_id": "Firemní kultura",
        "source_node_type": "Hlavni_Pojem",
        "target_node_id": "Kvalita personálních zdrojů",
        "target_node_type": "Metrika_Parametr",
        "type": "SKLADA_SE_Z"
      },
      {
        "source_node_id": "Metody řízení firmy",
        "source_node_type": "Proces_Cinnost",
        "target_node_id": "Podniková architektura",
        "target_node_type": "Nastroj_System",
        "type": "VYUZIVA"
      },
      {
        "source_node_id": "Metody řízení firmy",
        "source_node_type": "Proces_Cinnost",
        "target_node_id": "Podniková organizace",
        "target_node_type": "Subjekt_Role",
        "type": "VYUZIVA"
      },
      {
        "source_node_id": "Metody řízení firmy",
        "source_node_type": "Proces_Cinnost",
        "target_node_id": "Dislokace podniku",
        "target_node_type": "Metrika_Parametr",
        "type": "VYUZIVA"
      },
      {
        "source_node_id": "Metody řízení firmy",
        "source_node_type": "Proces_Cinnost",
        "target_node_id": "Úroveň podnikových procesů",
        "target_node_type": "Proces_Cinnost",
        "type": "VYUZIVA"
      },
      {
        "source_node_id": "Metody řízení firmy",
        "source_node_type": "Proces_Cinnost",
        "target_node_id": "Reengineering procesů",
        "target_node_type": "Nastroj_System",
        "type": "VYUZIVA"
      },
      {
        "source_node_id": "Metody řízení firmy",
        "source_node_type": "Proces_Cinnost",
        "target_node_id": "Kvalita personálních zdrojů",
        "target_node_type": "Metrika_Parametr",
        "type": "VYUZIVA"
      },
      {
        "source_node_id": "Podniková architektura",
        "source_node_type": "Nastroj_System",
        "target_node_id": "Podniková organizace",
        "target_node_type": "Subjekt_Role",
        "type": "VYUZIVA"
      },
      {
        "source_node_id": "Podniková architektura",
        "source_node_type": "Nastroj_System",
        "target_node_id": "Dislokace podniku",
        "target_node_type": "Metrika_Parametr",
        "type": "VYUZIVA"
      },
      {
        "source_node_id": "Podniková architektura",
        "source_node_type": "Nastroj_System",
        "target_node_id": "Úroveň podnikových procesů",
        "target_node_type": "Proces_Cinnost",
        "type": "VYUZIVA"
      },
      {
        "source_node_id": "Podniková architektura",
        "source_node_type": "Nastroj_System",
        "target_node_id": "Reengineering procesů",
        "target_node_type": "Nastroj_System",
        "type": "VYUZIVA"
      },
      {
        "source_node_id": "Podniková architektura",
        "source_node_type": "Nastroj_System",
        "target_node_id": "Kvalita personálních zdrojů",
        "target_node_type": "Metrika_Parametr",
        "type": "VYUZIVA"
      },
      {
        "source_node_id": "Podniková organizace",
        "source_node_type": "Subjekt_Role",
        "target_node_id": "Dislokace podniku",
        "target_node_type": "Metrika_Parametr",
        "type": "VYUZIVA"
      },
      {
        "source_node_id": "Podniková organizace",
        "source_node_type": "Subjekt_Role",
        "target_node_id": "Úroveň podnikových procesů",
        "target_node_type": "Proces_Cinnost",
        "type": "VYUZIVA"
      },
      {
        "source_node_id": "Podniková organizace",
        "source_node_type": "Subjekt_Role",
        "target_node_id": "Reengineering procesů",
        "target_node_type": "Nastroj_System",
        "type": "VYUZIVA"
      },
      {
        "source_node_id": "Podniková organizace",
        "source_node_type": "Subjekt_Role",
        "target_node_id": "Kvalita personálních zdrojů",
        "target_node_type": "Metrika_Parametr",
        "type": "VYUZIVA"
      },
      {
        "source_node_id": "Dislokace podniku",
        "source_node_type": "Metrika_Parametr",
        "target_node_id": "Úroveň podnikových procesů",
        "target_node_type": "Proces_Cinnost",
        "type": "VYUZIVA"
      },
      {
        "source_node_id": "Dislokace podniku",
        "source_node_type": "Metrika_Parametr",
        "target_node_id": "Reengineering procesů",
        "target_node_type": "Nastroj_System",
        "type": "VYUZIVA"
      },
      {
        "source_node_id": "Dislokace podniku",
        "source_node_type": "Metrika_Parametr",
        "target_node_id": "Kvalita personálních zdrojů",
        "target_node_type": "Metrika_Parametr",
        "type": "VYUZIVA"
      },
      {
        "source_node_id": "Úroveň podnikových procesů",
        "source_node_type": "Proces_Cinnost",
        "target_node_id": "Reengineering procesů",
        "target_node_type": "Nastroj_System",
        "type": "VYUZIVA"
      },
      {
        "source_node_id": "Úroveň podnikových procesů",
        "source_node_type": "Proces_Cinnost",
        "target_node_id": "Kvalita personálních
✅ Extrakce dokončena. Lokální záloha (PKL) je aktuální.

In [ ]:
# Nahrání extrahovaných grafových dokumentů do Neo4j
if new_graph_documents:
    print(f"Nahrávám {len(new_graph_documents)} dokumentů do Neo4j...")
    graph.add_graph_documents(
        new_graph_documents,
        baseEntityLabel=True,
        include_source=True  # Vytvoří uzel Document propojený s extrahovanými entitami
    )
    print("Nahrání dokončeno.")
else:
    print("Neo4j je aktuální, žádné nové dokumenty k nahrání.")

# Sestavení hierarchie kapitol z metadat chunků
print("Sestavuji stromovou strukturu kapitol...")

driver = GraphDatabase.driver(
    os.environ.get('NEO4J_URI'),
    auth=(os.environ.get('NEO4J_USERNAME'), os.environ.get('NEO4J_PASSWORD'))
)

with driver.session() as session:
    for doc in documents:
        chunk_hash = doc.metadata.get("hash")

        # Sestavení cesty nadpisů H1–H6 pro daný chunk
        # Složené path_id zajišťuje jedinečnost podkapitol se stejným názvem napříč kapitolami
        path_nodes = []
        current_path_id = ""

        for i in range(1, 7):
            h = doc.metadata.get(f"Header {i}")
            if h:
                current_path_id = f"{current_path_id} | {h}" if current_path_id else h
                path_nodes.append({"id": current_path_id, "name": h, "level": i})

        if not path_nodes:
            path_nodes = [{"id": "Obecné", "name": "Obecné", "level": 1}]

        # Vytvoření uzlů Kapitola a propojení do stromové hierarchie
        for i, item in enumerate(path_nodes):
            session.run(
                """
                MERGE (k:Kapitola {id: $id})
                SET k.nazev = $name, k.uroven = $level
                """,
                {"id": item["id"], "name": item["name"], "level": item["level"]}
            )

            # Propojení podkapitoly s nadřazenou kapitolou
            if i > 0:
                parent_item = path_nodes[i - 1]
                session.run(
                    """
                    MATCH (parent:Kapitola {id: $parent_id})
                    MATCH (child:Kapitola {id: $child_id})
                    MERGE (parent)-[:OBSAHUJE_PODKAPITOLU]->(child)
                    """,
                    {"parent_id": parent_item["id"], "child_id": item["id"]}
                )

        # Propojení nejhlubšího uzlu hierarchie s textovým chunkem
        leaf_item = path_nodes[-1]
        session.run(
            """
            MATCH (d:Document {hash: $hash})
            MATCH (k:Kapitola {id: $leaf_id})
            MERGE (k)-[:OBSAHUJE_TEXT]->(d)
            """,
            {"hash": chunk_hash, "leaf_id": leaf_item["id"]}
        )

driver.close()
print("Hierarchie kapitol sestavena.")

✅ Znalosti v Neo4j jsou stoprocentně aktuální, není co přidávat.
⏳ Buduji pevnou stromovou strukturu kapitol z metadat...
✅ Hierarchie kapitol byla úspěšně vygenerována a propojena s texty a entitami!

In [ ]:
# Inicializace embeddingového modelu
embeddings = OllamaEmbeddings(
    model="nomic-embed-text",
    num_ctx=8192  # Maximální kontextové okno modelu nomic-embed-text
)

# Vytvoření hybridního vektorového indexu nad uzly Document
try:
    vector_index = Neo4jVector.from_existing_graph(
        embeddings,
        search_type="hybrid",
        node_label="Document",
        text_node_properties=["text"],
        embedding_node_property="embedding"
    )
    vector_retriever = vector_index.as_retriever(search_kwargs={"k": 10})
    print("Vektorový index vytvořen.")
except Exception as e:
    print(f"Chyba při vytváření vektorového indexu: {e}")

# Vytvoření fulltextového indexu nad entitami a kapitolami
def create_fulltext_index():
    driver = GraphDatabase.driver(
        os.environ['NEO4J_URI'],
        auth=(os.environ['NEO4J_USERNAME'], os.environ['NEO4J_PASSWORD'])
    )
    with driver.session() as session:
        # Znovuvytvoření indexu — zajišťuje konzistenci při opakovaném spuštění
        session.run("DROP INDEX fulltext_entity_id IF EXISTS")
        session.run("""
        CREATE FULLTEXT INDEX fulltext_entity_id IF NOT EXISTS
        FOR (n:__Entity__|Kapitola|Podkapitola)
        ON EACH [n.id, n.nazev]
        """)
    driver.close()

create_fulltext_index()
print("Fulltextový index nad entitami a kapitolami vytvořen.")

✅ Vektorový index úspěšně vytvořen s max. kontextem.
✅ Fulltextový index pokrývající entity i kapitoly je připraven.

In [ ]:
# Inicializace embeddingového modelu pro manuální indexaci
embeddings_model = OllamaEmbeddings(
    model="nomic-embed-text",
    num_ctx=8192  # Maximální kontextové okno modelu nomic-embed-text
)

driver = GraphDatabase.driver(
    os.environ['NEO4J_URI'],
    auth=(os.environ['NEO4J_USERNAME'], os.environ['NEO4J_PASSWORD'])
)

def build_vector_index():
    with driver.session() as session:
        # Odstranění stávajícího indexu před znovuvytvořením
        session.run("DROP INDEX vector IF EXISTS")

        # Načtení uzlů Document bez embeddingu
        result = session.run(
            "MATCH (d:Document) WHERE d.embedding IS NULL RETURN d.id as id, d.text as text"
        )
        nodes = [{"id": r["id"], "text": r["text"]} for r in result]

        print(f"Uzly ke zpracování: {len(nodes)}")

        for i, node in enumerate(nodes):
            try:
                # Text oříznut na 8 000 znaků
                safe_text = node["text"][:8000]
                vector = embeddings_model.embed_query(safe_text)
                session.run(
                    "MATCH (d:Document {id: $id}) SET d.embedding = $vector",
                    {"id": node["id"], "vector": vector}
                )
                if (i + 1) % 10 == 0:
                    print(f"  Zpracováno {i+1}/{len(nodes)}")
            except Exception as e:
                print(f"  Chyba u uzlu {node['id']}: {e}")

        # Vytvoření vektorového indexu nad existujícími embeddingy
        session.run("""
            CREATE VECTOR INDEX vector IF NOT EXISTS
            FOR (m:Document) ON (m.embedding)
            OPTIONS {indexConfig: {
              `vector.dimensions`: 768,
              `vector.similarity_function`: 'cosine'
            }}
        """)
        print("Vektorový index vytvořen.")

build_vector_index()
driver.close()

🧹 Starý index smazán.
📦 Nalezeno 0 dokumentů v DB. Spouštím individuální embedding...
✅ Vektorový index úspěšně vytvořen manuálně.

In [ ]:
# Dense retriever — kosinová podobnost (baseline Naive RAG)
neo4j_dense_index = Neo4jVector.from_existing_index(
    embeddings,
    index_name="vector",
    search_type="vector",
    node_label="Document",
    text_node_property="text"
)
dense_retriever = neo4j_dense_index.as_retriever(search_kwargs={"k": 20})

# Hybridní retriever — kosinová podobnost + BM25 (Hybrid GraphRAG)
neo4j_hybrid_index = Neo4jVector.from_existing_index(
    embeddings,
    index_name="vector",
    search_type="hybrid",
    keyword_index_name="keyword",
    node_label="Document",
    text_node_property="text"
)
hybrid_retriever = neo4j_hybrid_index.as_retriever(search_kwargs={"k": 20})

print("dense_retriever  — search_type=vector")
print("hybrid_retriever — search_type=hybrid")

✅ dense_retriever  — search_type=vector (Naive RAG)
✅ hybrid_retriever — search_type=hybrid (Hybrid GraphRAG)

In [ ]:
# Schéma pro strukturovaný výstup extrakce entit
class Entities(BaseModel):
    """Informace o klíčových entitách a pojmech v textu."""
    names: list[str] = Field(
        ...,
        description="Všechny klíčové pojmy, technické termíny, procesy a funkce. ZÁSADNÍ: Nesekej víceslovná spojení (např. 'funkce prediktivní analytiky', 'řízení dopravy') na jednotlivá slova!",
    )

# Inicializace modelů
# llm_extraction bez num_predict — parametr je relevantní pouze pro LLMGraphTransformer
# llm_rag s rozšířeným kontextem num_ctx=32768 pro zpracování dlouhého retrieval kontextu
llm_extraction = OllamaFunctions(model="llama3.1:8b", temperature=0, format="json")
llm_rag = ChatOllama(
    model="llama3.1:8b",
    temperature=0,
    num_ctx=32768
)

# Few-shot prompt pro extrakci entit z uživatelského dotazu
extraction_prompt = ChatPromptTemplate.from_messages([
    ("system", """Jsi expert na extrakci klíčových pojmů z odborných dotazů pro vyhledávání v databázi.
Tvým úkolem je z uživatelské otázky vyextrahovat hlavní entity.

ZÁSADNÍ PRAVIDLO: Odborné pojmy, víceslovné názvy, vlastnosti, metriky nebo procesy ponechávej v celku! Nesekej ustálená spojení na jednotlivá slova.

PŘÍKLADY SPRÁVNÉHO CHOVÁNÍ:
Otázka: "Co je to sekvenční diagram?"
Entity: ["sekvenční diagram"]

Otázka: "Jaké jsou fáze buněčného dělení v biologii?"
Entity: ["fáze buněčného dělení", "biologie"]

Otázka: "Co patří pod funkce prediktivní analytiky v marketingu?"
Entity: ["funkce prediktivní analytiky v marketingu"]

Otázka: "Jaké jsou výhody agilního řízení projektů?"
Entity: ["výhody agilního řízení projektů"]
"""),
    ("human", "{question}")
])

# Extrakční pipeline s validací výstupu přes Pydantic schéma
entity_chain = extraction_prompt | llm_extraction.with_structured_output(Entities)

In [ ]:
def graph_enhanced_retriever(question: str):
    try:
        entities = entity_chain.invoke({"question": question})
        print(f"Extrahované entity: {entities.names}")

        all_documents = []
        seen_docs = set()
        search_queries = []

        relations_text = ""
        seen_relations = set()

        # Sestavení Lucene dotazů z extrahovaných entit
        for entity in entities.names:
            words = [w.lower() for w in entity.split() if len(w) >= 3]
            if words:
                lucene_query = " AND ".join([f"*{w[:5]}*" for w in words])
                search_queries.append(lucene_query)

        # Doplňkový dotaz sestavený přímo ze slov otázky
        question_words = [w.lower() for w in re.findall(r'\w+', question) if len(w) >= 3]
        if question_words:
            direct_query = " OR ".join([f"*{w[:5]}*" for w in question_words])
            search_queries.append(direct_query)

        search_queries = list(set(search_queries))

        for lucene_query in search_queries:
            printed_nodes = set()

            
            response = graph.query(
                """
                CALL db.index.fulltext.queryNodes('fulltext_entity_id', $lucene_query, {limit: 5})
                YIELD node

                // Traversal dolů pouze pro listové uzly bez přímých podkapitol
                OPTIONAL MATCH (node)-[:OBSAHUJE_PODKAPITOLU]->(direct_child)
                WITH node, count(direct_child) AS child_count

                OPTIONAL MATCH (node)-[:OBSAHUJE_PODKAPITOLU*1..5]->(sub_k)
                    WHERE child_count = 0

                // Traversal nahoru zachytí preamble chunky na úrovni H1
                OPTIONAL MATCH (parent_k:Kapitola)-[:OBSAHUJE_PODKAPITOLU*1..3]->(node)

                WITH node,
                     collect(DISTINCT sub_k) + [node] + collect(DISTINCT parent_k) AS all_nodes
                UNWIND all_nodes AS search_node

                MATCH (doc:Document)
                WHERE (doc)-[:MENTIONS]->(search_node) OR (search_node)-[:OBSAHUJE_TEXT]->(doc)

                OPTIONAL MATCH (doc)-[:MENTIONS]->(kapitola_entity:__Entity__)
                WHERE labels(node)[0] = 'Kapitola'

                OPTIONAL MATCH (node)-[r]-(neighbor)
                WHERE type(r) <> 'MENTIONS' AND type(r) <> 'OBSAHUJE_TEXT' AND type(r) <> 'OBSAHUJE_PODKAPITOLU'

                RETURN DISTINCT
                    node.id AS entity_name,
                    labels(node)[0] AS node_type,
                    type(r) AS relation,
                    neighbor.id AS related_entity,
                    kapitola_entity.id AS podrizena_entita,
                    doc.text AS source_doc
                LIMIT 50
                """,
                {"lucene_query": lucene_query}
            )

            for r in response:
                node_name = r.get('entity_name')
                node_type = r.get('node_type', 'neznámý typ')
                rel = r.get('relation')
                neighbor = r.get('related_entity')
                podrizena_entita = r.get('podrizena_entita')

                if node_name not in printed_nodes:
                    print(f"  Nalezen uzel [{node_type}]: '{node_name}'")
                    printed_nodes.add(node_name)

                if rel and neighbor:
                    rel_str = f"Položka '{neighbor}' (vztah ke '{node_name}': {rel})"
                    if rel_str not in seen_relations:
                        relations_text += f"- {rel_str}\n"
                        seen_relations.add(rel_str)

                if podrizena_entita:
                    sub_ent_str = f"Kapitola '{node_name}' obsahuje entitu: '{podrizena_entita}'"
                    if sub_ent_str not in seen_relations:
                        relations_text += f"- {sub_ent_str}\n"
                        seen_relations.add(sub_ent_str)

                doc = r.get('source_doc')
                if doc and doc not in seen_docs and len(doc) > 100:
                    all_documents.append(doc)
                    seen_docs.add(doc)

        print(f"Nalezeno dokumentů z grafu: {len(all_documents)}")
        return relations_text, all_documents

    except Exception as e:
        print(f"Chyba v grafovém retrieveru: {e}")
        return "", []

In [ ]:
# Cross-encoder reranker pro přeřazení dokumentů podle relevance k dotazu
# Použit multilingvální model trénovaný na datasetu mMARCO (včetně češtiny)
try:
    from sentence_transformers import CrossEncoder
    reranker = CrossEncoder("cross-encoder/mmarco-mMiniLMv2-L12-H384-v1")
    RERANKER_AVAILABLE = True
    print("Cross-encoder načten: mmarco-mMiniLMv2-L12-H384-v1")
except ImportError:
    RERANKER_AVAILABLE = False
    print("sentence-transformers neni dostupne, reranking preskocen")


def rerank_docs(question: str, docs, top_k: int = 10, label: str = ""):
    if not docs or not RERANKER_AVAILABLE:
        return docs[:top_k]

    # Podpora pro Document objekty i prosté řetězce
    texts = [doc.page_content if hasattr(doc, "page_content") else doc for doc in docs]
    pairs = [(question, text) for text in texts]
    scores = reranker.predict(pairs)
    ranked = sorted(zip(scores, docs), key=lambda x: x[0], reverse=True)

    print(f"  Reranking {label}({len(docs)} dokumentů → top {top_k}):")
    print(f"  {'Pořadí':<7} {'Skóre':>7}  Náhled")
    print("  " + "-" * 70)
    for rank_i, (score, doc) in enumerate(ranked, 1):
        text = doc.page_content if hasattr(doc, "page_content") else doc
        preview = text[:120].replace("\n", " ")
        marker = "+" if rank_i <= top_k else "-"
        print(f"  {marker} #{rank_i:<3} {score:>7.3f}  {preview}...")
    print()

    return [doc for _, doc in ranked[:top_k]]

✅ Multilingual cross-encoder načten: mmarco-mMiniLMv2-L12-H384-v1
   Podporuje češtinu (trénováno na mMARCO multilingválním datasetu).

In [ ]:
def full_retriever(question: str):
    # Vektorové vyhledávání — hybridní retriever (kosinová podobnost + BM25, k=20)
    vector_docs = hybrid_retriever.invoke(question)
    print(f"Vektorové vyhledávání: {len(vector_docs)} dokumentů")
    print("-" * 60)
    for i, doc in enumerate(vector_docs):
        meta = {k: v for k, v in doc.metadata.items() if k != "hash" and v}
        meta_str = " | ".join(str(v) for v in meta.values()) if meta else "(bez metadat)"
        preview = doc.page_content[:200].replace("\n", " ")
        print(f"  [{i+1}] {meta_str}")
        print(f"        {preview}...")
    print("-" * 60)

    graph_relations_text, graph_docs_list = graph_enhanced_retriever(question)
    print(f"Grafové vyhledávání: {len(graph_docs_list)} dokumentů")
    print("-" * 60)
    for i, doc_text in enumerate(graph_docs_list):
        preview = doc_text[:200].replace("\n", " ")
        print(f"  [{i+1}] {preview}...")
    print("-" * 60)

    reranked_vector = rerank_docs(question, vector_docs, top_k=10, label="[vector] ")
    reranked_graph = rerank_docs(question, graph_docs_list, top_k=10, label="[graph] ") if graph_docs_list else []

    # Výpis finálního pořadí dokumentů předaných LLM
    print("Finální pořadí — vektorové dokumenty:")
    print("  " + "-" * 70)
    for rank_i, doc in enumerate(reranked_vector, 1):
        text = doc.page_content if hasattr(doc, "page_content") else doc
        meta = {k: v for k, v in doc.metadata.items() if k != "hash" and v} if hasattr(doc, "metadata") else {}
        meta_str = " | ".join(str(v) for v in meta.values()) if meta else "(bez metadat)"
        preview = text[:150].replace("\n", " ")
        print(f"  #{rank_i:<3} {meta_str}")
        print(f"        {preview}...")
    print()

    if reranked_graph:
        print("Finální pořadí — grafové dokumenty:")
        print("  " + "-" * 70)
        for rank_i, doc in enumerate(reranked_graph, 1):
            text = doc.page_content if hasattr(doc, "page_content") else doc
            preview = text[:150].replace("\n", " ")
            print(f"  #{rank_i:<3} {preview}...")
        print()

    vector_text = "\n\n".join(
        doc.page_content if hasattr(doc, "page_content") else doc
        for doc in reranked_vector
    )
    graph_text = "\n\n".join(reranked_graph)

    # Ořez kontextu — llama3.1:8b spolehlivě zpracuje přibližně 10 000 znaků
    graph_text_trimmed  = graph_text[:8000]
    vector_text_trimmed = vector_text[:3000]
    graph_rel_trimmed   = graph_relations_text[:1500]

    # Grafové dokumenty jsou primárním zdrojem — řazeny na první pozici v kontextu
    context = (
        f"### 1. DOKUMENTY Z GRAFU (PRIMÁRNÍ ZDROJ - ČTĚTE CELÉ, ODPOVĚĎ JE ZDE):\n{graph_text_trimmed}"
        f"\n\n### 2. VEKTOROVÉ DOKUMENTY (Doplňující textový kontext):\n{vector_text_trimmed}"
        f"\n\n### 3. VZTAHY Z GRAFU (Strukturální kontext):\n{graph_rel_trimmed}"
    )

    # Náhled kontextu odeslaného do LLM
    char_count = len(context)
    sep = "=" * 70
    print(f"Kontext odeslaný do LLM ({char_count:,} znaků):")
    print(sep)
    print("[Sekce 1 — grafové dokumenty]")
    print(graph_text_trimmed[:800].replace("\n\n", "\n") + ("…" if len(graph_text_trimmed) > 800 else ""))
    print()
    print("[Sekce 2 — vektorové dokumenty]")
    print(vector_text_trimmed[:800].replace("\n\n", "\n") + ("…" if len(vector_text_trimmed) > 800 else ""))
    print()
    print("[Sekce 3 — vztahy z grafu]")
    print(graph_rel_trimmed[:800] + ("…" if len(graph_rel_trimmed) > 800 else ""))
    print(sep)

    return context

In [ ]:
template = """

Jsi expertní analytický systém pracující s technickou dokumentací.

### KRITICKÁ PRAVIDLA:
1. ODPOVÍDEJ POUZE NA ZÁKLADĚ DODANÉHO KONTEXTU.
2. Pro výčty použij odrážkový seznam, pro definice odstavce.
3. KOMPLETNÍ VÝČET BEZ ZKRACOVÁNÍ — žádné "a další", "apod.", "atd.".

### KONTEXT:
{context}

### OTÁZKA:
{question}


### ODPOVĚĎ:"""

prompt = ChatPromptTemplate.from_template(template)

# Sestavení RAG chain: retrieval → prompt → LLM → parsování výstupu
chain = (
    {"context": full_retriever, "question": RunnablePassthrough()}
    | prompt
    | llm_rag
    | StrOutputParser()
)

print("RAG chain připraven.")

✅ RAG chain s přísným promptem vytvořen!

### Rychlý test pipeline
Otázku pro ověření, že vše funguje.

In [59]:
print(chain.invoke("Jake jsou klíčové aktivity v evidenci TPV?"))

--- HLEDÁM ODPOVĚĎ NA: 'Jake jsou klíčové aktivity v evidenci TPV?' ---

📚 VEKTOROVÉ VYHLEDÁVÁNÍ — nalezeno 20 dokumentů (před rerankingem):
------------------------------------------------------------
  [1] 📂 11.1 Přehled a obsah úloh řízení majetku | 11. Řízení majetku | 11.1.1 Evidence majetku
       💬 Účelem je aktualizace základních údajů majetkových databází, klasifikace majetku, technických údajů apod. (viz další obrázek).   *Obrázek 11-2: Evidence majetku*   **Zajišťuje tyto klíčové aktivity :*...
  [2] 📂 17.1 Přehled a obsah úloh OŘV | 17. Operativní řízení výroby, OŘV | 17.1.1 OŘV: Operativní evidence výroby
       💬 Účelem je vytvářet a zajistit průběžnou operativní evidenci o výrobě, a to (viz další obrázek):   - evidenci plánované a realizované výroby v kusech, - spotřebu normohodin, - spotřebu materiálu, - sor...
  [3] 📂 17.2 OŘV v kontextu řízení firmy | 17. Operativní řízení výroby, OŘV | 17.2.1 Vstupy do OŘV
       💬 Podstatné vstupy do operativního řízení výroby z ostatních oblastí řízení jsou uvedeny v dalším přehledu:   **Plánování výrobních zakázek:**   - Plán výrobních zakázek, Plánovací sešit výroby, Monitor...
  [4] 📂 5.2 Řízení práce a mezd v kontextu řízení firmy | 5. Řízení práce a mezd, PAM | 5.2.2 Výstupy z řízení práce a mezd
       💬 Jako podstatné výstupy z řízení práce a mezd jsou:   Finanční řízení, Řízení lidských zdrojů, IT:   - mzdové výkazy a analýzy, mzdové plány: - představují vstupy pro komplexní analýzy a plány finanční...
  [5] 📂 15.7 Faktory v plánování a koordinace výrobních zakázek | 15. Plánování a koordinace výrobních zakázek
       💬 Kapitola obsahuje pouze vybrané faktory , které ovlivňují plánování a koordinaci zakázek ve strojírenské firmě.  Detailněji: dokument: [Strojírenství: Faktory  ]. Dále uvedené faktory, které jsou rele...
  [6] 📂 16.7 Faktory podstatné pro TPV | 16. Technická příprava, výroby, TPV
       💬 Kapitola obsahuje pouze vybrané faktory , které ovlivňují technickou přípravu výroby ve strojírenské firmě.  Detailněji: dokument: [Strojírenství: Faktory  ]. Dále uvedené faktory, které jsou relevant...
  [7] 📂 7.1 Přehled a obsah úloh řízení prodeje zboží a služeb | 7. Řízení prodeje zboží a služeb | 7.1.2 Realizace prodejních transakcí, obchodní případ Prodej
       💬 Účelem je zajistit co nejefektivnější realizace prodejních transakcí, resp. činností v rámci obchodního případu Prodej , tj. přípravy a zpracování obchodních dokumentů prodeje (viz další obrázky).   V...
  [8] 📂 3.7 Faktory v řízení závazků
       💬 Kapitola obsahuje pouze vybrané faktory , které ovlivňují řízení závazků ve strojírenské firmě.  Detailněji: dokument: [Strojírenství: Faktory  ]. Dále uvedené faktory, které jsou relevantní pro řízen...
  [9] 📂 2.7 Faktory ovlivňující finanční řízení
       💬 Kapitola obsahuje pouze vybrané faktory , které ovlivňují finanční řízení ve strojírenské firmě.  Detailněji: dokument: [Strojírenství: Faktory  ]. Dále uvedené faktory, které jsou relevantní pro fina...
  [10] 📂 4.7 Faktory v řízení pohledávek
       💬 Kapitola obsahuje pouze vybrané faktory , které ovlivňují řízení pohledávek ve strojírenské firmě. Detailněji: dokument: [Strojírenství: Faktory] . Dále uvedené faktory, které jsou relevantní pro říze...
  [11] 📂 17.7 Faktory ovlivňující OŘV | 17. Operativní řízení výroby, OŘV
       💬 Kapitola obsahuje pouze vybrané faktory , které ovlivňují operativní řízení výroby ve strojírenské firmě.  Detailněji: dokument: [Strojírenství: Faktory  ]. Dále uvedené faktory, které jsou relevantní...
  [12] 📂 18.7 Faktory DŘV | 18. Dílenské řízení výroby, DŘV
       💬 Kapitola obsahuje pouze vybrané faktory , které ovlivňují dílenské řízení výroby ve strojírenské firmě. Detailněji: dokument: [Strojírenství: Faktory  ]. Dále uvedené faktory, které jsou relevantní pr...
  [13] 📂 16.2 TPV v kontextu řízení firmy | 16. Technická příprava, výroby, TPV | 16.2.1 Vstupy do TPV
       💬 Podstatné vstupy do TPV z ostatních oblastí řízení jsou uvedeny v dalším přehledu:   **Plánování výrobních zakázek:**   - Plán výrobních zakázek, Plánovací sešit výroby, Monitorování a koordinace zaká...
  [14] 📂 7.7 Faktory v řízení prodeje
       💬 Kapitola obsahuje pouze vybrané faktory , které ovlivňují řízení prodejů ve strojírenské firmě.  Detailněji: dokument: [Strojírenství: Faktory  ]. Dále uvedené faktory, které jsou relevantní pro řízen...
  [15] 📂 6.7 Faktory controllingu - 'Byznys prostředí'
       💬 Kapitola obsahuje pouze vybrané faktory , které ovlivňují controlling ve strojírenské firmě.  Detailněji: dokument: [Strojírenství: Faktory  ]. Dále uvedené faktory, které jsou relevantní pro controll...
  [16] 📂 1.7 Faktory strategického řízení Strojírenské firmy
       💬 Kapitola obsahuje pouze vybrané faktory , které ovlivňují tvorbu strategie strojírenské firmy a celé strategické řízení.  Detailněji: dokument: [Strojírenství: Faktory  ]. Dále uvedené faktory, které ...
  [17] 📂 5.7 Faktory v řízení práce a mezd
       💬 Kapitola obsahuje pouze vybrané faktory , které ovlivňují řízení práce a mezd ve strojírenské firmě. Detailněji: dokument: [Strojírenství: Faktory  ]. Dále uvedené faktory, které jsou relevantní pro ř...
  [18] 📂 13.2 Řízení dopravy v kontextu řízení firmy | 13. Řízení dopravy | 13.2.2 Výstupy z řízení dopravy
       💬 Jako podstatné výstupy z řízení interní dopravy pro ostatní oblasti řízení jsou:   **Strategické řízení:**   - dopravní analýzy, plány dopravy: - jsou podkladem pro hodnocení stavu dopravních a dalšíc...
  [19] 📂 11.7 Faktory v řízení majetku | 11. Řízení majetku
       💬 Kapitola obsahuje pouze vybrané faktory , které ovlivňují řízení majetku strojírenské firmy.  Detailněji: dokument: [Strojírenství: Faktory  ]. Dále uvedené faktory, které jsou relevantní pro řízení m...
  [20] 📂 17.1 Přehled a obsah úloh OŘV | 17. Operativní řízení výroby, OŘV | 17.1.2 OŘV: Operativní řízení výroby
       💬 Účelem úlohy je racionální provázání výroby a ekonomiky efektivně realizovat operace související s vyhodnocováním požadavků na výrobu, s přípravou operativních plánů výroby (viz další obrázek).   *Obr...
------------------------------------------------------------
🔍 Nalezené entity pro graf: ['klíčové aktivity', 'evidencia TPV']
🎯 Přímý fulltext dotaz do grafu: *jake* OR *jsou* OR *klíčo* OR *aktiv* OR *evide* OR *tpv*
  🎯 ZÁCHYT V GRAFU: Nalezen uzel [Kapitola] s názvem '15. Plánování a koordinace výrobních zakázek | 15.1 Přehled a obsah úloh plánování a koordinace výrobních zakázek | 15.1.4 Analýzy výrobních zakázek | 15.1.4.1 Klíčové aktivity'
  🎯 ZÁCHYT V GRAFU: Nalezen uzel [Kapitola] s názvem '16. Technická příprava, výroby, TPV | 16.1 Přehled a obsah úloh TPV | 16.1.1 Evidence technické přípravy výroby, TPV'
  🎯 ZÁCHYT V GRAFU: Nalezen uzel [Kapitola] s názvem '6. Controlling | 6.1 Přehled a obsah úloh controllingu | 6.1.2 Analýzy v rámci controllingu | 6.1.2.1 Klíčové aktivity'
  🎯 ZÁCHYT V GRAFU: Nalezen uzel [Kapitola] s názvem '17. Operativní řízení výroby, OŘV | 17.1 Přehled a obsah úloh OŘV | 17.1.3 OŘV: Operativní analýzy výroby | 17.1.3.1 Klíčové aktivity'
  🎯 ZÁCHYT V GRAFU: Nalezen uzel [Kapitola] s názvem '6. Controlling | 6.1 Přehled a obsah úloh controllingu | 6.1.2 Analýzy v rámci controllingu | 6.1.2.1 Klíčové aktivity'
  🎯 ZÁCHYT V GRAFU: Nalezen uzel [Kapitola] s názvem '15. Plánování a koordinace výrobních zakázek | 15.1 Přehled a obsah úloh plánování a koordinace výrobních zakázek | 15.1.4 Analýzy výrobních zakázek | 15.1.4.1 Klíčové aktivity'
  🎯 ZÁCHYT V GRAFU: Nalezen uzel [Kapitola] s názvem '17. Operativní řízení výroby, OŘV | 17.1 Přehled a obsah úloh OŘV | 17.1.5 OŘV: Operativní plánování výroby | 17.1.5.1 Klíčové aktivity'
  🎯 ZÁCHYT V GRAFU: Nalezen uzel [Kapitola] s názvem '16. Technická příprava, výroby, TPV | 16.1 Přehled a obsah úloh TPV | 16.1.1 Evidence technické přípravy výroby, TPV'
✅ CELKEM z grafu: 16 unikátních dokumentů

🕸️  GRAFOVÉ VYHLEDÁVÁNÍ — nalezeno 16 dokumentů (před rerankingem):
------------------------------------------------------------
  [1] 💬 - Analýzy ukazatelů výrobních zakázek dle vybraných dimenzí, např. objemu poptávaných zakázek, nákladů na výrobní zakázku. objemu rozpracované výroby v Kč, v měrných jednotkách. - Analýzy vývoje výrob...
  [2] 💬 Účelem analytické úlohy je především dosažení očekávaných efektů, tj. pozitivních změn v metrikách řízení výrobních zakázek , např. v optimalizaci počtu výrobních zakázek, v nákladech na zakázky apod....
  [3] 💬 Celkový přehled úloh plánování a koordinace výrobních zakázek obsahuje další obrázek:   *Obrázek 15-1: Plánování a koordinace výrobních zakázek - přehled úloh*   Další paragrafy obsahují přehled úloh ...
  [4] 💬 Účelem plánování a koordinace výrobních zakázek je:   - dosahovat efektivního využití výrobních kapacit ve vazbě na potřeby prodeje, případně kooperací s partnery a vysoké ekonomické využití výrobních...
  [5] 💬 Účelem úlohy je vytvářet, a především udržovat aktualizovaná veškerá výrobní data , dokumentaci přípravy výroby (viz další obrázek).   *Obrázek 16-3: Evidence TPV*   **Klíčové aktivity úlohy:**   - Ev...
  [6] 💬 Celkový přehled úloh TPV obsahuje další obrázek:   *Obrázek 16-1: TPV - přehled úloh*   Souhrnný pohled na vybrané aktivity TPV ve vzájemných vazbách dokumentuje další obrázek.   *Obrázek 16-2: Činnos...
  [7] 💬 **TPV zahrnuje :**   - konstrukční přípravu výroby - zpracování návrhu výrobku a konstrukční řešení výrobku a jeho ověření na prototypu, zpracování všech detailních informací o výrobku - použitých mat...
  [8] 💬 - Analýzy finančních ukazatelů podle vybraných dimenzí - Analýzy obchodních ukazatelů podle vybraných dimenzí - Analýzy personálních ukazatelů podle vybraných dimenzí - Analýzy majetkových a investičn...
  [9] 💬 Účelem analytické úlohy je zajistit komplexní analytické operace v rámci firmy a přispívat tak ke zvyšování její výkonnosti a úspěšnosti na trhu (viz další obrázek).   *Obrázek 6-4: Analýzy v controll...
  [10] 💬 Celkový přehled úloh controllingu obsahuje další obrázek:   *Obrázek 6-1: Controlling - přehled úloh*   Do controllingu spadají tyto úlohy :   - Transakce -aktualizace podkladů pro controllingové anal...
  [11] 💬 - Analýzy ukazatelů pro OŘV dle vybraných dimenzí, např. nákladů na výrobní zakázku, objemu rozpracované výroby v Kč, v měrných jednotkách, počtu výpadků, objemu spotřeby dílů, objemu vydaného materiá...
  [12] 💬 Účelem analytické úlohy je především dosažení očekávaných efektů , tj. pozitivních změn v metrikách řízení pro OŘV, např. ve snížení nákladů na výrobu, ve vyšším využití kapacit apod. (viz další obráz...
  [13] 💬 Celkový přehled úloh OŘV obsahuje další obrázek.   *Obrázek 17-1: OŘV - přehled úloh*   **¨Základní charakteristiky OŘV :**   - využívá celé škály normativních i skutečných dat, jako jsou technickohos...
  [14] 💬 **Účelem skupiny úloh je:**   - plánovat a zajišťovat výrobní zakázky podle dlouhodobého a střednědobého plánu výroby ve stanovených termínech, - dosahovat efektivního využití výrobních kapacit , - za...
  [15] 💬 Účelem controllingu je koordinace systému řízení pro zajištění vnitřní a vnější harmonizace a zajištění informací. Controlling doplňuje a integruje management jak v koncepčním, funkcionálním a institu...
  [16] 💬 - Analýzy ukazatelů pro operativní plánování výroby dle vybraných dimenzí, např. nákladů na výrobní zakázku, objemu rozpracované výroby v Kč, v měrných jednotkách, kapacit pracovišť, objemu spotřeby d...
------------------------------------------------------------

🔀 Reranking vektorových dokumentů...
  📊 Reranking [vector] (20 docs → top 10):
  Rank    Score  Preview
  ----------------------------------------------------------------------
  ✅ #1     1.829  Podstatné vstupy do TPV z ostatních oblastí řízení jsou uvedeny v dalším přehledu:   **Plánování výrobních zakázek:**   ...
  ✅ #2     0.658  Účelem úlohy je racionální provázání výroby a ekonomiky efektivně realizovat operace související s vyhodnocováním požada...
  ✅ #3     0.234  Účelem je zajistit co nejefektivnější realizace prodejních transakcí, resp. činností v rámci obchodního případu Prodej ,...
  ✅ #4    -0.040  Účelem je aktualizace základních údajů majetkových databází, klasifikace majetku, technických údajů apod. (viz další obr...
  ✅ #5    -0.061  Podstatné vstupy do operativního řízení výroby z ostatních oblastí řízení jsou uvedeny v dalším přehledu:   **Plánování ...
  ✅ #6    -3.049  Jako podstatné výstupy z řízení interní dopravy pro ostatní oblasti řízení jsou:   **Strategické řízení:**   - dopravní ...
  ✅ #7    -3.454  Kapitola obsahuje pouze vybrané faktory , které ovlivňují technickou přípravu výroby ve strojírenské firmě.  Detailněji:...
  ✅ #8    -3.808  Jako podstatné výstupy z řízení práce a mezd jsou:   Finanční řízení, Řízení lidských zdrojů, IT:   - mzdové výkazy a an...
  ✅ #9    -4.314  Účelem je vytvářet a zajistit průběžnou operativní evidenci o výrobě, a to (viz další obrázek):   - evidenci plánované a...
  ✅ #10   -5.133  Kapitola obsahuje pouze vybrané faktory , které ovlivňují řízení majetku strojírenské firmy.  Detailněji: dokument: [Str...
  ❌ #11   -5.455  Kapitola obsahuje pouze vybrané faktory , které ovlivňují plánování a koordinaci zakázek ve strojírenské firmě.  Detailn...
  ❌ #12   -5.670  Kapitola obsahuje pouze vybrané faktory , které ovlivňují operativní řízení výroby ve strojírenské firmě.  Detailněji: d...
  ❌ #13   -5.717  Kapitola obsahuje pouze vybrané faktory , které ovlivňují řízení pohledávek ve strojírenské firmě. Detailněji: dokument:...
  ❌ #14   -5.730  Kapitola obsahuje pouze vybrané faktory , které ovlivňují tvorbu strategie strojírenské firmy a celé strategické řízení....
  ❌ #15   -5.766  Kapitola obsahuje pouze vybrané faktory , které ovlivňují finanční řízení ve strojírenské firmě.  Detailněji: dokument: ...
  ❌ #16   -5.767  Kapitola obsahuje pouze vybrané faktory , které ovlivňují řízení práce a mezd ve strojírenské firmě. Detailněji: dokumen...
  ❌ #17   -5.878  Kapitola obsahuje pouze vybrané faktory , které ovlivňují dílenské řízení výroby ve strojírenské firmě. Detailněji: doku...
  ❌ #18   -5.925  Kapitola obsahuje pouze vybrané faktory , které ovlivňují řízení závazků ve strojírenské firmě.  Detailněji: dokument: [...
  ❌ #19   -6.055  Kapitola obsahuje pouze vybrané faktory , které ovlivňují řízení prodejů ve strojírenské firmě.  Detailněji: dokument: [...
  ❌ #20   -6.288  Kapitola obsahuje pouze vybrané faktory , které ovlivňují controlling ve strojírenské firmě.  Detailněji: dokument: [Str...

🔀 Reranking grafových dokumentů...
  📊 Reranking [graph] (16 docs → top 10):
  Rank    Score  Preview
  ----------------------------------------------------------------------
  ✅ #1     4.470  Účelem úlohy je vytvářet, a především udržovat aktualizovaná veškerá výrobní data , dokumentaci přípravy výroby (viz dal...
  ✅ #2    -0.104  **TPV zahrnuje :**   - konstrukční přípravu výroby - zpracování návrhu výrobku a konstrukční řešení výrobku a jeho ověře...
  ✅ #3    -1.345  Celkový přehled úloh TPV obsahuje další obrázek:   *Obrázek 16-1: TPV - přehled úloh*   Souhrnný pohled na vybrané aktiv...
  ✅ #4    -2.863  - Analýzy ukazatelů pro operativní plánování výroby dle vybraných dimenzí, např. nákladů na výrobní zakázku, objemu rozp...
  ✅ #5    -2.995  **Účelem skupiny úloh je:**   - plánovat a zajišťovat výrobní zakázky podle dlouhodobého a střednědobého plánu výroby ve...
  ✅ #6    -3.012  Účelem plánování a koordinace výrobních zakázek je:   - dosahovat efektivního využití výrobních kapacit ve vazbě na potř...
  ✅ #7    -3.190  Účelem controllingu je koordinace systému řízení pro zajištění vnitřní a vnější harmonizace a zajištění informací. Contr...
  ✅ #8    -3.256  - Analýzy ukazatelů výrobních zakázek dle vybraných dimenzí, např. objemu poptávaných zakázek, nákladů na výrobní zakázk...
  ✅ #9    -3.402  Účelem analytické úlohy je především dosažení očekávaných efektů, tj. pozitivních změn v metrikách řízení výrobních zaká...
  ✅ #10   -3.633  Účelem analytické úlohy je především dosažení očekávaných efektů , tj. pozitivních změn v metrikách řízení pro OŘV, např...
  ❌ #11   -3.707  Celkový přehled úloh controllingu obsahuje další obrázek:   *Obrázek 6-1: Controlling - přehled úloh*   Do controllingu ...
  ❌ #12   -4.463  Celkový přehled úloh OŘV obsahuje další obrázek.   *Obrázek 17-1: OŘV - přehled úloh*   **¨Základní charakteristiky OŘV ...
  ❌ #13   -4.558  - Analýzy ukazatelů pro OŘV dle vybraných dimenzí, např. nákladů na výrobní zakázku, objemu rozpracované výroby v Kč, v ...
  ❌ #14   -4.817  Účelem analytické úlohy je zajistit komplexní analytické operace v rámci firmy a přispívat tak ke zvyšování její výkonno...
  ❌ #15   -4.861  Celkový přehled úloh plánování a koordinace výrobních zakázek obsahuje další obrázek:   *Obrázek 15-1: Plánování a koord...
  ❌ #16   -5.650  - Analýzy finančních ukazatelů podle vybraných dimenzí - Analýzy obchodních ukazatelů podle vybraných dimenzí - Analýzy ...


🏆 FINÁLNÍ POŘADÍ — VEKTOROVÉ dokumenty předané LLM:
  ----------------------------------------------------------------------
  #1   📂 16.2 TPV v kontextu řízení firmy | 16. Technická příprava, výroby, TPV | 16.2.1 Vstupy do TPV
       💬 Podstatné vstupy do TPV z ostatních oblastí řízení jsou uvedeny v dalším přehledu:   **Plánování výrobních zakázek:**   - Plán výrobních zakázek, Plán...
  #2   📂 17.1 Přehled a obsah úloh OŘV | 17. Operativní řízení výroby, OŘV | 17.1.2 OŘV: Operativní řízení výroby
       💬 Účelem úlohy je racionální provázání výroby a ekonomiky efektivně realizovat operace související s vyhodnocováním požadavků na výrobu, s přípravou ope...
  #3   📂 7.1 Přehled a obsah úloh řízení prodeje zboží a služeb | 7. Řízení prodeje zboží a služeb | 7.1.2 Realizace prodejních transakcí, obchodní případ Prodej
       💬 Účelem je zajistit co nejefektivnější realizace prodejních transakcí, resp. činností v rámci obchodního případu Prodej , tj. přípravy a zpracování obc...
  #4   📂 11.1 Přehled a obsah úloh řízení majetku | 11. Řízení majetku | 11.1.1 Evidence majetku
       💬 Účelem je aktualizace základních údajů majetkových databází, klasifikace majetku, technických údajů apod. (viz další obrázek).   *Obrázek 11-2: Eviden...
  #5   📂 17.2 OŘV v kontextu řízení firmy | 17. Operativní řízení výroby, OŘV | 17.2.1 Vstupy do OŘV
       💬 Podstatné vstupy do operativního řízení výroby z ostatních oblastí řízení jsou uvedeny v dalším přehledu:   **Plánování výrobních zakázek:**   - Plán ...
  #6   📂 13.2 Řízení dopravy v kontextu řízení firmy | 13. Řízení dopravy | 13.2.2 Výstupy z řízení dopravy
       💬 Jako podstatné výstupy z řízení interní dopravy pro ostatní oblasti řízení jsou:   **Strategické řízení:**   - dopravní analýzy, plány dopravy: - jsou...
  #7   📂 16.7 Faktory podstatné pro TPV | 16. Technická příprava, výroby, TPV
       💬 Kapitola obsahuje pouze vybrané faktory , které ovlivňují technickou přípravu výroby ve strojírenské firmě.  Detailněji: dokument: [Strojírenství: Fak...
  #8   📂 5.2 Řízení práce a mezd v kontextu řízení firmy | 5. Řízení práce a mezd, PAM | 5.2.2 Výstupy z řízení práce a mezd
       💬 Jako podstatné výstupy z řízení práce a mezd jsou:   Finanční řízení, Řízení lidských zdrojů, IT:   - mzdové výkazy a analýzy, mzdové plány: - předsta...
  #9   📂 17.1 Přehled a obsah úloh OŘV | 17. Operativní řízení výroby, OŘV | 17.1.1 OŘV: Operativní evidence výroby
       💬 Účelem je vytvářet a zajistit průběžnou operativní evidenci o výrobě, a to (viz další obrázek):   - evidenci plánované a realizované výroby v kusech, ...
  #10  📂 11.7 Faktory v řízení majetku | 11. Řízení majetku
       💬 Kapitola obsahuje pouze vybrané faktory , které ovlivňují řízení majetku strojírenské firmy.  Detailněji: dokument: [Strojírenství: Faktory  ]. Dále u...

🏆 FINÁLNÍ POŘADÍ — GRAFOVÉ dokumenty předané LLM:
  ----------------------------------------------------------------------

In [ ]:
def showGraph():
    driver = GraphDatabase.driver(
        uri=os.environ.get('NEO4J_URI'),
        auth=(os.environ.get('NEO4J_USERNAME'), os.environ.get('NEO4J_PASSWORD'))
    )

    with driver.session() as session:
        query = """
        MATCH (s)-[r]->(t)
        RETURN s, r, t
        """
        graph_data = session.run(query).graph()

    driver.close()

    widget = GraphWidget(graph=graph_data)

    def custom_node_label(node):
        props = node.get("properties", {})
        labels = node.get("labels", [])

        # Uzly Document zobrazí začátek textu místo hash identifikátoru
        if "Document" in labels:
            text = props.get("text", "")
            return text[:40] + "..." if text else "Textový blok"

        # Kapitoly a entity zobrazí své id
        return props.get("id", "Neznámý uzel")

    widget.node_label_mapping = custom_node_label
    return widget

showGraph()

GraphWidget(layout=Layout(height='800px', width='100%'))

---

##  Část 2 — Evaluace

Evaluace **přímo volá retrievery z pipeline** výše — žádná duplicita kódu, žádný rozdíl v odpovědích.

**Retrievery:**
- `Standard RAG` — pouze vektorové vyhledávání (`vector_retriever`, k=20)
- `Pure Graph RAG` — pouze grafové vyhledávání + reranking
- `Hybrid GraphRAG` — kombinace grafu + vektoru + reranking (= `full_retriever`)

**Metriky:**
- `BERTScore` P/R/F1 — sémantická podobnost s ground truth
- `ROUGE-L` P/R/F1 — lexikální překryv s ground truth
- `RAGAS` Faithfulness, AnswerRelevancy, ContextRecall, AnswerCorrectness (LLM judge: Qwen)

In [ ]:
try:
    from bert_score import score as bert_score
    BERTSCORE_AVAILABLE = True
    print("BERTScore načten.")
except ImportError:
    BERTSCORE_AVAILABLE = False
    print("bert-score není dostupný: pip install bert-score")

try:
    from rouge_score import rouge_scorer
    ROUGE_AVAILABLE = True
    print("ROUGE-L načten.")
except ImportError:
    ROUGE_AVAILABLE = False
    print("rouge-score není dostupný: pip install rouge-score")

try:
    from ragas.metrics import Faithfulness, AnswerRelevancy, AnswerCorrectness, ContextRecall
    from ragas import evaluate as evaluate_ragas
    from ragas.llms import LangchainLLMWrapper
    from ragas.embeddings import LangchainEmbeddingsWrapper
    from ragas.run_config import RunConfig
    from datasets import Dataset
    RAGAS_AVAILABLE = True
    print("RAGAS načten.")
except ImportError:
    RAGAS_AVAILABLE = False
    print("ragas není dostupný: pip install ragas datasets")

# LLM judge pro RAGAS — nezávislý model oddělený od modelu generujícího odpovědi
llm_judge = ChatOllama(model="qwen2.5:7b", temperature=0, num_ctx=16384)

print("Evaluační závislosti načteny.")
print("LLM judge: qwen2.5:7b")

✅ BERTScore loaded
✅ ROUGE-L loaded
✅ RAGAS loaded
✅ Eval imports hotové
   LLM judge (RAGAS): qwen2.5:7b

/var/folders/bq/dvsycyn560sgx_gql985ch9w0000gn/T/ipykernel_55056/1775939859.py:22: DeprecationWarning: Importing Faithfulness from 'ragas.metrics' is deprecated and will be removed in v1.0. Please use 'ragas.metrics.collections' instead. Example: from ragas.metrics.collections import Faithfulness
  from ragas.metrics import Faithfulness, AnswerRelevancy, AnswerCorrectness, ContextRecall
/var/folders/bq/dvsycyn560sgx_gql985ch9w0000gn/T/ipykernel_55056/1775939859.py:22: DeprecationWarning: Importing AnswerRelevancy from 'ragas.metrics' is deprecated and will be removed in v1.0. Please use 'ragas.metrics.collections' instead. Example: from ragas.metrics.collections import AnswerRelevancy
  from ragas.metrics import Faithfulness, AnswerRelevancy, AnswerCorrectness, ContextRecall
/var/folders/bq/dvsycyn560sgx_gql985ch9w0000gn/T/ipykernel_55056/1775939859.py:22: DeprecationWarning: Importing AnswerCorrectness from 'ragas.metrics' is deprecated and will be removed in v1.0. Please use 'ragas.metrics.collections' instead. Example: from ragas.metrics.collections import AnswerCorrectness
  from ragas.metrics import Faithfulness, AnswerRelevancy, AnswerCorrectness, ContextRecall
/var/folders/bq/dvsycyn560sgx_gql985ch9w0000gn/T/ipykernel_55056/1775939859.py:22: DeprecationWarning: Importing ContextRecall from 'ragas.metrics' is deprecated and will be removed in v1.0. Please use 'ragas.metrics.collections' instead. Example: from ragas.metrics.collections import ContextRecall
  from ragas.metrics import Faithfulness, AnswerRelevancy, AnswerCorrectness, ContextRecall

In [ ]:
def naive_rag(question: str) -> str:
    """Naive RAG — Dense Retriever (cosine similarity).Baseline.
    """
    docs = dense_retriever.invoke(question)
    return '\n\n'.join(d.page_content for d in docs)


def graph_rag(question: str) -> str:
    """Graph RAG — Knowledge Graph Retriever"""
    rel, docs = graph_enhanced_retriever(question)
    ranked = rerank_docs(question, docs, top_k=10) if docs else []
    graph_text = '\n\n'.join(ranked)
    return (
        f'### DOKUMENTY Z GRAFU:\n{graph_text[:8000]}'
        f'\n\n### VZTAHY Z GRAFU:\n{rel[:3000]}'
    )


def hybrid_graphrag(question: str) -> str:
    """Hybrid GraphRAG — Knowledge Graph + (cosine similarity).
    Kombinuje grafovou navigaci s Hybrid Retrieverem = plný Hybrid RAG přístup.
    """
    return full_retriever(question)


SCENARE = {
    'Naive RAG':       naive_rag,       # Dense Retriever,
    'Graph RAG':       graph_rag,       # KG Retriever,
    'Hybrid GraphRAG': hybrid_graphrag, # KG + Hybrid Retriever
}


print("Evaluační scénáře připraveny:")
print("  Naive RAG       — dense retriever, bez rerankingu (baseline)")
print("  Graph RAG       — KG traversal s rerankingem")
print("  Hybrid GraphRAG — KG traversal + hybridní retriever s rerankingem")

✅ Evaluační retrievery připraveny
   Scénáře: ['Naive RAG', 'Graph RAG', 'Hybrid GraphRAG']

Naive RAG       — Dense only, BEZ rerankingu  → baseline (Lewis 2020)
Graph RAG       — KG Retriever + reranking    → přínos grafu
Hybrid GraphRAG — KG + Hybrid + reranking     → hlavní systém

###  Kompetenční otázky

Každá sada je seznam dvojic `(otázka, ground_truth)`.

In [ ]:
sada_strojirenska_firma = [
 
    # ── VÝČTOVÉ (3) ────────────────────────────────────────────────────────────
    # Testují úplnost retrieval — graf by měl vrátit celý výčet z kapitoly
 
    (
        'Jake jsou klíčové aktivity v evidenci TPV?',
        '- Evidence kusovníků, kusovníkových položek a kusovníkových vazeb:\n'
        '    - Stavebnicový kusovník\n'
        '    - Strukturní analytický kusovník\n'
        '    - Strukturní přehled\n'
        '    - Inverzní kusovník na celý sortiment\n'
        '    - Souhrnný kusovník\n'
        '- Specifikace technologických postupů\n'
        '- Vytváření a aktualizace normativní základny\n'
        '- Specifikace výrobních středisek\n'
        '- Evidence výkresů a rozpisek materiálů\n'
        '- Průběžné sledování pracnosti probíhajících výrobních zakázek'
    ),
 
    (
        'Jaké funkce zahrnuje pokročilá analytika v marketingu?',
        '- Segmentace zákazníků podle různých charakteristik '
        '(demografické, behaviorální, geografické)\n'
        '- Predikce odchodu zákazníků (churn management)\n'
        '- Credit scoring — ohodnocení zákazníka podle úvěrového rizika\n'
        '- Analýza nákupního košíku — zjišťování souvislostí mezi produkty '
        'které zákazníci kupují společně'
    ),
 
    (
        'Jaké jsou klíčové aktivity analytické úlohy v controllingu?',
        '- Analýzy finančních ukazatelů podle vybraných dimenzí\n'
        '- Analýzy obchodních ukazatelů podle vybraných dimenzí\n'
        '- Analýzy personálních ukazatelů podle vybraných dimenzí\n'
        '- Analýzy majetkových a investičních ukazatelů podle vybraných dimenzí\n'
        '- Časové analýzy v controllingu\n'
        '- Analýzy vnitropodnikových normativů\n'
        '- Vyhodnocování kalkulací'
    ),
 
    # ── DEFINICE / ÚČEL (3) ────────────────────────────────────────────────────
    # Testují přesnost — jednodušší retrieval, dobrý pro baseline
 
    (
        'Jaký je účel TPV v technické přípravě?',
        'Účelem TPV je připravit kvalitní technickou a technologickou dokumentaci výrobků, '
        'připravit podklady pro nákup na základě objemu výroby a příslušných kusovníků, '
        'připravit podklady pro řízení kooperací s výrobními partnery a udržovat celý systém norem, '
        'technické dokumentace a dokumentace technologických postupů pro řízení výroby.'
    ),
 
    (
        'Jaký je účel dílenského řízení výroby (DŘV)?',
        '- Zajišťovat realizaci výrobních zakázek podle operativních plánů výroby '
        'a dílenských plánů výroby\n'
        '- Dosahovat efektivního využití výrobních kapacit\n'
        '- Zajišťovat požadovanou kvalitu výroby a finálních výrobků'
    ),
 
    (
        'Jaký je účel controllingu?',
        'Účelem controllingu je koordinace systému řízení pro zajištění vnitřní a vnější '
        'harmonizace a zajištění informací. Controlling doplňuje a integruje management '
        'jak v koncepčním, funkcionálním a institucionálním smyslu, tak i v personálním smyslu.'
    ),
 
    # ── VZTAHOVÉ — vstupy/výstupy mezi oblastmi (3) ───────────────────────────
    # Testují traversal přes hrany grafu — silná stránka GraphRAG
    # Naive RAG tyto otázky pravděpodobně špatně zodpoví (informace jsou ve více chunkcích)
 
    (
        'Jaké jsou vstupy do TPV v oblasti plánování výrobních zakázek?',
        '- Plán výrobních zakázek\n'
        '- Plánovací sešit výroby\n'
        '- Monitorování a koordinace zakázek\n'
        '- Dostupnost zásob v čase\n'
        '- Evidence výrobních zakázek\n'
        '- Kalkulace zakázek\n'
        '- Průběžné sledování pracnosti\n'
        '- Dokumenty probíhajících, plánovaných a realizovaných zakázkách\n'
        '- Výrobní plány - dlouhodobé, střednědobé, operativní'
    ),
 
    (
        'Jaké jsou výstupy z TPV do OŘV?',
        '- Kusovníky\n'
        '- Kusovníkové položky\n'
        '- Technologické postupy\n'
        '- Normy, normativní základna\n'
        '- Výrobní střediska\n'
        '- Výkresy\n'
        '- Rozpisky materiálů\n'
        '- Technická a výrobní dokumentace'
    ),
 
    (
        'Jaké jsou vstupy do DŘV z TPV?',
        '- Normy, normativní základna\n'
        '- Kusovníky\n'
        '- Kusovníkové položky\n'
        '- Technologické postupy\n'
        '- Výrobní střediska\n'
        '- Výkresy\n'
        '- Rozpisky materiálů\n'
        '- Technická a výrobní dokumentace'
    ),
 
    # ── FAKTICKÉ — jednoduché definice (3) ────────────────────────────────────
    # Testují základní retrieval — baseline by měl zvládnout
    # Pokud baseline selže i zde, je to silný argument pro GraphRAG
 
    (
        'Co je to strukturní analytický kusovník?',
        'Strukturní analytický kusovník je celá struktura výrobku nebo vyráběné součásti '
        'a zachycuje všechny přímo i nepřímo vstupující položky. Vstupující součásti jsou '
        'zobrazeny tolikrát, kolikrát se vyskytují ve struktuře, je zde také určeno množství '
        'nižší součásti do vyšší podle výrobních.'
    ),
 
    (
        'Jaké jsou základní charakteristiky OŘV?',
        '- Využívá celé škály normativních i skutečných dat jako jsou technickohospodářské '
        'normy, kapacity pracovišť a další\n'
        '- Základním obdobím je kvartál, klouzavě se posunující v čase\n'
        '- Zakládá se na hodnocení průběžné doby výroby, hospodářských smluv a dalších parametrech\n'
        '- Zahrnuje operativní evidence, operativní hodnocení průběhu výroby i operativní '
        'plánování výroby\n'
        '- Podstatnou součástí je řízení změn a nastavení změnového řízení'
    ),
 
    (
        'Jaké KPI se využívají v technické přípravě výroby?',
        '- Technickohospodářské normy spotřeby materiálu\n'
        '- Normy zásob\n'
        '- Normy ztrát a mank\n'
        '- Kapacitní normy\n'
        '- Normy spotřeby času'
    ),
 
]
print(f'   sada_strojirenska_firma:   {len(sada_strojirenska_firma)} otázek')

   sada_strojirenska_firma:   12 otázek

In [ ]:
import threading
import inspect

LLM_TIMEOUT = 180


def compute_bertscore(predictions, references):
    """Vrátí (Precision, Recall, F1) listy pro BERTScore."""
    if not BERTSCORE_AVAILABLE:
        none = [None] * len(predictions)
        return none, none, none
    P, R, F1 = bert_score(
        predictions, references,
        model_type='bert-base-multilingual-cased', lang='cs',
        verbose=False
    )
    return P.tolist(), R.tolist(), F1.tolist()


def compute_rouge(predictions, references):
    """Vrátí (Precision, Recall, F1) listy pro ROUGE-L."""
    if not ROUGE_AVAILABLE:
        none = [None] * len(predictions)
        return none, none, none
    scorer = rouge_scorer.RougeScorer(['rougeL'], use_stemmer=False)
    P, R, F1 = [], [], []
    for pred, ref in zip(predictions, references):
        s = scorer.score(ref, pred)['rougeL']
        P.append(s.precision); R.append(s.recall); F1.append(s.fmeasure)
    return P, R, F1


def call_with_timeout(retriever, llm, question, timeout=LLM_TIMEOUT):
    """Zavolá retriever a LLM s timeoutem. Vrátí (answer, context, elapsed_s)."""
    result = {}

    # Prompt identický s pipeline — zajišťuje konzistenci mezi evaluací a produkcí
    EVAL_PROMPT = """
Jsi expertní analytický systém pracující s technickou dokumentací.

### KRITICKÁ PRAVIDLA:
1. ODPOVÍDEJ POUZE NA ZÁKLADĚ DODANÉHO KONTEXTU.
2. Pro výčty použij odrážkový seznam, pro definice odstavce.
3. KOMPLETNÍ VÝČET BEZ ZKRACOVÁNÍ — žádné "a další", "apod.", "atd.".

### KONTEXT:
{context}

### OTÁZKA:
{question}

### ODPOVĚĎ:"""

    def worker():
        try:
            context = retriever(question)
            prompt  = EVAL_PROMPT.format(context=context, question=question)
            answer  = llm_rag.invoke(prompt).content
            result['ok'] = (answer, context)
        except Exception as e:
            result['error'] = str(e)

    t  = threading.Thread(target=worker)
    t0 = time.time()
    t.start()
    t.join(timeout=timeout)
    elapsed = round(time.time() - t0, 1)

    if t.is_alive():
        return None, None, elapsed
    if 'error' in result:
        return f"ERROR: {result['error']}", '', elapsed
    answer, context = result['ok']
    return answer, context, elapsed


def evaluate(sada, document_name=None, timeout=LLM_TIMEOUT, mode='combined'):
    """
    Spustí evaluaci pro danou testovací sadu.

    Retrievery jsou volány přímo z pipeline — bez duplicity kódu,
    chování je identické se Streamlit aplikací.

    Parametry
    ----------
    sada          : list of (question, ground_truth)
    document_name : str, volitelný — název pro výstupní CSV
    timeout       : int, sekundy na jedno LLM volání (výchozí 180)
    mode          : 'combined' | 'reference' | 'ragas'
        'combined'   — BERTScore + ROUGE-L + RAGAS (výchozí)
        'reference'  — pouze BERTScore + ROUGE-L, bez LLM judge
        'ragas'      — pouze RAGAS
    """
    if not sada:
        print('Testovací sada je prázdná.')
        return None

    if document_name is None:
        frame = inspect.currentframe().f_back
        document_name = next(
            (k for k, v in frame.f_locals.items() if v is sada), 'document'
        ).replace('sada_', '')

    print(f'Evaluace: {document_name}')
    print(f'Otázky: {len(sada)} | Metody: {len(SCENARE)} | '
          f'LLM volání celkem: {len(sada) * len(SCENARE)}')
    print(f'Timeout: {timeout}s | Mode: {mode}\n')

    rows     = []
    out_file = f'../evaluation/evaluation_{document_name}.csv'

    for i, (question, ground_truth) in enumerate(sada, 1):
        print(f'[{i}/{len(sada)}] {question}')
        for method_name, retriever in SCENARE.items():
            print(f'  {method_name}...', end=' ', flush=True)

            answer, context, elapsed = call_with_timeout(retriever, llm_rag, question, timeout)

            if answer is None:
                print(f'Timeout ({elapsed}s), přeskočeno.')
                answer = 'TIMEOUT'; context = ''
            else:
                print(f'{elapsed}s')
                print(f'    {answer[:120].replace(chr(10), " ")}...')

            if answer != 'TIMEOUT' and mode in ('combined', 'reference'):
                bp, br, bf1 = compute_bertscore([answer], [ground_truth])
                rp, rr, rf1 = compute_rouge([answer], [ground_truth])
                bert_p, bert_r, bert_f1 = bp[0], br[0], bf1[0]
                rouge_p, rouge_r, rouge_f1 = rp[0], rr[0], rf1[0]
                print(f'    BERT F1: {round(bert_f1, 3)} | '
                      f'ROUGE-L R: {round(rouge_r, 3)} | '
                      f'ROUGE-L F1: {round(rouge_f1, 3)}')
            else:
                bert_p = bert_r = bert_f1 = None
                rouge_p = rouge_r = rouge_f1 = None

            rows.append({
                'document':     document_name,
                'method':       method_name,
                'question':     question,
                'answer':       answer,
                'context':      context,
                'time_s':       elapsed,
                'ground_truth': ground_truth,
                'BERTScore_P':  bert_p,
                'BERTScore_R':  bert_r,
                'BERTScore_F1': bert_f1,
                'ROUGE_L_P':    rouge_p,
                'ROUGE_L_R':    rouge_r,
                'ROUGE_L_F1':   rouge_f1,
            })

        # Průběžné ukládání po každé otázce
        existing = pd.read_csv(out_file) if os.path.exists(out_file) else pd.DataFrame()
        pd.concat([existing, pd.DataFrame(rows)]).drop_duplicates(
            subset=['method', 'question'], keep='last'
        ).to_csv(out_file, index=False, encoding='utf-8-sig')
        print(f'  Uloženo: {out_file}\n')

    df = pd.DataFrame(rows)

    print('\n' + '=' * 60)
    print('Vygenerované odpovědi')
    print('=' * 60)
    for _, r in df.iterrows():
        print(f'\n[{r["method"]}] {r["question"]}')
        print('-' * 40)
        print(r['answer'])

    df_valid = df[df['answer'] != 'TIMEOUT'].copy()
    if df_valid.empty:
        print('Žádné platné výsledky — všechna volání překročila timeout.')
        return df

    if mode in ('combined', 'ragas') and RAGAS_AVAILABLE:
        print('\nRAGAS evaluace...')
        ragas_llm = LangchainLLMWrapper(llm_judge)
        ragas_emb = LangchainEmbeddingsWrapper(embeddings)

        dataset = Dataset.from_dict({
            'user_input':         df_valid['question'].tolist(),
            'response':           df_valid['answer'].tolist(),
            'retrieved_contexts': [[k] for k in df_valid['context'].tolist()],
            'reference':          df_valid['ground_truth'].tolist(),
        })
        ragas_result = evaluate_ragas(
            dataset=dataset,
            metrics=[Faithfulness(), AnswerRelevancy(), ContextRecall(), AnswerCorrectness()],
            llm=ragas_llm, embeddings=ragas_emb,
            run_config=RunConfig(timeout=300, max_workers=1)
        )
        df_ragas   = ragas_result.to_pandas()
        wanted     = ['faithfulness', 'answer_relevancy', 'context_recall', 'answer_correctness']
        available  = [c for c in wanted if c in df_ragas.columns]
        ragas_cols = df_ragas[available].reset_index(drop=True)
    else:
        ragas_cols = pd.DataFrame({
            'faithfulness':       [None] * len(df_valid),
            'answer_relevancy':   [None] * len(df_valid),
            'context_recall':     [None] * len(df_valid),
            'answer_correctness': [None] * len(df_valid),
        })

    ref_cols = ['BERTScore_P', 'BERTScore_R', 'BERTScore_F1',
                'ROUGE_L_P', 'ROUGE_L_R', 'ROUGE_L_F1']
    df_out = pd.concat([
        df_valid[['document', 'method', 'question', 'answer', 'context',
                  'time_s', 'ground_truth'] + ref_cols].reset_index(drop=True),
        ragas_cols
    ], axis=1)

    metrics_cols = [c for c in ref_cols + ['faithfulness', 'answer_relevancy',
                    'context_recall', 'answer_correctness'] if c in df_out.columns]

    print(f'\nVýsledky per otázka — {document_name}')
    display(df_out[['method', 'question'] + metrics_cols].round(3))

    print(f'\nPrůměrné skóre — {document_name}')
    display(df_out.groupby('method')[metrics_cols].mean().round(3))

    if 'ROUGE_L_R' in df_out.columns and df_out['ROUGE_L_R'].notna().any():
        best_rouge = df_out.groupby('method')['ROUGE_L_R'].mean().idxmax()
        print(f'\nNejlepší ROUGE-L Recall (úplnost):    {best_rouge}')
    if 'BERTScore_F1' in df_out.columns and df_out['BERTScore_F1'].notna().any():
        best_bert = df_out.groupby('method')['BERTScore_F1'].mean().idxmax()
        print(f'Nejlepší BERTScore F1 (sémantika):     {best_bert}')
    if 'answer_correctness' in df_out.columns and df_out['answer_correctness'].notna().any():
        best_ac = df_out.groupby('method')['answer_correctness'].mean().idxmax()
        print(f'Nejlepší Answer Correctness (RAGAS):   {best_ac}')

    existing = pd.read_csv(out_file) if os.path.exists(out_file) else pd.DataFrame()
    pd.concat([existing, df_out]).drop_duplicates(
        subset=['method', 'question'], keep='last'
    ).to_csv(out_file, index=False, encoding='utf-8-sig')
    print(f'\nVýsledky uloženy: {out_file}')
    return df_out


print('evaluate() připravena.')
print('  evaluate(sada_strojirenska_firma)                     # combined')
print('  evaluate(sada_strojirenska_firma, mode="reference")   # bez RAGAS')
print('  evaluate(sada_strojirenska_firma, mode="ragas")       # pouze RAGAS')
print('  evaluate(sada_strojirenska_firma[:1])                 # jedna otázka')

✅ evaluate() připravena

Použití:
  evaluate(sada_strojirenska_firma)                            # combined
  evaluate(sada_strojirenska_firma, mode="reference")          # bez RAGAS
  evaluate(sada_strojirenska_firma, mode="ragas")              # pouze RAGAS
  evaluate(sada_strojirenska_firma[:1], document_name="q1")    # 1 otázka

###  Spuštění evaluace

In [75]:
evaluate(sada_strojirenska_firma, timeout=120, mode='combined', document_name='strojirenska_firma')

🚀 Evaluating: strojirenska_firma
   Otázky: 12 | Metody: 3 | Celkem LLM volání: 36
   Timeout: 120s | Mode: combined

[1/12] Jake jsou klíčové aktivity v evidenci TPV?
  ⏳ Naive RAG... ✅ 23.6s
    → Klíčové aktivity v evidenci TPV (Technické přípravy výroby) jsou:  1.  **Prověření a analýza požadavků na výrobu**: Prov...
    BERT F1: 0.675 | ROUGE-L R: 0.211 | ROUGE-L F1: 0.121
  ⏳ Graph RAG... 🔍 Nalezené entity pro graf: ['klíčové aktivity', 'evidencia TPV']
🎯 Přímý fulltext dotaz do grafu: *jake* OR *jsou* OR *klíčo* OR *aktiv* OR *evide* OR *tpv*
  🎯 ZÁCHYT V GRAFU: Nalezen uzel [Kapitola] s názvem '15. Plánování a koordinace výrobních zakázek | 15.1 Přehled a obsah úloh plánování a koordinace výrobních zakázek | 15.1.4 Analýzy výrobních zakázek | 15.1.4.1 Klíčové aktivity'
  🎯 ZÁCHYT V GRAFU: Nalezen uzel [Kapitola] s názvem '16. Technická příprava, výroby, TPV | 16.1 Přehled a obsah úloh TPV | 16.1.1 Evidence technické přípravy výroby, TPV'
  🎯 ZÁCHYT V GRAFU: Nalezen uzel [Kapitola] s názvem '6. Controlling | 6.1 Přehled a obsah úloh controllingu | 6.1.2 Analýzy v rámci controllingu | 6.1.2.1 Klíčové aktivity'
  🎯 ZÁCHYT V GRAFU: Nalezen uzel [Kapitola] s názvem '17. Operativní řízení výroby, OŘV | 17.1 Přehled a obsah úloh OŘV | 17.1.3 OŘV: Operativní analýzy výroby | 17.1.3.1 Klíčové aktivity'
  🎯 ZÁCHYT V GRAFU: Nalezen uzel [Kapitola] s názvem '6. Controlling | 6.1 Přehled a obsah úloh controllingu | 6.1.2 Analýzy v rámci controllingu | 6.1.2.1 Klíčové aktivity'
  🎯 ZÁCHYT V GRAFU: Nalezen uzel [Kapitola] s názvem '15. Plánování a koordinace výrobních zakázek | 15.1 Přehled a obsah úloh plánování a koordinace výrobních zakázek | 15.1.4 Analýzy výrobních zakázek | 15.1.4.1 Klíčové aktivity'
  🎯 ZÁCHYT V GRAFU: Nalezen uzel [Kapitola] s názvem '17. Operativní řízení výroby, OŘV | 17.1 Přehled a obsah úloh OŘV | 17.1.5 OŘV: Operativní plánování výroby | 17.1.5.1 Klíčové aktivity'
  🎯 ZÁCHYT V GRAFU: Nalezen uzel [Kapitola] s názvem '16. Technická příprava, výroby, TPV | 16.1 Přehled a obsah úloh TPV | 16.1.1 Evidence technické přípravy výroby, TPV'
✅ CELKEM z grafu: 16 unikátních dokumentů
  📊 Reranking (16 docs → top 10):
  Rank    Score  Preview
  ----------------------------------------------------------------------
  ✅ #1     4.470  Účelem úlohy je vytvářet, a především udržovat aktualizovaná veškerá výrobní data , dokumentaci přípravy výroby (viz dal...
  ✅ #2    -0.104  **TPV zahrnuje :**   - konstrukční přípravu výroby - zpracování návrhu výrobku a konstrukční řešení výrobku a jeho ověře...
  ✅ #3    -1.345  Celkový přehled úloh TPV obsahuje další obrázek:   *Obrázek 16-1: TPV - přehled úloh*   Souhrnný pohled na vybrané aktiv...
  ✅ #4    -2.863  - Analýzy ukazatelů pro operativní plánování výroby dle vybraných dimenzí, např. nákladů na výrobní zakázku, objemu rozp...
  ✅ #5    -2.995  **Účelem skupiny úloh je:**   - plánovat a zajišťovat výrobní zakázky podle dlouhodobého a střednědobého plánu výroby ve...
  ✅ #6    -3.012  Účelem plánování a koordinace výrobních zakázek je:   - dosahovat efektivního využití výrobních kapacit ve vazbě na potř...
  ✅ #7    -3.190  Účelem controllingu je koordinace systému řízení pro zajištění vnitřní a vnější harmonizace a zajištění informací. Contr...
  ✅ #8    -3.256  - Analýzy ukazatelů výrobních zakázek dle vybraných dimenzí, např. objemu poptávaných zakázek, nákladů na výrobní zakázk...
  ✅ #9    -3.402  Účelem analytické úlohy je především dosažení očekávaných efektů, tj. pozitivních změn v metrikách řízení výrobních zaká...
  ✅ #10   -3.633  Účelem analytické úlohy je především dosažení očekávaných efektů , tj. pozitivních změn v metrikách řízení pro OŘV, např...
  ❌ #11   -3.707  Celkový přehled úloh controllingu obsahuje další obrázek:   *Obrázek 6-1: Controlling - přehled úloh*   Do controllingu ...
  ❌ #12   -4.463  Celkový přehled úloh OŘV obsahuje další obrázek.   *Obrázek 17-1: OŘV - přehled úloh*   **¨Základní charakteristiky OŘV ...
  ❌ #13   -4.558  - Analýzy ukazatelů pro OŘV dle vybraných dimenzí, např. nákladů na výrobní zakázku, objemu rozpracované výroby v Kč, v ...
  ❌ #14   -4.817  Účelem analytické úlohy je zajistit komplexní analytické operace v rámci firmy a přispívat tak ke zvyšování její výkonno...
  ❌ #15   -4.861  Celkový přehled úloh plánování a koordinace výrobních zakázek obsahuje další obrázek:   *Obrázek 15-1: Plánování a koord...
  ❌ #16   -5.650  - Analýzy finančních ukazatelů podle vybraných dimenzí - Analýzy obchodních ukazatelů podle vybraných dimenzí - Analýzy ...

✅ 34.7s
    → Klíčové aktivity v evidenci TPV (Technické přípravy výroby) jsou:  1.  Evidence kusovníků, kusovníkových položek a kusov...
    BERT F1: 0.705 | ROUGE-L R: 1.0 | ROUGE-L F1: 0.243
  ⏳ Hybrid GraphRAG...
--- HLEDÁM ODPOVĚĎ NA: 'Jake jsou klíčové aktivity v evidenci TPV?' ---

📚 VEKTOROVÉ VYHLEDÁVÁNÍ — nalezeno 20 dokumentů (před rerankingem):
------------------------------------------------------------
  [1] 📂 11.1 Přehled a obsah úloh řízení majetku | 11. Řízení majetku | 11.1.1 Evidence majetku
       💬 Účelem je aktualizace základních údajů majetkových databází, klasifikace majetku, technických údajů apod. (viz další obrázek).   *Obrázek 11-2: Evidence majetku*   **Zajišťuje tyto klíčové aktivity :*...
  [2] 📂 17.1 Přehled a obsah úloh OŘV | 17. Operativní řízení výroby, OŘV | 17.1.1 OŘV: Operativní evidence výroby
       💬 Účelem je vytvářet a zajistit průběžnou operativní evidenci o výrobě, a to (viz další obrázek):   - evidenci plánované a realizované výroby v kusech, - spotřebu normohodin, - spotřebu materiálu, - sor...
  [3] 📂 17.2 OŘV v kontextu řízení firmy | 17. Operativní řízení výroby, OŘV | 17.2.1 Vstupy do OŘV
       💬 Podstatné vstupy do operativního řízení výroby z ostatních oblastí řízení jsou uvedeny v dalším přehledu:   **Plánování výrobních zakázek:**   - Plán výrobních zakázek, Plánovací sešit výroby, Monitor...
  [4] 📂 5.2 Řízení práce a mezd v kontextu řízení firmy | 5. Řízení práce a mezd, PAM | 5.2.2 Výstupy z řízení práce a mezd
       💬 Jako podstatné výstupy z řízení práce a mezd jsou:   Finanční řízení, Řízení lidských zdrojů, IT:   - mzdové výkazy a analýzy, mzdové plány: - představují vstupy pro komplexní analýzy a plány finanční...
  [5] 📂 15.7 Faktory v plánování a koordinace výrobních zakázek | 15. Plánování a koordinace výrobních zakázek
       💬 Kapitola obsahuje pouze vybrané faktory , které ovlivňují plánování a koordinaci zakázek ve strojírenské firmě.  Detailněji: dokument: [Strojírenství: Faktory  ]. Dále uvedené faktory, které jsou rele...
  [6] 📂 16.7 Faktory podstatné pro TPV | 16. Technická příprava, výroby, TPV
       💬 Kapitola obsahuje pouze vybrané faktory , které ovlivňují technickou přípravu výroby ve strojírenské firmě.  Detailněji: dokument: [Strojírenství: Faktory  ]. Dále uvedené faktory, které jsou relevant...
  [7] 📂 7.1 Přehled a obsah úloh řízení prodeje zboží a služeb | 7. Řízení prodeje zboží a služeb | 7.1.2 Realizace prodejních transakcí, obchodní případ Prodej
       💬 Účelem je zajistit co nejefektivnější realizace prodejních transakcí, resp. činností v rámci obchodního případu Prodej , tj. přípravy a zpracování obchodních dokumentů prodeje (viz další obrázky).   V...
  [8] 📂 3.7 Faktory v řízení závazků
       💬 Kapitola obsahuje pouze vybrané faktory , které ovlivňují řízení závazků ve strojírenské firmě.  Detailněji: dokument: [Strojírenství: Faktory  ]. Dále uvedené faktory, které jsou relevantní pro řízen...
  [9] 📂 2.7 Faktory ovlivňující finanční řízení
       💬 Kapitola obsahuje pouze vybrané faktory , které ovlivňují finanční řízení ve strojírenské firmě.  Detailněji: dokument: [Strojírenství: Faktory  ]. Dále uvedené faktory, které jsou relevantní pro fina...
  [10] 📂 4.7 Faktory v řízení pohledávek
       💬 Kapitola obsahuje pouze vybrané faktory , které ovlivňují řízení pohledávek ve strojírenské firmě. Detailněji: dokument: [Strojírenství: Faktory] . Dále uvedené faktory, které jsou relevantní pro říze...
  [11] 📂 17.7 Faktory ovlivňující OŘV | 17. Operativní řízení výroby, OŘV
       💬 Kapitola obsahuje pouze vybrané faktory , které ovlivňují operativní řízení výroby ve strojírenské firmě.  Detailněji: dokument: [Strojírenství: Faktory  ]. Dále uvedené faktory, které jsou relevantní...
  [12] 📂 18.7 Faktory DŘV | 18. Dílenské řízení výroby, DŘV
       💬 Kapitola obsahuje pouze vybrané faktory , které ovlivňují dílenské řízení výroby ve strojírenské firmě. Detailněji: dokument: [Strojírenství: Faktory  ]. Dále uvedené faktory, které jsou relevantní pr...
  [13] 📂 16.2 TPV v kontextu řízení firmy | 16. Technická příprava, výroby, TPV | 16.2.1 Vstupy do TPV
       💬 Podstatné vstupy do TPV z ostatních oblastí řízení jsou uvedeny v dalším přehledu:   **Plánování výrobních zakázek:**   - Plán výrobních zakázek, Plánovací sešit výroby, Monitorování a koordinace zaká...
  [14] 📂 7.7 Faktory v řízení prodeje
       💬 Kapitola obsahuje pouze vybrané faktory , které ovlivňují řízení prodejů ve strojírenské firmě.  Detailněji: dokument: [Strojírenství: Faktory  ]. Dále uvedené faktory, které jsou relevantní pro řízen...
  [15] 📂 6.7 Faktory controllingu - 'Byznys prostředí'
       💬 Kapitola obsahuje pouze vybrané faktory , které ovlivňují controlling ve strojírenské firmě.  Detailněji: dokument: [Strojírenství: Faktory  ]. Dále uvedené faktory, které jsou relevantní pro controll...
  [16] 📂 1.7 Faktory strategického řízení Strojírenské firmy
       💬 Kapitola obsahuje pouze vybrané faktory , které ovlivňují tvorbu strategie strojírenské firmy a celé strategické řízení.  Detailněji: dokument: [Strojírenství: Faktory  ]. Dále uvedené faktory, které ...
  [17] 📂 5.7 Faktory v řízení práce a mezd
       💬 Kapitola obsahuje pouze vybrané faktory , které ovlivňují řízení práce a mezd ve strojírenské firmě. Detailněji: dokument: [Strojírenství: Faktory  ]. Dále uvedené faktory, které jsou relevantní pro ř...
  [18] 📂 13.2 Řízení dopravy v kontextu řízení firmy | 13. Řízení dopravy | 13.2.2 Výstupy z řízení dopravy
       💬 Jako podstatné výstupy z řízení interní dopravy pro ostatní oblasti řízení jsou:   **Strategické řízení:**   - dopravní analýzy, plány dopravy: - jsou podkladem pro hodnocení stavu dopravních a dalšíc...
  [19] 📂 11.7 Faktory v řízení majetku | 11. Řízení majetku
       💬 Kapitola obsahuje pouze vybrané faktory , které ovlivňují řízení majetku strojírenské firmy.  Detailněji: dokument: [Strojírenství: Faktory  ]. Dále uvedené faktory, které jsou relevantní pro řízení m...
  [20] 📂 17.1 Přehled a obsah úloh OŘV | 17. Operativní řízení výroby, OŘV | 17.1.2 OŘV: Operativní řízení výroby
       💬 Účelem úlohy je racionální provázání výroby a ekonomiky efektivně realizovat operace související s vyhodnocováním požadavků na výrobu, s přípravou operativních plánů výroby (viz další obrázek).   *Obr...
------------------------------------------------------------
🔍 Nalezené entity pro graf: ['klíčové aktivity', 'evidencia TPV']
🎯 Přímý fulltext dotaz do grafu: *jake* OR *jsou* OR *klíčo* OR *aktiv* OR *evide* OR *tpv*
  🎯 ZÁCHYT V GRAFU: Nalezen uzel [Kapitola] s názvem '15. Plánování a koordinace výrobních zakázek | 15.1 Přehled a obsah úloh plánování a koordinace výrobních zakázek | 15.1.4 Analýzy výrobních zakázek | 15.1.4.1 Klíčové aktivity'
  🎯 ZÁCHYT V GRAFU: Nalezen uzel [Kapitola] s názvem '16. Technická příprava, výroby, TPV | 16.1 Přehled a obsah úloh TPV | 16.1.1 Evidence technické přípravy výroby, TPV'
  🎯 ZÁCHYT V GRAFU: Nalezen uzel [Kapitola] s názvem '6. Controlling | 6.1 Přehled a obsah úloh controllingu | 6.1.2 Analýzy v rámci controllingu | 6.1.2.1 Klíčové aktivity'
  🎯 ZÁCHYT V GRAFU: Nalezen uzel [Kapitola] s názvem '17. Operativní řízení výroby, OŘV | 17.1 Přehled a obsah úloh OŘV | 17.1.3 OŘV: Operativní analýzy výroby | 17.1.3.1 Klíčové aktivity'
  🎯 ZÁCHYT V GRAFU: Nalezen uzel [Kapitola] s názvem '6. Controlling | 6.1 Přehled a obsah úloh controllingu | 6.1.2 Analýzy v rámci controllingu | 6.1.2.1 Klíčové aktivity'
  🎯 ZÁCHYT V GRAFU: Nalezen uzel [Kapitola] s názvem '15. Plánování a koordinace výrobních zakázek | 15.1 Přehled a obsah úloh plánování a koordinace výrobních zakázek | 15.1.4 Analýzy výrobních zakázek | 15.1.4.1 Klíčové aktivity'
  🎯 ZÁCHYT V GRAFU: Nalezen uzel [Kapitola] s názvem '17. Operativní řízení výroby, OŘV | 17.1 Přehled a obsah úloh OŘV | 17.1.5 OŘV: Operativní plánování výroby | 17.1.5.1 Klíčové aktivity'
  🎯 ZÁCHYT V GRAFU: Nalezen uzel [Kapitola] s názvem '16. Technická příprava, výroby, TPV | 16.1 Přehled a obsah úloh TPV | 16.1.1 Evidence technické přípravy výroby, TPV'
✅ CELKEM z grafu: 16 unikátních dokumentů

🕸️  GRAFOVÉ VYHLEDÁVÁNÍ — nalezeno 16 dokumentů (před rerankingem):
------------------------------------------------------------
  [1] 💬 - Analýzy ukazatelů výrobních zakázek dle vybraných dimenzí, např. objemu poptávaných zakázek, nákladů na výrobní zakázku. objemu rozpracované výroby v Kč, v měrných jednotkách. - Analýzy vývoje výrob...
  [2] 💬 Účelem analytické úlohy je především dosažení očekávaných efektů, tj. pozitivních změn v metrikách řízení výrobních zakázek , např. v optimalizaci počtu výrobních zakázek, v nákladech na zakázky apod....
  [3] 💬 Celkový přehled úloh plánování a koordinace výrobních zakázek obsahuje další obrázek:   *Obrázek 15-1: Plánování a koordinace výrobních zakázek - přehled úloh*   Další paragrafy obsahují přehled úloh ...
  [4] 💬 Účelem plánování a koordinace výrobních zakázek je:   - dosahovat efektivního využití výrobních kapacit ve vazbě na potřeby prodeje, případně kooperací s partnery a vysoké ekonomické využití výrobních...
  [5] 💬 Účelem úlohy je vytvářet, a především udržovat aktualizovaná veškerá výrobní data , dokumentaci přípravy výroby (viz další obrázek).   *Obrázek 16-3: Evidence TPV*   **Klíčové aktivity úlohy:**   - Ev...
  [6] 💬 Celkový přehled úloh TPV obsahuje další obrázek:   *Obrázek 16-1: TPV - přehled úloh*   Souhrnný pohled na vybrané aktivity TPV ve vzájemných vazbách dokumentuje další obrázek.   *Obrázek 16-2: Činnos...
  [7] 💬 **TPV zahrnuje :**   - konstrukční přípravu výroby - zpracování návrhu výrobku a konstrukční řešení výrobku a jeho ověření na prototypu, zpracování všech detailních informací o výrobku - použitých mat...
  [8] 💬 - Analýzy finančních ukazatelů podle vybraných dimenzí - Analýzy obchodních ukazatelů podle vybraných dimenzí - Analýzy personálních ukazatelů podle vybraných dimenzí - Analýzy majetkových a investičn...
  [9] 💬 Účelem analytické úlohy je zajistit komplexní analytické operace v rámci firmy a přispívat tak ke zvyšování její výkonnosti a úspěšnosti na trhu (viz další obrázek).   *Obrázek 6-4: Analýzy v controll...
  [10] 💬 Celkový přehled úloh controllingu obsahuje další obrázek:   *Obrázek 6-1: Controlling - přehled úloh*   Do controllingu spadají tyto úlohy :   - Transakce -aktualizace podkladů pro controllingové anal...
  [11] 💬 - Analýzy ukazatelů pro OŘV dle vybraných dimenzí, např. nákladů na výrobní zakázku, objemu rozpracované výroby v Kč, v měrných jednotkách, počtu výpadků, objemu spotřeby dílů, objemu vydaného materiá...
  [12] 💬 Účelem analytické úlohy je především dosažení očekávaných efektů , tj. pozitivních změn v metrikách řízení pro OŘV, např. ve snížení nákladů na výrobu, ve vyšším využití kapacit apod. (viz další obráz...
  [13] 💬 Celkový přehled úloh OŘV obsahuje další obrázek.   *Obrázek 17-1: OŘV - přehled úloh*   **¨Základní charakteristiky OŘV :**   - využívá celé škály normativních i skutečných dat, jako jsou technickohos...
  [14] 💬 **Účelem skupiny úloh je:**   - plánovat a zajišťovat výrobní zakázky podle dlouhodobého a střednědobého plánu výroby ve stanovených termínech, - dosahovat efektivního využití výrobních kapacit , - za...
  [15] 💬 Účelem controllingu je koordinace systému řízení pro zajištění vnitřní a vnější harmonizace a zajištění informací. Controlling doplňuje a integruje management jak v koncepčním, funkcionálním a institu...
  [16] 💬 - Analýzy ukazatelů pro operativní plánování výroby dle vybraných dimenzí, např. nákladů na výrobní zakázku, objemu rozpracované výroby v Kč, v měrných jednotkách, kapacit pracovišť, objemu spotřeby d...
------------------------------------------------------------

🔀 Reranking vektorových dokumentů...
  📊 Reranking [vector] (20 docs → top 10):
  Rank    Score  Preview
  ----------------------------------------------------------------------
  ✅ #1     1.829  Podstatné vstupy do TPV z ostatních oblastí řízení jsou uvedeny v dalším přehledu:   **Plánování výrobních zakázek:**   ...
  ✅ #2     0.658  Účelem úlohy je racionální provázání výroby a ekonomiky efektivně realizovat operace související s vyhodnocováním požada...
  ✅ #3     0.234  Účelem je zajistit co nejefektivnější realizace prodejních transakcí, resp. činností v rámci obchodního případu Prodej ,...
  ✅ #4    -0.040  Účelem je aktualizace základních údajů majetkových databází, klasifikace majetku, technických údajů apod. (viz další obr...
  ✅ #5    -0.061  Podstatné vstupy do operativního řízení výroby z ostatních oblastí řízení jsou uvedeny v dalším přehledu:   **Plánování ...
  ✅ #6    -3.049  Jako podstatné výstupy z řízení interní dopravy pro ostatní oblasti řízení jsou:   **Strategické řízení:**   - dopravní ...
  ✅ #7    -3.454  Kapitola obsahuje pouze vybrané faktory , které ovlivňují technickou přípravu výroby ve strojírenské firmě.  Detailněji:...
  ✅ #8    -3.808  Jako podstatné výstupy z řízení práce a mezd jsou:   Finanční řízení, Řízení lidských zdrojů, IT:   - mzdové výkazy a an...
  ✅ #9    -4.314  Účelem je vytvářet a zajistit průběžnou operativní evidenci o výrobě, a to (viz další obrázek):   - evidenci plánované a...
  ✅ #10   -5.133  Kapitola obsahuje pouze vybrané faktory , které ovlivňují řízení majetku strojírenské firmy.  Detailněji: dokument: [Str...
  ❌ #11   -5.455  Kapitola obsahuje pouze vybrané faktory , které ovlivňují plánování a koordinaci zakázek ve strojírenské firmě.  Detailn...
  ❌ #12   -5.670  Kapitola obsahuje pouze vybrané faktory , které ovlivňují operativní řízení výroby ve strojírenské firmě.  Detailněji: d...
  ❌ #13   -5.717  Kapitola obsahuje pouze vybrané faktory , které ovlivňují řízení pohledávek ve strojírenské firmě. Detailněji: dokument:...
  ❌ #14   -5.730  Kapitola obsahuje pouze vybrané faktory , které ovlivňují tvorbu strategie strojírenské firmy a celé strategické řízení....
  ❌ #15   -5.766  Kapitola obsahuje pouze vybrané faktory , které ovlivňují finanční řízení ve strojírenské firmě.  Detailněji: dokument: ...
  ❌ #16   -5.767  Kapitola obsahuje pouze vybrané faktory , které ovlivňují řízení práce a mezd ve strojírenské firmě. Detailněji: dokumen...
  ❌ #17   -5.878  Kapitola obsahuje pouze vybrané faktory , které ovlivňují dílenské řízení výroby ve strojírenské firmě. Detailněji: doku...
  ❌ #18   -5.925  Kapitola obsahuje pouze vybrané faktory , které ovlivňují řízení závazků ve strojírenské firmě.  Detailněji: dokument: [...
  ❌ #19   -6.055  Kapitola obsahuje pouze vybrané faktory , které ovlivňují řízení prodejů ve strojírenské firmě.  Detailněji: dokument: [...
  ❌ #20   -6.288  Kapitola obsahuje pouze vybrané faktory , které ovlivňují controlling ve strojírenské firmě.  Detailněji: dokument: [Str...

🔀 Reranking grafových dokumentů...
  📊 Reranking [graph] (16 docs → top 10):
  Rank    Score  Preview
  ----------------------------------------------------------------------
  ✅ #1     4.470  Účelem úlohy je vytvářet, a především udržovat aktualizovaná veškerá výrobní data , dokumentaci přípravy výroby (viz dal...
  ✅ #2    -0.104  **TPV zahrnuje :**   - konstrukční přípravu výroby - zpracování návrhu výrobku a konstrukční řešení výrobku a jeho ověře...
  ✅ #3    -1.345  Celkový přehled úloh TPV obsahuje další obrázek:   *Obrázek 16-1: TPV - přehled úloh*   Souhrnný pohled na vybrané aktiv...
  ✅ #4    -2.863  - Analýzy ukazatelů pro operativní plánování výroby dle vybraných dimenzí, např. nákladů na výrobní zakázku, objemu rozp...

/var/folders/bq/dvsycyn560sgx_gql985ch9w0000gn/T/ipykernel_55056/1246177949.py:192: DeprecationWarning: LangchainLLMWrapper is deprecated and will be removed in a future version. Use llm_factory instead: from openai import OpenAI; from ragas.llms import llm_factory; llm = llm_factory('gpt-4o-mini', client=OpenAI(api_key='...'))
  ragas_llm = LangchainLLMWrapper(llm_judge)
/var/folders/bq/dvsycyn560sgx_gql985ch9w0000gn/T/ipykernel_55056/1246177949.py:193: DeprecationWarning: LangchainEmbeddingsWrapper is deprecated and will be removed in a future version. Use the modern embedding providers instead: embedding_factory('openai', model='text-embedding-3-small', client=openai_client) or from ragas.embeddings import OpenAIEmbeddings, GoogleEmbeddings, HuggingFaceEmbeddings
  ragas_emb = LangchainEmbeddingsWrapper(embeddings)

Evaluating:   0%|          | 0/144 [00:00<?, ?it/s]

ERROR:ragas.executor:Exception raised in Job[4]: OutputParserException(Invalid json output: Klíčové aktivity v evidenci TPV jsou:
For troubleshooting, visit: https://docs.langchain.com/oss/python/langchain/errors/OUTPUT_PARSING_FAILURE )

📊 VÝSLEDKY PER OTÁZKA — strojirenska_firma

,method,question,BERTScore_P,BERTScore_R,BERTScore_F1,ROUGE_L_P,ROUGE_L_R,ROUGE_L_F1,faithfulness,answer_relevancy,context_recall,answer_correctness
0,Naive RAG,Jake jsou klíčové aktivity v evidenci TPV?,0.660,0.691,0.675,0.085,0.211,0.121,0.800,0.532,0.500,0.172
1,Graph RAG,Jake jsou klíčové aktivity v evidenci TPV?,0.651,0.769,0.705,0.138,1.000,0.243,NaN,0.883,1.000,0.417
2,Hybrid GraphRAG,Jake jsou klíčové aktivity v evidenci TPV?,0.671,0.812,0.735,0.220,0.915,0.354,0.917,0.517,1.000,0.685
3,Naive RAG,Jaké funkce zahrnuje pokročilá analytika v mar...,0.667,0.800,0.727,0.188,0.569,0.283,1.000,0.644,1.000,0.957
4,Graph RAG,Jaké funkce zahrnuje pokročilá analytika v mar...,0.617,0.665,0.640,0.067,0.176,0.097,0.833,0.467,0.000,0.173
5,Hybrid GraphRAG,Jaké funkce zahrnuje pokročilá analytika v mar...,0.662,0.766,0.711,0.176,0.451,0.253,1.000,0.619,1.000,0.746
6,Naive RAG,Jaké jsou klíčové aktivity analytické úlohy v ...,0.613,0.649,0.630,0.073,0.164,0.101,1.000,0.678,0.857,0.925
7,Graph RAG,Jaké jsou klíčové aktivity analytické úlohy v ...,0.761,0.872,0.813,0.510,0.891,0.649,1.000,0.691,1.000,0.837
8,Hybrid GraphRAG,Jaké jsou klíčové aktivity analytické úlohy v ...,0.669,0.806,0.731,0.200,0.945,0.330,0.091,0.678,1.000,0.599
9,Naive RAG,Jaký je účel TPV v technické přípravě?,0.661,0.738,0.698,0.118,0.400,0.183,0.909,0.501,1.000,0.963
10,Graph RAG,Jaký je účel TPV v technické přípravě?,0.951,0.984,0.967,0.923,1.000,0.960,1.000,0.618,1.000,0.999
11,Hybrid GraphRAG,Jaký je účel TPV v technické přípravě?,0.951,0.984,0.967,0.923,1.000,0.960,1.000,0.621,1.000,0.999
12,Naive RAG,Jaký je účel dílenského řízení výroby (DŘV)?,0.621,0.680,0.650,0.137,0.311,0.190,1.000,0.524,0.667,0.505
13,Graph RAG,Jaký je účel dílenského řízení výroby (DŘV)?,0.638,0.729,0.681,0.171,0.467,0.250,1.000,0.659,1.000,0.570
14,Hybrid GraphRAG,Jaký je účel dílenského řízení výroby (DŘV)?,0.687,0.785,0.733,0.170,0.578,0.263,1.000,0.603,1.000,0.306
15,Naive RAG,Jaký je účel controllingu?,0.726,0.699,0.712,0.250,0.146,0.184,1.000,0.654,1.000,0.700
16,Graph RAG,Jaký je účel controllingu?,0.598,0.853,0.703,0.044,1.000,0.084,1.000,0.625,1.000,0.965
17,Hybrid GraphRAG,Jaký je účel controllingu?,0.649,0.893,0.752,0.259,1.000,0.412,1.000,0.657,1.000,0.988
18,Naive RAG,Jaké jsou vstupy do TPV v oblasti plánování vý...,0.885,0.755,0.815,1.000,0.306,0.469,1.000,0.000,1.000,0.570
19,Graph RAG,Jaké jsou vstupy do TPV v oblasti plánování vý...,0.817,0.863,0.839,0.714,0.968,0.822,1.000,0.492,1.000,0.952
20,Hybrid GraphRAG,Jaké jsou vstupy do TPV v oblasti plánování vý...,0.916,0.953,0.934,0.747,0.903,0.818,1.000,0.462,1.000,0.974
21,Naive RAG,Jaké jsou výstupy z TPV do OŘV?,0.708,0.744,0.726,0.222,0.308,0.258,1.000,0.526,1.000,0.309
22,Graph RAG,Jaké jsou výstupy z TPV do OŘV?,0.635,0.773,0.697,0.115,0.923,0.204,1.000,0.843,1.000,0.316
23,Hybrid GraphRAG,Jaké jsou výstupy z TPV do OŘV?,0.756,0.884,0.815,0.388,1.000,0.559,1.000,0.514,1.000,0.949
24,Naive RAG,Jaké jsou vstupy do DŘV z TPV?,0.672,0.732,0.701,0.091,0.192,0.123,1.000,0.898,1.000,0.443
25,Graph RAG,Jaké jsou vstupy do DŘV z TPV?,0.627,0.789,0.699,0.107,0.846,0.190,1.000,0.833,1.000,0.591
26,Hybrid GraphRAG,Jaké jsou vstupy do DŘV z TPV?,0.855,0.938,0.894,0.703,1.000,0.825,1.000,0.792,1.000,0.471
27,Naive RAG,Co je to strukturní analytický kusovník?,0.578,0.656,0.615,0.045,0.254,0.076,0.000,0.664,0.000,0.250
28,Graph RAG,Co je to strukturní analytický kusovník?,0.763,0.874,0.815,0.375,0.966,0.540,0.636,0.432,1.000,0.805
29,Hybrid GraphRAG,Co je to strukturní analytický kusovník?,0.602,0.738,0.663,0.127,0.559,0.207,1.000,0.615,1.000,0.444
30,Naive RAG,Jaké jsou základní charakteristiky OŘV?,0.777,0.854,0.814,0.724,1.000,0.840,1.000,0.557,1.000,0.959
31,Graph RAG,Jaké jsou základní charakteristiky OŘV?,0.583,0.676,0.626,0.063,0.262,0.102,0.000,0.507,0.000,0.702
32,Hybrid GraphRAG,Jaké jsou základní charakteristiky OŘV?,0.804,0.868,0.835,0.748,0.988,0.851,1.000,0.571,1.000,0.959
33,Naive RAG,Jaké KPI se využívají v technické přípravě výr...,0.624,0.688,0.655,0.050,0.238,0.083,1.000,0.515,0.400,0.376
34,Graph RAG,Jaké KPI se využívají v technické přípravě výr...,0.700,0.896,0.786,0.196,1.000,0.328,1.000,0.490,1.000,0.940
35,Hybrid GraphRAG,Jaké KPI se využívají v technické přípravě výr...,0.716,0.923,0.807,0.328,1.000,0.494,1.000,0.503,1.000,0.953

📊 PRŮMĚRNÉ SKÓRE — strojirenska_firma

,BERTScore_P,BERTScore_R,BERTScore_F1,ROUGE_L_P,ROUGE_L_R,ROUGE_L_F1,faithfulness,answer_relevancy,context_recall,answer_correctness
method,,,,,,,,,,
Graph RAG,0.695,0.812,0.748,0.285,0.792,0.372,0.861,0.629,0.833,0.689
Hybrid GraphRAG,0.745,0.862,0.798,0.416,0.862,0.527,0.917,0.596,1.000,0.756
Naive RAG,0.683,0.724,0.701,0.249,0.342,0.243,0.892,0.558,0.785,0.594

🏆 Nejlepší ROUGE-L Recall (úplnost):       Hybrid GraphRAG
🏆 Nejlepší BERTScore F1 (sémantika):        Hybrid GraphRAG
🏆 Nejlepší Answer Correctness (RAGAS):      Hybrid GraphRAG

✅ Výsledky uloženy → evaluation_strojirenska_firma.csv

,document,method,question,answer,context,time_s,BERTScore_P,BERTScore_R,BERTScore_F1,ROUGE_L_P,ROUGE_L_R,ROUGE_L_F1,faithfulness,answer_relevancy,context_recall,answer_correctness
0,strojirenska_firma,Naive RAG,Jake jsou klíčové aktivity v evidenci TPV?,Klíčové aktivity v evidenci TPV (Technické pří...,Účelem je vytvářet a zajistit průběžnou operat...,23.6,0.660134,0.691110,0.675267,0.084746,0.211268,0.120968,0.800000,0.531999,0.500000,0.171632
1,strojirenska_firma,Graph RAG,Jake jsou klíčové aktivity v evidenci TPV?,Klíčové aktivity v evidenci TPV (Technické pří...,### DOKUMENTY Z GRAFU:\nÚčelem úlohy je vytvář...,34.7,0.650801,0.768885,0.704932,0.138132,1.000000,0.242735,NaN,0.883478,1.000000,0.416898
2,strojirenska_firma,Hybrid GraphRAG,Jake jsou klíčové aktivity v evidenci TPV?,Klíčové aktivity v evidenci TPV (Technické pří...,### 1. DOKUMENTY Z GRAFU (PRIMÁRNÍ ZDROJ - ČTĚ...,28.8,0.671422,0.812179,0.735123,0.219595,0.915493,0.354223,0.916667,0.516861,1.000000,0.684832
3,strojirenska_firma,Naive RAG,Jaké funkce zahrnuje pokročilá analytika v mar...,Pokročilá analytika v marketingu zahrnuje násl...,- Jaké klíčové funkce a aktivity má zahrnovat ...,22.7,0.667100,0.799589,0.727360,0.188312,0.568627,0.282927,1.000000,0.643843,1.000000,0.957472
4,strojirenska_firma,Graph RAG,Jaké funkce zahrnuje pokročilá analytika v mar...,"Není možné odpovědět na otázku, protože se týk...",### DOKUMENTY Z GRAFU:\nÚčelem je řešit finanč...,15.1,0.616820,0.665422,0.640200,0.066667,0.176471,0.096774,0.833333,0.467438,0.000000,0.173291
5,strojirenska_firma,Hybrid GraphRAG,Jaké funkce zahrnuje pokročilá analytika v mar...,Pokročilá analytika v marketingu zahrnuje násl...,### 1. DOKUMENTY Z GRAFU (PRIMÁRNÍ ZDROJ - ČTĚ...,17.9,0.662463,0.766282,0.710601,0.175573,0.450980,0.252747,1.000000,0.619493,1.000000,0.746291
6,strojirenska_firma,Naive RAG,Jaké jsou klíčové aktivity analytické úlohy v ...,Klíčovými aktivitami analytické úlohy v contro...,Jako podstatné výstupy z controllingu jsou: \...,17.7,0.612903,0.648730,0.630308,0.072581,0.163636,0.100559,1.000000,0.677789,0.857143,0.924571
7,strojirenska_firma,Graph RAG,Jaké jsou klíčové aktivity analytické úlohy v ...,Klíčové aktivity analytické úlohy v controllin...,### DOKUMENTY Z GRAFU:\nÚčelem analytické úloh...,16.8,0.761158,0.871941,0.812792,0.510417,0.890909,0.649007,1.000000,0.691226,1.000000,0.836733
8,strojirenska_firma,Hybrid GraphRAG,Jaké jsou klíčové aktivity analytické úlohy v ...,Analytická úloha v kontrollingu zahrnuje kompl...,### 1. DOKUMENTY Z GRAFU (PRIMÁRNÍ ZDROJ - ČTĚ...,24.7,0.668770,0.805842,0.730935,0.200000,0.945455,0.330159,0.090909,0.678099,1.000000,0.598735
9,strojirenska_firma,Naive RAG,Jaký je účel TPV v technické přípravě?,Účelem Technických postupů výroby (TPV) v tech...,Účelem analytické úlohy je především dosažení ...,13.9,0.661023,0.738357,0.697553,0.118227,0.400000,0.182510,0.909091,0.501090,1.000000,0.962875
10,strojirenska_firma,Graph RAG,Jaký je účel TPV v technické přípravě?,Účelem TPV (Technické Přípravy Výroby) je přip...,### DOKUMENTY Z GRAFU:\n**TPV zahrnuje :** \n...,16.8,0.951136,0.983583,0.967088,0.923077,1.000000,0.960000,1.000000,0.618015,1.000000,0.999432
11,strojirenska_firma,Hybrid GraphRAG,Jaký je účel TPV v technické přípravě?,Účelem TPV (Technické Přípravy Výroby) je přip...,### 1. DOKUMENTY Z GRAFU (PRIMÁRNÍ ZDROJ - ČTĚ...,18.0,0.951136,0.983583,0.967088,0.923077,1.000000,0.960000,1.000000,0.621445,1.000000,0.999432
12,strojirenska_firma,Naive RAG,Jaký je účel dílenského řízení výroby (DŘV)?,Účelem dílenského řízení výroby (DŘV) je dosaž...,- PLC.\n- SCADA. \n- Robotika.\n- Digitální d...,7.7,0.621436,0.680375,0.649571,0.137255,0.311111,0.190476,1.000000,0.523948,0.666667,0.505453
13,strojirenska_firma,Graph RAG,Jaký je účel dílenského řízení výroby (DŘV)?,Účelem dílenského řízení výroby (DŘV) je opera...,### DOKUMENTY Z GRAFU:\nÚčelem úlohy je operat...,18.8,0.638397,0.728664,0.680550,0.170732,0.466667,0.250000,1.000000,0.659039,1.000000,0.570367
14,strojirenska_firma,Hybrid GraphRAG,Jaký je účel dílenského řízení výroby (DŘV)?,Účelem dílenského řízení výroby (DŘV) je opera...,### 1. DOKUMENTY Z GRAFU (PRIMÁRNÍ ZDROJ - ČTĚ...,21.1,0.687052,0.784995,0.732765,0.169935,0.577778,0.262626,1.000000,0.602703,1.000000,0.305514
15,strojirenska_firma,Naive RAG,Jaký je účel controllingu?,Účelem controllingu je zajistit komplexní anal...,Jako podstatné výstupy z controllingu jsou: \...,11.3,0.725689,0.698763,0.711972,0.250000,0.145833,0.184211,1.000000,0.653823,1.000000,0.700167
16,strojirenska_firma,Graph RAG,Jaký je účel controllingu?,Účelem controllingu je koordinace systému říze...,### DOKUMENTY Z GRAFU:\nÚčelem controllingu je...,61.5,0.598128,0.852559,0.703032,0.043796,1.000000,0.083916,1.000000,0.625346,1.000000,0.965019
17,strojirenska_firma,Hybrid GraphRAG,Jaký je účel controllingu?,Účelem controllingu je koordinace systému říze...,### 1. DOKUMENTY Z GRAFU (PRIMÁRNÍ ZDROJ - ČTĚ...,20.4,0.649396,0.892791,0.751886,0.259459,1.000000,0.412017,1.000000,0.656831,1.000000,0.987578
18,strojirenska_firma,Naive RAG,Jaké jsou vstupy do TPV v oblasti plánování vý...,"Plán výrobních zakázek, Plánovací sešit výroby...",Jako podstatné výstupy z řízení práce a mezd j...,24.0,0.885113,0.755468,0.815168,1.000000,0.306452,0.469136,1.000000,0.000000,1.000000,0.569621
19,strojirenska_firma,Graph RAG,Jaké jsou vstupy do TPV v oblasti plánování vý...,Vstupy do TPV v oblasti plánování výrobních za...,### DOKUMENTY Z GRAFU:\nPodstatné vstupy do TP...,17.7,0.816568,0.863184,0.839229,0.714286,0.967742,0.821918,1.000000,0.492467,1.000000,0.951584
20,strojirenska_firma,Hybrid GraphRAG,Jaké jsou vstupy do TPV v oblasti plánování vý...,Podle textu je vstupy do TPV z oblasti plánová...,### 1. DOKUMENTY Z GRAFU (PRIMÁRNÍ ZDROJ - ČTĚ...,18.8,0.916233,0.953435,0.934464,0.746667,0.903226,0.817518,1.000000,0.461510,1.000000,0.974028
21,strojirenska_firma,Naive RAG,Jaké jsou výstupy z TPV do OŘV?,Výstupy z TPV (Technické přípravě výroby) do O...,Jako podstatné výstupy z řízení práce a mezd j...,9.5,0.708475,0.744162,0.725880,0.222222,0.307692,0.258065,1.000000,0.526117,1.000000,0.308956
22,strojirenska_firma,Graph RAG,Jaké jsou výstupy z TPV do OŘV?,Výstupy z TPV (Technické a technologické přípr...,### DOKUMENTY Z GRAFU:\nJako podstatné výstupy...,24.1,0.634948,0.772709,0.697088,0.114833,0.923077,0.204255,1.000000,0.843008,1.000000,0.316402
23,strojirenska_firma,Hybrid GraphRAG,Jaké jsou výstupy z TPV do OŘV?,Výstupy z TPV do OŘV jsou:\n\n- Kusovníky\n- K...,### 1. DOKUMENTY Z GRAFU (PRIMÁRNÍ ZDROJ - ČTĚ...,20.2,0.756263,0.883739,0.815047,0.388060,1.000000,0.559140,1.000000,0.513751,1.000000,0.949451
24,strojirenska_firma,Naive RAG,Jaké jsou vstupy do DŘV z TPV?,Podle textu jsou vstupy do DŘV (Dílenské řízen...,Jako podstatné výstupy z řízení práce a mezd j...,17.3,0.672457,0.731618,0.700791,0.090909,0.192308,0.123457,1.000000,0.897991,1.000000,0.442979
25,strojirenska_firma,Graph RAG,Jaké jsou vstupy do DŘV z TPV?,Vstupy do DŘV (Dílenské řízení výroby) z TPV (...,### DOKUMENTY Z GRAFU:\nPodstatné vstupy do DŘ...,22.7,0.626951,0.789402,0.698860,0.107317,0.846154,0.190476,1.000000,0.832826,1.000000,0.590936
26,strojirenska_firma,Hybrid GraphRAG,Jaké jsou vstupy do DŘV z TPV?,Podle textu je jeden ze vstupů do DŘV z TPV:\n...,### 1. DOKUMENTY Z GRAFU (PRIMÁRNÍ ZDROJ - ČTĚ...,18.6,0.855049,0.937580,0.894414,0.702703,1.000000,0.825397,1.000000,0.791621,1.000000,0.471025
27,strojirenska_firma,Naive RAG,Co je to strukturní analytický kusovník?,Strukturní analytický kusovník (SAC) je nástro...,- PLC.\n- SCADA.\n- Robotika.\n- Digitální dvo...,15.0,0.578413,0.656013,0.614774,0.044510,0.254237,0.075758,0.000000,0.664022,0.000000,0.249622
28,strojirenska_firma,Graph RAG,Co je to strukturní analytický kusovník?,Strukturní analytický kusovník je typ dokument...,### DOKUMENTY Z GRAFU:\nÚčelem úlohy je vytvář...,19.1,0.762887,0.873759,0.814568,0.375000,0.966102,0.540284,0.636364,0.432471,1.000000,0.805196
29,strojirenska_firma,Hybrid GraphRAG,Co je to strukturní analytický kusovník?,"Strukturní analytický kusovník je dokument, kt...",### 1. DOKUMENTY Z GRAFU (PRIMÁRNÍ ZDROJ - ČTĚ...,27.7,0.602089,0.738014,0.663158,0.126923,0.559322,0.206897,1.000000,0.614564,1.000000,0.443776
30,strojirenska_firma,Naive RAG,Jaké jsou základní charakteristiky OŘV?,**Obrázek 17-1: OŘV - přehled úloh**\n\n**¨Zák...,"Úloha má reportingový charakter, tj. zpracován...",13.0,0.776591,0.854111,0.813508,0.724138,1.000000,0.840000,1.000000,0.556509,1.000000,0.958867
31,strojirenska_firma,Graph RAG,Jaké jsou základní charakteristiky OŘV?,**OŘV (Operativní a Reaktivní Vedení)**\n\nOŘV...,### DOKUMENTY Z GRAFU:\nAplikace se váže zejmé...,21.1,0.583405,0.675961,0.626282,0.063401,0.261905,0.102088,0.000000,0.507225,0.000000,0.701800
32,strojirenska_firma,Hybrid GraphRAG,Jaké jsou základní charakteristiky OŘV?,**Základní charakteristiky OŘV:**\n\n1. Využí...,### 1. DOKUMENTY Z GRAFU (PRIMÁRNÍ ZDROJ - ČTĚ...,15.4,0.803973,0.868247,0.834875,0.747748,0.988095,0.851282,1.000000,0.571150,1.000000,0.959199
33,strojirenska_firma,Naive RAG,Jaké KPI se využívají v technické přípravě výr...,Klíčové ukazatele (KPI) používané v technické ...,Účetní řídí v celém rozsahu operace spojené s ...,15.0,0.624103,0.688326,0.654643,0.050000,0.238095,0.082645,1.000000,0.515047,0.400000,0.376457
34,strojirenska_firma,Graph RAG,Jaké KPI se využívají v technické přípravě výr...,V oblasti technické přípravy výroby se využíva...,### DOKUMENTY Z GRAFU:\nDalší přehled metrik p...,18.8,0.699846,0.896053,0.785888,0.196262,1.000000,0.328125,1.000000,0.490244,1.000000,0.940381
35,strojirenska_firma,Hybrid GraphRAG,Jaké KPI se využívají v technické přípravě výr...,V technické přípravě výroby se využívají násle...,### 1. DOKUMENTY Z GRAFU (PRIMÁRNÍ ZDROJ - ČTĚ...,19.6,0.716405,0.922538,0.806509,0.328125,1.000000,0.494118,1.000000,0.502606,1.000000,0.952824